apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tekton-kueue
    control-plane: controller-manager
  name: tekton-kueue
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tekton-kueue
  name: tekton-kueue-controller-manager
  namespace: tekton-kueue
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tekton-kueue
  name: tekton-kueue-webhook
  namespace: tekton-kueue
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tekton-kueue
  name: tekton-kueue-leader-election-role
  namespace: tekton-kueue
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-kueue-webhook-role
  namespace: tekton-kueue
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-kueue-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - resourceflavors
  - workloadpriorityclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - workloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - workloads/finalizers
  verbs:
  - update
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - workloads/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  verbs:
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns/finalizers
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-kueue-metrics-auth-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-kueue-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tekton-kueue
  name: tekton-kueue-leader-election-rolebinding
  namespace: tekton-kueue
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-kueue-leader-election-role
subjects:
- kind: ServiceAccount
  name: tekton-kueue-controller-manager
  namespace: tekton-kueue
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tekton-kueue
  name: tekton-kueue-webhook-rolebinding
  namespace: tekton-kueue
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-kueue-webhook-role
subjects:
- kind: ServiceAccount
  name: tekton-kueue-webhook
  namespace: tekton-kueue
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tekton-kueue
  name: tekton-kueue-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-kueue-manager-role
subjects:
- kind: ServiceAccount
  name: tekton-kueue-controller-manager
  namespace: tekton-kueue
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-kueue-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-kueue-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: tekton-kueue-controller-manager
  namespace: tekton-kueue
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-kueue-metrics-auth-webhook-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-kueue-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: tekton-kueue-webhook
  namespace: tekton-kueue
---
apiVersion: v1
data:
  config.yaml: |
    queueName: pipelines-queue
    cel:
      expressions:
        - priority("tekton-kueue-default")
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/part-of: tekton-kueue
  name: tekton-kueue-config
  namespace: tekton-kueue
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tekton-kueue
    control-plane: controller-manager
  name: tekton-kueue-controller-manager-metrics-service
  namespace: tekton-kueue
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: metrics-server
  selector:
    app.kubernetes.io/name: tekton-kueue
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tekton-kueue-webhook
  name: tekton-kueue-webhook-service
  namespace: tekton-kueue
spec:
  ports:
  - name: webhook-server
    port: 443
    protocol: TCP
    targetPort: webhook-server
  - name: metrics-server
    port: 8443
    protocol: TCP
    targetPort: metrics-server
  selector:
    app.kubernetes.io/name: tekton-kueue-webhook
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tekton-kueue
    control-plane: controller-manager
  name: tekton-kueue-controller-manager
  namespace: tekton-kueue
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tekton-kueue
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/name: tekton-kueue
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - controller
        - --leader-elect
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=:8443
        - --metrics-cert-path=/tmp/k8s-metrics-server/metrics-certs
        command:
        - /manager
        image: quay.io/openshift-pipeline/kueue-rhel9@sha256:eee9726727af73afdf61fbedb47f7d2a48fc4abecaddf944d620d39d3a326388
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 8443
          name: metrics-server
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp/k8s-metrics-server/metrics-certs
          name: metrics-certs
          readOnly: true
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: tekton-kueue-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: metrics-certs
        secret:
          items:
          - key: ca.crt
            path: ca.crt
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
          optional: false
          secretName: controller-manager-metrics-server-cert
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tekton-kueue-webhook
    control-plane: controller-manager
  name: tekton-kueue-webhook
  namespace: tekton-kueue
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tekton-kueue-webhook
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: webhook
      labels:
        app.kubernetes.io/name: tekton-kueue-webhook
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - webhook
        - --health-probe-bind-address=:8081
        - --webhook-cert-path=/tmp/k8s-webhook-server/serving-certs
        - --metrics-bind-address=:8443
        - --metrics-cert-path=/tmp/k8s-metrics-server/metrics-certs
        command:
        - /manager
        image: quay.io/openshift-pipeline/kueue-rhel9@sha256:eee9726727af73afdf61fbedb47f7d2a48fc4abecaddf944d620d39d3a326388
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: webhook
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 8443
          name: metrics-server
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: webhook-certs
          readOnly: true
        - mountPath: /tmp/k8s-metrics-server/metrics-certs
          name: metrics-certs
          readOnly: true
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: tekton-kueue-webhook
      terminationGracePeriodSeconds: 10
      volumes:
      - name: webhook-certs
        secret:
          secretName: webhook-server-cert
      - name: metrics-certs
        secret:
          items:
          - key: ca.crt
            path: ca.crt
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
          optional: false
          secretName: webhook-metrics-server-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tekton-kueue
  name: tekton-kueue-controller-manager-metrics-certs
  namespace: tekton-kueue
spec:
  dnsNames:
  - tekton-kueue-controller-manager-metrics-service.tekton-kueue.svc
  - tekton-kueue-controller-manager-metrics-service.tekton-kueue.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: tekton-kueue-selfsigned-issuer
  secretName: controller-manager-metrics-server-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tekton-kueue
  name: tekton-kueue-serving-cert
  namespace: tekton-kueue
spec:
  dnsNames:
  - tekton-kueue-webhook-service.tekton-kueue.svc
  - tekton-kueue-webhook-service.tekton-kueue.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: tekton-kueue-selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tekton-kueue
  name: tekton-kueue-webhook-metrics-certs
  namespace: tekton-kueue
spec:
  dnsNames:
  - tekton-kueue-webhook-service.tekton-kueue.svc
  - tekton-kueue-webhook-service.tekton-kueue.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: tekton-kueue-selfsigned-issuer
  secretName: webhook-metrics-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tekton-kueue
  name: tekton-kueue-selfsigned-issuer
  namespace: tekton-kueue
spec:
  selfSigned: {}
---
apiVersion: kueue.x-k8s.io/v1beta1
description: tekton-kueue default priority class
kind: WorkloadPriorityClass
metadata:
  name: tekton-kueue-default
  namespace: tekton-kueue
value: 0
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: tekton-kueue/tekton-kueue-serving-cert
  name: tekton-kueue-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: tekton-kueue-webhook-service
      namespace: tekton-kueue
      path: /mutate-tekton-dev-v1-pipelinerun
  failurePolicy: Fail
  name: pipelinerun-kueue-defaulter.tekton-kueue.io
  rules:
  - apiGroups:
    - tekton.dev
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pipelineruns
  sideEffects: None
