versions:
  current: 5.0.5-756
  previous: 5.0.5-755
  previous_range: 1.20.0
  channel: pipelines-5.0
  openshift:
    latest: 4.20 # lastest GA'ed openshift
    min: 4.12 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-controller-rhel9@sha256:bcd247afad787369b6398b9c80c8248a70443b2a50e5b421725a1b73e78dab45
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-webhook-rhel9@sha256:16b4cb6797a19bf40450fc60f9184767a5191a2cb6da410c02faef918e773f2e
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-resolvers-rhel9@sha256:6a0977a2c1bff6eccccb6c0f43346e94c15e5a8f4efa04c86c07b16b034cadbe
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-events-rhel9@sha256:d127085a586d5d1a8412ba0092216b3e7e87bc66ad948041a7efa5a200e39e4f
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-entrypoint-rhel9@sha256:be220407b502731a9bf03b753725670930ea91b972f70c950ef76264590f993e
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-workingdirinit-rhel9@sha256:1966830a2bdafa5e7dd142d97cbcb3d1fffc643c7de1704b312425e9ed73b4ed
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-nop-rhel9@sha256:af31935144a3de67cebd1d1fa8ef652b6ced2b96e32cc06757a800a80e3899de
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-entrypoint-rhel9@sha256:be220407b502731a9bf03b753725670930ea91b972f70c950ef76264590f993e
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-sidecarlogresults-rhel9@sha256:a1687042b5a5e2777fda97079ab26f683b2b843d4427a541430fb8c4e85376cb
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-controller-rhel9@sha256:7eaf44ffc5fed8c9da69c18629b0268038534b0a2692b8c8d7054cb53623feac
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-webhook-rhel9@sha256:541b93d05d36ea37e9e688b25f9bacab6ad3ca92052b6975694bfb2332c0340b
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-core-interceptors-rhel9@sha256:57f7ec2bacc494e3cf8a268e317497d317269e014877e28d570b62b70fa9d0ea
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-eventlistenersink-rhel9@sha256:7b0c267eb208560e3a997f68d75c44eeaa03211096e951bbf78f787bf6ecfa47
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-chains-controller-rhel9@sha256:4029c6f4920a87bd8a0610ab1a310d1752bbbe52660d0fd8364370c9d8d9baa8
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-hub-db-migration-rhel9@sha256:84b0435aac4e93f42a81c64ae8d8fc8dc819b65deb80c1ddd64a405ee2c72273
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-hub-api-rhel9@sha256:c8443833598d8eb74859f07e92a6f3e4a20d574180d51d17527e1740c2c7a67c
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-hub-ui-rhel9@sha256:3e7428f2d1d8c1a8a9f695414b0583628a496cc65ba575b72460afcfbde8530a
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-results-watcher-rhel9@sha256:a30b0dcf4c8a3df2df4b1b536b3e56f60edc2e0d169f85c315eed1ce615667af
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-results-api-rhel9@sha256:02b07e5cf3a720af50007bd585439648c9d3d2b4d64d200d18622df178a601f5
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-results-retention-policy-agent-rhel9@sha256:0f9e4603df51717495b44b76fa1c14521811acbd92db585eea1118c8b68aaf88
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cli-tkn-rhel9@sha256:2871101262adbe8c590340734a39578d95ac462983f8157383a13b51e10078ab
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cli-tkn-rhel9@sha256:2871101262adbe8c590340734a39578d95ac462983f8157383a13b51e10078ab
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cli-tkn-rhel9@sha256:2871101262adbe8c590340734a39578d95ac462983f8157383a13b51e10078ab
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-serve-tkn-cli-rhel9@sha256:ac27f336d3e4e9e2538a867c1a956ca8328428948dd72d9ad6456c346ab48989
  - name: IMAGE_ADDONS_TKN_CLI_SERVE_INIT_CONFIG
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-serve-tkn-cli-rhel9@sha256:ac27f336d3e4e9e2538a867c1a956ca8328428948dd72d9ad6456c346ab48989
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-manual-approval-gate-webhook-rhel9@sha256:2d28f04094dfc8ad97daa60581cbc160aef35f61becd0c2776398566a6480db9
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-manual-approval-gate-controller-rhel9@sha256:57fa09974c072e2affb29fd079818cfa3f19796383d2c567fc16b4da3f5d42e7
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-controller-rhel9@sha256:bedfc28fe0db6cb6353d9aa051cbc5a3642a16c810ce43f8352a5a6b1e1b90a8
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-webhook-rhel9@sha256:b93416ed90e54892ab487f8e8f7e640da8d11406efcc07b6d45415e1d337fb87
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-watcher-rhel9@sha256:b0d8df36f39e868a124588ba7b7be4d2e98ab99f87b9b7bbfcbfcba99b7080d0
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-cli-rhel9@sha256:810ca31a095c1db3ad41e756818c1d77d843a4602c0c66369700ba678967ce0d
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-rhel9-operator@sha256:8e461d295a924b197b242ba247e654ee889659e6e413a440aac9a9059869de6f
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-rhel9-operator@sha256:8e461d295a924b197b242ba247e654ee889659e6e413a440aac9a9059869de6f
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-operator-proxy-rhel9@sha256:8b6b806a71656b7ef7f384d1c916b84e026d96406a815d1af1dd012468d601e4
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-operator-webhook-rhel9@sha256:6dfb23cbe9f2d5a3ddd6375de5f40fc5e7e29fdd69ff9e14405ce68602632c8e
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cache-rhel9@sha256:43a17e72e22a700cef1df704c8971bc0403412643c58cf744c2e211be61b7072
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cache-rhel9@sha256:43a17e72e22a700cef1df704c8971bc0403412643c58cf744c2e211be61b7072
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-console-plugin-rhel9@sha256:bb058b3de08a97a38b1eb1c65df636dcb0632194c30c4d57569762097f9b6b86
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-operator-bundle@sha256:f65476d405feee6223afdda382412f945627354c8f03224aa2ce51576e701cdc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-opc-rhel9@sha256:ae7ce6ffc5b084276e6e754a0f89493cd25cd78c5b515c31ec81c31b9c716e2c
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pruner-controller-rhel9@sha256:9518c4bc1cb0498caa496f72df3ffefd6d0320e38b66640268d44a78be019ed9
  - name: IMAGE_PRUNER_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pruner-webhook-rhel9@sha256:e640d0e01736af6519d4341ce4b0440991e35044fd45d0a048d72af097d239e7
