versions:
  current: 5.0.5-479
  previous: 5.0.5-478
  previous_range: 1.16.0
  channel: pipelines-5.0
  openshift:
    latest: 4.17 # lastest GA'ed openshift
    min: 4.16    # Minimum version OSP supports
images:
# tektoncd-pipeline
- name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/controller@sha256:7fea61cbe666823f25dc60b9c02e7bbc31e82d0f093270654f85ef6ef590583a
- name: IMAGE_PIPELINES_WEBHOOK
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/webhook@sha256:5b4be0904a60f9b980b7fa81e7b6c371b732a4b0584461ede168503fc10d9bac
- name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/resolvers@sha256:ab14facc6b475c8d48d8ab02fb653bbcd98a168131354ab6289bfd6ee676fda4
- name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/events@sha256:daaa14261d5c20c41763c5d84c7942d15b350b55b888f3be8c5e047f2b31d28d
- name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/entrypoint@sha256:8496156f9996901e60c61e6979bcdf83208ca03474ebe4cde9cdc9eeb6394066
- name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/workingdirinit@sha256:8515af0c79e8df8e4abc5ea9f649435c5efd108a0467529214937094d5fbf010
- name: IMAGE_PIPELINES_ARG__NOP_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/nop@sha256:317ebe5a7ac1999946fec1c777ed45369d51829c36c3617126e268c56fd3d3f4
- name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/entrypoint@sha256:8496156f9996901e60c61e6979bcdf83208ca03474ebe4cde9cdc9eeb6394066
# tektoncd-triggers
- name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-main/controller@sha256:cc6e5fddfa874e29d00da8552357310e94c1cc0c8526d1d8c5c920a3f7c1e97f
- name: IMAGE_TRIGGERS_WEBHOOK
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-main/webhook@sha256:43a54333df984bcf775556454e8cf8b067c58cad4007546d92ccfdedd721e698
- name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-main/core-interceptors@sha256:14d0cbafa3b6cab6bc02fc9b04c83c180f372069727a21138d8f962e353298f7
- name: IMAGE_TRIGGERS_ARG__EL_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-main/eventlistenersink@sha256:e93e51981225f8d21263e2a1b78897793bd9ac8dd217d6a2872d074d2b9a8cbb
# tektoncd-chains
- name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-chains-main/controller@sha256:1851a86e3b5014eabb603ca4cbba1dafc05f8c52e4fe1b25916abeb7bacc0917
# tektoncd-hub
- name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-hub-main/db-migration@sha256:1d195b1ba08074832a17bd24dc0df2c22c697863d2f06a265538a4357baa20a9
- name: IMAGE_HUB_TEKTON_HUB_API
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-hub-main/hub-api@sha256:3105034ed8ff46f5fdf9c0d53475ce481fbaaffa6e5eeae3c7bbec115b3b7ba9
- name: IMAGE_HUB_TEKTON_HUB_UI
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-hub-main/hub-ui@sha256:329c09c5895299834e19b09a1f18a22fae57ec8a4c4937e311275370282a7ac5
# tektoncd-results
- name: IMAGE_RESULTS_WATCHER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-results-main/watcher@sha256:85d472af9437cc1553f1521ef550246cfef368132b61ef0fd01fbe96b4e6f577
- name: IMAGE_RESULTS_API
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-results-main/api@sha256:85d472af9437cc1553f1521ef550246cfef368132b61ef0fd01fbe96b4e6f577
- name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-results-main/retention-policy-agent@sha256:85d472af9437cc1553f1521ef550246cfef368132b61ef0fd01fbe96b4e6f577
- name: IMAGE_RESULTS_POSTGRES
  value: registry.redhat.io/rhel8/postgresql-13@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
# tektoncd-cli
- name: IMAGE_JOB_PRUNER_TKN
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-main/tkn@sha256:cb82c5a812be0c37e78d52788b090cb0597aa6be64df4feff056645e377c1724
- name: IMAGE_ADDONS_PARAM_TKN_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-main/tkn@sha256:cb82c5a812be0c37e78d52788b090cb0597aa6be64df4feff056645e377c1724
- name: IMAGE_ADDONS_TKN
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-main/tkn@sha256:cb82c5a812be0c37e78d52788b090cb0597aa6be64df4feff056645e377c1724
- name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
  # value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-main/serve-tkn@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
  value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel8@sha256:cc5234d6a6afc213d24786253c8ea70bb77f3f5c3e1ea1526debb8a1776e4ffc
# manual-approval-gate
- name: IMAGE_MAG_MANUAL_APPROVAL
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/manual-approval-gate-main/webhook@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
- name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/manual-approval-gate-main/controller@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
# pipelines-as-code
- name: IMAGE_PAC_PAC_CONTROLLER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-as-code-main/controller@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
- name: IMAGE_PAC_PAC_WEBHOOK
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-as-code-main/webhook@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
- name: IMAGE_PAC_PAC_WATCHER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-as-code-main/watcher@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
# operator
- name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/operator@sha256:3dfe3a1ecc38d395d270b65cdd766ec53e6768aef10a1d00b18eb04f078ebe5c
- name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/operator@sha256:3dfe3a1ecc38d395d270b65cdd766ec53e6768aef10a1d00b18eb04f078ebe5c
- name: IMAGE_PIPELINES_PROXY
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/proxy@sha256:d788ddbb3195cc22cb0460f3f88250f70f7c3e2e7ffcaf82d98e1d5820286317
- name: TEKTON_OPERATOR_WEBHOOK
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/webhook@sha256:ae6b2c843737980d40dce3b8591c245a2afbc186abe2fc257a5c834daec1995a
# Addons
- name: IMAGE_PIPELINES_ARG__GIT_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
- name: IMAGE_ADDONS_PARAM_GITINITIMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
- name: IMAGE_ADDONS_GIT_RUN
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
- name: IMAGE_ADDONS_REPORT
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
- name: IMAGE_ADDONS_GIT_CLONE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
- name: IMAGE_ADDONS_KN
  value: registry.redhat.io/openshift-serverless-1/client-kn-rhel8@sha256:a5a7b2be50f211d4d9d555b2a2e2302096c139ff5011d984cc386f1530007f16
- name: IMAGE_ADDONS_SKOPEO_RESULTS
  value: registry.redhat.io/rhel8/skopeo@sha256:1dcb4189c92da21ee58b3ca5433615e0208194c8412f7f1fb45fa491179aaf9b
- name: IMAGE_ADDONS_BUILD
  value: registry.redhat.io/rhel8/buildah@sha256:5c7cd7c9a3d49e8905fc98693f6da605aeafae36bde5622dc78e12f31db3cd59
- name: IMAGE_ADDONS_S2I_BUILD
  value: registry.redhat.io/rhel8/buildah@sha256:5c7cd7c9a3d49e8905fc98693f6da605aeafae36bde5622dc78e12f31db3cd59
- name: IMAGE_ADDONS_S2I_GENERATE
  value: registry.redhat.io/source-to-image/source-to-image-rhel8@sha256:6a6025914296a62fdf2092c3a40011bd9b966a6806b094d51eec5e1bd5026ef4
- name: IMAGE_ADDONS_LOAD_SCRIPTS
  value: registry.redhat.io/ubi8/ubi-minimal@sha256:a47c89f02b39a98290f88204ed3d162845db0a0c464b319c2596cfd1e94b444e
- name: IMAGE_ADDONS_MAVEN_GENERATE
  value: registry.redhat.io/ubi8/ubi-minimal@sha256:a47c89f02b39a98290f88204ed3d162845db0a0c464b319c2596cfd1e94b444e
- name: IMAGE_ADDONS_PREPARE
  value: registry.redhat.io/ubi8/ubi-minimal@sha256:a47c89f02b39a98290f88204ed3d162845db0a0c464b319c2596cfd1e94b444e
- name: IMAGE_ADDONS_MAVEN_GOALS
  value: registry.redhat.io/ubi8/openjdk-17@sha256:632e78989471859ca4ed1148b951a911f7e3b6e6516482be20967c4171612c55
