versions:
  current: 1.22.0
  previous: 1.21.0
  previous_range: 1.21.0
  channel: pipelines-1.22
  openshift:
    latest: 4.20 # lastest GA'ed openshift
    min: 4.16 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-controller-rhel9@sha256:66d57e5296b6abb910a94d724e6a82f2b090ccfc0ac0c755ac1535014101865b
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-webhook-rhel9@sha256:00ba29f9d7acc9f9a622cbbd8340199dc15671e7daee2478ff4eab24d07c5763
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-resolvers-rhel9@sha256:2d18a832bb0f7a2a204b2b40178dfd11615ed1028b05fb7bc21177a5edc7b82e
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-events-rhel9@sha256:89ffc0ecd37f651802345916b5aa19f063945d9af2203bbeec617ec4f085aee5
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-entrypoint-rhel9@sha256:330d3789901765b01d1fe7cb78a0eebedb2963712ff65947b68c105d15b2d9a2
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-workingdirinit-rhel9@sha256:e1ebd072c380aa192d1dc9dc1f367fdde4817c99697bc31322305847dabd3b8c
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-nop-rhel9@sha256:302681a7227e7f78ff7e565969ca956034500d67dd4db247d81af42ad0b1cd39
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-entrypoint-rhel9@sha256:330d3789901765b01d1fe7cb78a0eebedb2963712ff65947b68c105d15b2d9a2
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-sidecarlogresults-rhel9@sha256:8282937688000e09e309123dfa4783f37fd2ab2bcf7727866d3c80723ee68d6c
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-controller-rhel9@sha256:2ebb6f9a4cc0b3ce596feafd2a69c55561c7cc6573a5f6db498bad6d7858065b
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-webhook-rhel9@sha256:b250d4662967227cc892d007bb9ad72b1a12aa791839a0d1c8772cb8cea46d85
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-core-interceptors-rhel9@sha256:7c14604fd3cf78eb911df455b47de10367dd858b804fd4de22b085575ef7ecf8
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-eventlistenersink-rhel9@sha256:cd07f7db82638879761cbc686ecc6d475324a4c5755d68255765190e6cd89cd5
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-chains-controller-rhel9@sha256:731b8c842fc5d06e73bf3d03020417f47c24c63fe0dc2f06978ec3de5b829718
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-hub-db-migration-rhel9@sha256:fdc294d98622d4177d42527f71841d1fce1c31b4a419e353b4356091a0ec22b5
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-hub-api-rhel9@sha256:7c3185abbf361e9ca300b5fb858f0d2a14917cc1b971faf1c0767c374876bad6
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-hub-ui-rhel9@sha256:2e3009208ef5fb8782c9d54646d7f1bdd989d6df306c49ae2d956e9686719580
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-results-watcher-rhel9@sha256:a0aa6e5bf4bfe9b381f5484243bb0b25762a18827b5ff2c990381c3c15fd902e
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-results-api-rhel9@sha256:00360381f845cc27eb8cd47d44f8cf09ea9ae292a345f29f8d025bd7d5392732
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-results-retention-policy-agent-rhel9@sha256:8314d57a051d387c8d78e93bb139dc35e7b1211aa9549dee205113b0280d566f
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cli-tkn-rhel9@sha256:1cdc4b484458fc1ae39d61f6858ac71de5237241873c121b532dd2904c4637c8
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cli-tkn-rhel9@sha256:1cdc4b484458fc1ae39d61f6858ac71de5237241873c121b532dd2904c4637c8
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cli-tkn-rhel9@sha256:1cdc4b484458fc1ae39d61f6858ac71de5237241873c121b532dd2904c4637c8
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-serve-tkn-cli-rhel9@sha256:bcf527382808fba18f412d8f36773c215cd5cc6bfae02090bc5f72091f926b4d
  - name: IMAGE_ADDONS_TKN_CLI_SERVE_INIT_CONFIG
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-serve-tkn-cli-rhel9@sha256:bcf527382808fba18f412d8f36773c215cd5cc6bfae02090bc5f72091f926b4d
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-manual-approval-gate-webhook-rhel9@sha256:782467e6e54502227735df9549724ce44d00f2625aae16fcbe28c84f88cef141
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-manual-approval-gate-controller-rhel9@sha256:a115bc1c1bf223527e5e68af97545c299a5840d4e84d8b1fc4cf8f03e1098f94
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-controller-rhel9@sha256:135d65f15972cffed20b4515c4da6eac125cdd44089b7ef09829d9bdee966f54
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-webhook-rhel9@sha256:775d5e23ff9812666d33f3c7dcdebf9461acf0843c1e50c2994459241108aaba
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-watcher-rhel9@sha256:744787aacaf02cb49758e729db3b3338ade11faf71a4714c999487bb9ddd87f2
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-cli-rhel9@sha256:2cafbf1e0707f0857d205d940c7117144178a9aa903af395a721253fbb4e30bc
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-rhel9-operator@sha256:fa12539ed8516d592479d04761569f788c2d825f7335bcc6a4987849126e87ac
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-rhel9-operator@sha256:fa12539ed8516d592479d04761569f788c2d825f7335bcc6a4987849126e87ac
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-operator-proxy-rhel9@sha256:359374727e743945e4f32abc0fb1147289148339953f9febf1a84de86cf1c7a1
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-operator-webhook-rhel9@sha256:11877a159762cb30c3a5552adf3638a71caa0a318a4b2e800221550f2cddc97c
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cache-rhel9@sha256:a24b80822370b4030da2bf9996b01e7cb5ddae5049836c5ffb23363855399670
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cache-rhel9@sha256:a24b80822370b4030da2bf9996b01e7cb5ddae5049836c5ffb23363855399670
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:c0440c386365c1ecec9072c4809fbcf3b42bb09a3539aceb9edc739cc0a10d90
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:c0440c386365c1ecec9072c4809fbcf3b42bb09a3539aceb9edc739cc0a10d90
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:c0440c386365c1ecec9072c4809fbcf3b42bb09a3539aceb9edc739cc0a10d90
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:c0440c386365c1ecec9072c4809fbcf3b42bb09a3539aceb9edc739cc0a10d90
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:c0440c386365c1ecec9072c4809fbcf3b42bb09a3539aceb9edc739cc0a10d90
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:c0440c386365c1ecec9072c4809fbcf3b42bb09a3539aceb9edc739cc0a10d90
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-console-plugin-rhel9@sha256:538c64cd0715b81d9d97580cdb053c519d56b21f5ca398fb69e073bae1107b98
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-opc-rhel9@sha256:fe7dedc55fd023fbdb21ac3b34ca4e157c454e27725d70e52d79849f93a8511c
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pruner-controller-rhel9@sha256:63b5888a87cf45ae008f8b0241394ee59760fbc659ab200536c204cf1b345546
  - name: IMAGE_PRUNER_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pruner-webhook-rhel9@sha256:34e66d49dfaa5b02c0eea281ee73e77f75f41f2b09312df03374da300778066f
  # Scheduler
  - name: IMAGE_SCHEDULER_MANAGER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-scheduler-rhel9@sha256:18c84e6ccdbc3986cf18f8a1b81eb7f47b0002b996f4589075366ae940ad0621
  - name: IMAGE_SCHEDULER_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-scheduler-rhel9@sha256:18c84e6ccdbc3986cf18f8a1b81eb7f47b0002b996f4589075366ae940ad0621
  #multicluster proxy aae
  - name: IMAGE_MULTICLUSTERPROXYAAE_PROXY_SERVER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-multicluster-proxy-aae-proxy-server-rhel9@sha256:298d682977301d7986603e237910685b3b9fc6c769086892fa3502cef5e20e10

