versions:
  current: 1.15.4
  previous: 1.15.3
  previous_range: 1.14.0
  channel: pipelines-1.15
  openshift:
    latest: 4.21 # lastest GA'ed openshift
    min: 4.14 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-controller-rhel8@sha256:43edeec6f956ec7bee908ff093e897fdc8ac6f52ff9be6ce34e6bd2908d20875
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-webhook-rhel8@sha256:036a656456cb72683a3fdb82efe7029b6895469aedd5299300983776286b7b33
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-resolvers-rhel8@sha256:c3268c9355b6dee706ec31767056ef14acd6b43fa2eea681c020282d5e5c42b0
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-events-rhel8@sha256:5244e39194ce66c6fcb12403060a9660748ffd774bca1b1f7fd05e3b30a42c03
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-entrypoint-rhel8@sha256:875f1fd02714b054843d36d217ae7208017a7453d2e3652020bc700b9f88c8aa
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-workingdirinit-rhel8@sha256:d7a5d3565450f4fb4cad0ca5e248b0e49b730d981a3ec1ebf3aa07cfae939ec4
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-nop-rhel8@sha256:8aa7bcf277fde39ee0d9fc7a0c7072a4f2b3a315656b35b44d921ff51818247b
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-entrypoint-rhel8@sha256:875f1fd02714b054843d36d217ae7208017a7453d2e3652020bc700b9f88c8aa
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-sidecarlogresults-rhel8@sha256:ab24861f30133ad4b6c89bb5aed740ebd6d28e47e1de932f750abb7563a849a2
  # tektoncd-triggerspipelines
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/triggers-controller-rhel8@sha256:91d1e54480cdf6dc5545e1662f4dc7c204741991fd4013338afbc61da9e492dd
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/triggers-webhook-rhel8@sha256:4e77b4b9aceaa2886ca74d92e4b12c2d09b571cc11aca35c662dd9d9fc7d6e85
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/triggers-core-interceptors-rhel8@sha256:39fd240310104cfb2e116167e49558aa04062d7eed42509bddd2db81576113c7
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/triggers-eventlistenersink-rhel8@sha256:228cd136b9dbab62a8c38c7d7991fed5b9af31c3f79235cac77ec4bf04d342e2
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/chains-controller-rhel8@sha256:0672d0cad8e3890105b6cfad6134d0c07da2b1f3c1826901594ed55aaea7ed30
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/hub-db-migration-rhel8@sha256:045de7548fa86249418aca3246df4ae3fef7db47fe24858449fc33af856ad616
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/hub-api-rhel8@sha256:dcd8ffd487303f15facec1cb51af72a1a0cb0a3335aa2b4489a48d0de48502ed
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/hub-ui-rhel8@sha256:4feb02e07f5023af05e91424198a96842913556193a6ce3ecd980913dad5e443
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/results-watcher-rhel8@sha256:bd7b9e10555b1804e977067d253656b3e58f98a8977dc5220c68dfd010148812
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/results-api-rhel8@sha256:6e81c7d5c0347fd10a7f917b008d231e11743731dfbb7f1219c85b8c3bb04057
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/cli-tkn-rhel8@sha256:7bcd349e9961bff8a9269d03e531e082c9e9c7457a960fd07573723a40d2b6df
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/cli-tkn-rhel8@sha256:7bcd349e9961bff8a9269d03e531e082c9e9c7457a960fd07573723a40d2b6df
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/cli-tkn-rhel8@sha256:7bcd349e9961bff8a9269d03e531e082c9e9c7457a960fd07573723a40d2b6df
  - name: IMAGE_ADDONS_TKN_CLI_SERVE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/serve-tkn-cli-rhel8@sha256:e1455d965c4767027706e61ff3ea4d92da80a64b36a4ac4ec35e6e06da1050cf
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/manual-approval-gate-webhook-rhel8@sha256:e313b78fd58ea659897c5a964cf7becaf254b1f1097f8feb84e7375e94509295
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/manual-approval-gate-controller-rhel8@sha256:dabe7e1de212226e744dae0664f5229f38bd87c431b93ac2848bee58b713f177
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipelines-as-code-controller-rhel8@sha256:72334d648b68bbf624c7aec701a325aa6e84f970c67d84aab2511fed0fe1b6e9
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipelines-as-code-webhook-rhel8@sha256:a14eb828aa15615e33f3b8d1ae77a671f2c6b12d5902905be9a08a676e51f545
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipelines-as-code-watcher-rhel8@sha256:479cdb6042a1023a9d0ee29c33d710c3ea09fc17eb1b1f2a07a0d6a177d2395f
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipelines-as-code-cli-rhel8@sha256:d9e53878ad1251bf5545ed78cf3971a21f1e34bd6723c5e098ad19e11a8cbf93
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/operator-operator-rhel8@sha256:b1d787036d322bb6946629a937c31cb7b58d10321a351c4d6fa86374a99078dc
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/operator-operator-rhel8@sha256:b1d787036d322bb6946629a937c31cb7b58d10321a351c4d6fa86374a99078dc
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/operator-proxy-rhel8@sha256:6e42b09518b6aec2b0095d7ee80fb52254d14f1e47337e123fd97d8ac55dfdb2
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/operator-webhook-rhel8@sha256:f17c6a6ba76b0f9c14e317f4458d6ce9a64386c41c37a211d2c7864202b21712
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:c89b75be65192a6c571203e62596913d9486fe14575cff9ac81705a6ae064a4d
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:c89b75be65192a6c571203e62596913d9486fe14575cff9ac81705a6ae064a4d
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:c89b75be65192a6c571203e62596913d9486fe14575cff9ac81705a6ae064a4d
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:c89b75be65192a6c571203e62596913d9486fe14575cff9ac81705a6ae064a4d
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:c89b75be65192a6c571203e62596913d9486fe14575cff9ac81705a6ae064a4d
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:c89b75be65192a6c571203e62596913d9486fe14575cff9ac81705a6ae064a4d
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/console-plugin-rhel8@sha256:bd6edfd2d558f525458651ad1039241d882efdc21efae1a4e41ef0dac7a2cc99
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/operator-bundle-rhel8@sha256:c7a9de8b16d7525e15dbe77cb796d9a6c243f6a9e789c5a96a8e8489a852df0f
