versions:
  current: 1.19.3
  previous: 1.19.2
  previous_range: 1.18.0
  channel: pipelines-1.19
  openshift:
    latest: 4.19 # lastest GA'ed openshift
    min: 4.15 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-controller-rhel9@sha256:6b7bbdb999c4bbbea434e192e16177a48c78905ed4a104b1228d063d71e4884f
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-webhook-rhel9@sha256:9b91b03604af06c549fbc2b48dab81734db68ef8749e381f0748ece55709e4c2
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-resolvers-rhel9@sha256:680d4cd811d05212abd4e74ec5bee99331c74570776f766e67f074e3609dfbdd
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-events-rhel9@sha256:4c847ce61227b5c6ab8dafc77ba12a3fbe85a3025be0efd16fba2079dcea2c3b
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:7f156a3b6ac6f450372c80d055e908e84ad754a5eb88e7aedeb1f22ecb6e8506
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-workingdirinit-rhel9@sha256:8e8ce9e3588d833b43c8bba113d098d43db93b43d787ff525d8abffb06b92fac
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-nop-rhel9@sha256:1d4313f26ee99eda90dbf70fc7e744a1ea3cc98471e5acd3cb612d40d7d924bc
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:7f156a3b6ac6f450372c80d055e908e84ad754a5eb88e7aedeb1f22ecb6e8506
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-sidecarlogresults-rhel9@sha256:c46e2dcc763e0467b92e9fcca2d8b0e22170e59e031c40859a29dc83e4af5bdc
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-controller-rhel9@sha256:22095c436562ff92771d9349f57d007d82415dae519e3da1de7d51e3f1042a93
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-webhook-rhel9@sha256:25bcdb30f0fe34300c4f61f62513f4853f65fe11bafde58bcf19b7b3c3fb9af7
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-core-interceptors-rhel9@sha256:92b8c92eb0bec102215b97f1d60d76c7a57747aeec9594ce1e0e46f7c27391d6
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-eventlistenersink-rhel9@sha256:8bcaeaa751c61eb927d6353984f81d6a92b4bd4f9a5be9dc620a11b06ff9e6ba
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/chains-controller-rhel9@sha256:90a5eb2c0decb72234cbea5354bb7737cebc53c467229b2c16a1425b4bf408dc
  # tektoncd-hubpipelines-
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-db-migration-rhel9@sha256:28258903330a0715141e4685b3760ff18b0d75da0694985bba7c3345d7808b5f
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-api-rhel9@sha256:ba596c629fe8b5b70db97923ff11392dc12115c8e7afefee0d48c12440b8dd86
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-ui-rhel9@sha256:10c620aa3a9c4bfbca185fb460e2521473a5fe6d518342b89a3dada5cf14e65a
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-watcher-rhel9@sha256:2d2499b7b12aace07c4b5ab4121caad445aab5bc8dd73377171683b36d417d73
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-api-rhel9@sha256:3f7e1d83eb1e21860cc2ae0bfe3abe8c9058e92a69698dba9d5871069016e90d
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-retention-policy-agent-rhel9@sha256:3b1c6f8acdf17a5185413147e0248baa559378ed79e08cb098c724036020576e
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:3980bc46b8f8dcf6c6e3f98c16528c90cbdd0697ade2f534e2fea1f31ef269ae
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:3980bc46b8f8dcf6c6e3f98c16528c90cbdd0697ade2f534e2fea1f31ef269ae
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:3980bc46b8f8dcf6c6e3f98c16528c90cbdd0697ade2f534e2fea1f31ef269ae
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:41d669fbe8bb48481890fb9fb52de9d4cac98cb74e6a6b284d046a8d21b06e58
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-webhook-rhel9@sha256:d4ebf4c88e277e6474c0562d60f49939573a10a33558988ab69776625af526f0
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-controller-rhel9@sha256:eb4316387a335d27297d8be550ef921a825e3e824783eae9a1a416dac0637790
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-controller-rhel9@sha256:6aaabb9af37e46a856371e29f141de6b0fac623128099bb927fc30f8f61e9db4
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-webhook-rhel9@sha256:37e2f1fb8a2b4c7ac3d5390ba68a9bf98a0c83a38567b6a9778764061b3d2bab
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-watcher-rhel9@sha256:faeb3d39eafc31b6a856bfbc47d8583b8dae6a811a59d0179531d64c859c0528
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-cli-rhel9@sha256:8f328c242ab6e394444c43329ceea527ccf6ea39aa6ca4ccd399560897ac5007
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:dd4c7c9db07b5dc80bc74a7726320ff3b00cc0f90cc1b141026609806b0c2e2e
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:dd4c7c9db07b5dc80bc74a7726320ff3b00cc0f90cc1b141026609806b0c2e2e
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-proxy-rhel9@sha256:8a26b681b72796746f731aaf4e8a310f356fc87018dbc12bcd7a08be92529b60
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-webhook-rhel9@sha256:9075cc8f9a16f3b8f8cdda9cbfbd709793049c95062f5abcb52f048ab749da2a
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:8872bda311fb4344f2de05bfcc646d860240357775bde25dc11c664059ded568
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:8872bda311fb4344f2de05bfcc646d860240357775bde25dc11c664059ded568
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:0bac6643aac6a49488860cb4b44f0f60b085564e06dd17698a90e03e85aaf100
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:0bac6643aac6a49488860cb4b44f0f60b085564e06dd17698a90e03e85aaf100
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:0bac6643aac6a49488860cb4b44f0f60b085564e06dd17698a90e03e85aaf100
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:0bac6643aac6a49488860cb4b44f0f60b085564e06dd17698a90e03e85aaf100
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:0bac6643aac6a49488860cb4b44f0f60b085564e06dd17698a90e03e85aaf100
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:0bac6643aac6a49488860cb4b44f0f60b085564e06dd17698a90e03e85aaf100
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/console-plugin-rhel9@sha256:d20e32bfb74e7af016ace851de3eb927497bfdbe691a88e119d963095715e4e2
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-bundle-rhel9@sha256:979b1941d23fcd5b748ef29ae4c7245ad0171b89c14f72d792ff684fdb7f1d19
  # opc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/opc-rhel9@sha256:11583e8717bb2b736c6c629498308047f6b2cf744543331abcca93079a2d601e
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pruner-controller-rhel9@sha256:30f52eddcae6613296b293dc7e9e57333ed46f714dcc6556a9901b26f60b8b66
