versions:
  current: 5.0.5-479
  previous: 5.0.5-478
  previous_range: 1.16.0
  channel: pipelines-5.0
  openshift:
    latest: 4.17 # lastest GA'ed openshift
    min: 4.16    # Minimum version OSP supports
images:
# tektoncd-pipeline
- name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/controller@sha256:289138ae64588c9f36d6eeb2806afff9c4b6fd2d75f81bceb15e6e08890fbc8c
- name: IMAGE_PIPELINES_WEBHOOK
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/webhook@sha256:ecdefdb7bbd9aa95be3973028615108c5a629279b226a94e3c1e51992d8d26c6
- name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/resolvers@sha256:a93d2b8273529572000c645f2004d290e3d9a884e332379652a7c8c9aae16b36
- name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/events@sha256:a04c440073aaa86ea685a01f792ed02024ed685623912193cba659b21e8265b6
- name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/entrypoint@sha256:d879df0d83a34af8ee99f5053dc210f6bbfa67d5593d1b6cd7a20f35748cd00b
- name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/workingdirinit@sha256:6c5df9d051cf70ff229a877c12b7ae80f80551aa1c8c0b2685d9c0137ed2f51e
- name: IMAGE_PIPELINES_ARG__NOP_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/nop@sha256:85be85b25b2f79062cd47ebc5df086bfd79607a2dfd4ab27923cc07a4011808a
- name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/entrypoint@sha256:d879df0d83a34af8ee99f5053dc210f6bbfa67d5593d1b6cd7a20f35748cd00b
# tektoncd-triggers
- name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-main/controller@sha256:161957830cdfd52cc4c884f849ee0a82fc7a56cdb944f5d73dec8ba2de20ef12
- name: IMAGE_TRIGGERS_WEBHOOK
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-main/webhook@sha256:95692f7022abebb252ef66f5dcecefdeef906be79043f13dcf5de98f1e5a36df
- name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-main/core-interceptors@sha256:1f0cac655c6094749c778b4fcee6474316cf82e9be8134333b9caa7d52084d09
- name: IMAGE_TRIGGERS_ARG__EL_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-main/eventlistenersink@sha256:b29abec68ab8bd5783f0fb822bb3aaa14678d24b62617fb0acb4237796848450
# tektoncd-chains
- name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-chains-main/controller@sha256:21d5f359f2a731cae946a2b415cb6757e748656630e8876af25ced4b305dd60a
# tektoncd-hub
- name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-hub-main/db-migration@sha256:424e738509470368c17114f6f696e5a07d4975ed63d2bd5996e07ca5880e342f
- name: IMAGE_HUB_TEKTON_HUB_API
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-hub-main/hub-api@sha256:ea3734c22817317e8728039192b54316705ed07cbaaeb5d19bcfdb4539ebf1ee
- name: IMAGE_HUB_TEKTON_HUB_UI
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-hub-main/hub-ui@sha256:6242b6bd9fe9eee22840a89a7a87e1c747a645d0f86d7f51639929b8971e5a83
# tektoncd-results
- name: IMAGE_RESULTS_WATCHER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-results-main/watcher@sha256:85d472af9437cc1553f1521ef550246cfef368132b61ef0fd01fbe96b4e6f577
- name: IMAGE_RESULTS_API
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-results-main/api@sha256:85d472af9437cc1553f1521ef550246cfef368132b61ef0fd01fbe96b4e6f577
- name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-results-main/retention-policy-agent@sha256:85d472af9437cc1553f1521ef550246cfef368132b61ef0fd01fbe96b4e6f577
- name: IMAGE_RESULTS_POSTGRES
  value: registry.redhat.io/rhel8/postgresql-13@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
# tektoncd-cli
- name: IMAGE_JOB_PRUNER_TKN
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-main/tkn@sha256:70fe5cade897755da6e5571181aadb3fe868708ac50ed4f8e9129891398f83ee
- name: IMAGE_ADDONS_PARAM_TKN_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-main/tkn@sha256:70fe5cade897755da6e5571181aadb3fe868708ac50ed4f8e9129891398f83ee
- name: IMAGE_ADDONS_TKN
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-main/tkn@sha256:70fe5cade897755da6e5571181aadb3fe868708ac50ed4f8e9129891398f83ee
- name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
  # value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-main/serve-tkn@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
  value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel8@sha256:cc5234d6a6afc213d24786253c8ea70bb77f3f5c3e1ea1526debb8a1776e4ffc
# manual-approval-gate
- name: IMAGE_MAG_MANUAL_APPROVAL
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/manual-approval-gate-main/webhook@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
- name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/manual-approval-gate-main/controller@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
# pipelines-as-code
- name: IMAGE_PAC_PAC_CONTROLLER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-as-code-main/controller@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
- name: IMAGE_PAC_PAC_WEBHOOK
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-as-code-main/webhook@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
- name: IMAGE_PAC_PAC_WATCHER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-as-code-main/watcher@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
# operator
- name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/operator@sha256:e75fea512f4eb11b539a2e52d7646b0de08c2ca8dbd22601e3c6659490265a4a
- name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/operator@sha256:e75fea512f4eb11b539a2e52d7646b0de08c2ca8dbd22601e3c6659490265a4a
- name: IMAGE_PIPELINES_PROXY
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/proxy@sha256:2e7f57069371c40bd8e769adc36f88dd4da60f0fb4b1f049b63f36a6904f43f0
- name: TEKTON_OPERATOR_WEBHOOK
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/webhook@sha256:ad6c1d751f4f571510dd3b488dfb98e1d809fd5a641b7d9a62243843fe98ec0e
# Addons
- name: IMAGE_PIPELINES_ARG__GIT_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
- name: IMAGE_ADDONS_PARAM_GITINITIMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
- name: IMAGE_ADDONS_GIT_RUN
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
- name: IMAGE_ADDONS_REPORT
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
- name: IMAGE_ADDONS_GIT_CLONE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
- name: IMAGE_ADDONS_KN
  value: registry.redhat.io/openshift-serverless-1/client-kn-rhel8@sha256:a5a7b2be50f211d4d9d555b2a2e2302096c139ff5011d984cc386f1530007f16
- name: IMAGE_ADDONS_SKOPEO_RESULTS
  value: registry.redhat.io/rhel8/skopeo@sha256:1dcb4189c92da21ee58b3ca5433615e0208194c8412f7f1fb45fa491179aaf9b
- name: IMAGE_ADDONS_BUILD
  value: registry.redhat.io/rhel8/buildah@sha256:5c7cd7c9a3d49e8905fc98693f6da605aeafae36bde5622dc78e12f31db3cd59
- name: IMAGE_ADDONS_S2I_BUILD
  value: registry.redhat.io/rhel8/buildah@sha256:5c7cd7c9a3d49e8905fc98693f6da605aeafae36bde5622dc78e12f31db3cd59
- name: IMAGE_ADDONS_S2I_GENERATE
  value: registry.redhat.io/source-to-image/source-to-image-rhel8@sha256:6a6025914296a62fdf2092c3a40011bd9b966a6806b094d51eec5e1bd5026ef4
- name: IMAGE_ADDONS_LOAD_SCRIPTS
  value: registry.redhat.io/ubi8/ubi-minimal@sha256:a47c89f02b39a98290f88204ed3d162845db0a0c464b319c2596cfd1e94b444e
- name: IMAGE_ADDONS_MAVEN_GENERATE
  value: registry.redhat.io/ubi8/ubi-minimal@sha256:a47c89f02b39a98290f88204ed3d162845db0a0c464b319c2596cfd1e94b444e
- name: IMAGE_ADDONS_PREPARE
  value: registry.redhat.io/ubi8/ubi-minimal@sha256:a47c89f02b39a98290f88204ed3d162845db0a0c464b319c2596cfd1e94b444e
- name: IMAGE_ADDONS_MAVEN_GOALS
  value: registry.redhat.io/ubi8/openjdk-17@sha256:632e78989471859ca4ed1148b951a911f7e3b6e6516482be20967c4171612c55
