versions:
  current: 1.20.3
  previous: 1.20.2
  previous_range: 1.19.0
  channel: pipelines-1.20
  openshift:
    latest: 4.21 # lastest GA'ed openshift
    min: 4.14 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-controller-rhel9@sha256:e5c0e813353b4c777b873a4d4b80c91778b34ca73b23372cc03228d9869e1344
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-webhook-rhel9@sha256:ff3a2a9565e82e3a0aca8c57bd44d7934fd4c9d2b79760a67e2720589b499136
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-resolvers-rhel9@sha256:2abb8fd5ac7c7a3073a87ce0e6ffee0a5b7324f4f4f82a46c03ad51e79944d1c
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-events-rhel9@sha256:acca17fa770e287b10080e608b4c402e6062b0a94442e6565888ce84ade9045d
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-entrypoint-rhel9@sha256:c6e8f2ac9f7e84503d67d122ee259c7c381e5f55e41093536f9571d78d9f3510
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-workingdirinit-rhel9@sha256:17a7792dcb66136548020ed2fd031b7952ab99712c1daacdd9ca2fc5146e7514
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-nop-rhel9@sha256:3d6a0182a116761bb0949fdd40cb1695c5add12d5c3b1ed979543507bfacb43a
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-entrypoint-rhel9@sha256:c6e8f2ac9f7e84503d67d122ee259c7c381e5f55e41093536f9571d78d9f3510
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-sidecarlogresults-rhel9@sha256:8d13e026b2a555add2b7a2aa50fd22f12a42778d0f9a04ca4948a4b3e53a61a2
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/triggers-controller-rhel9@sha256:10d71084cc08106d18f340900188b7ac26a1ed7d37ede2816b2e5b719d4c0ab7
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/triggers-webhook-rhel9@sha256:ff5377474b2a5defebefd72d6db0f8b1882ed2450fdce48783d46b36423a5eac
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/triggers-core-interceptors-rhel9@sha256:f2379c2fad36f51e6b6d30b68ebe8696a70319e28fb32c9e91df62ccc758b421
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/triggers-eventlistenersink-rhel9@sha256:5847b75a18f86f0bf66125b586a02f9cf50d91f5def8ae7ddd449c9ec204a97a
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/chains-controller-rhel9@sha256:190da7865ccef30e93ace68f06b7287466e05709bdfa1c771710c93333e5ab4e
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/hub-db-migration-rhel9@sha256:722ccea0642efe6fb7816caaab963bf71dc4d2acb6f2204a293311d67e911c82
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/hub-api-rhel9@sha256:4ff12438daf22c8f6be14abda5d91c45b03a6824e0592775f49072218b3703fb
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/hub-ui-rhel9@sha256:af7ea92da04a4287ad6b3eef6d22f00a00579d94f0854965a4527a3e552b1186
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/results-watcher-rhel9@sha256:8fff6735a42c87ed9dafe99c8f98f745d1dff6d149869bb9bfc82a68651282ae
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/results-api-rhel9@sha256:fb22d9aaf6fbbdddbb1ea8a8227d209e5377af6eb6edf711986b3cd27914da07
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/results-retention-policy-agent-rhel9@sha256:0fd578686fbc8a7a62f8edee6fb2559620c423b3937afbdb1a1d6865006946d4
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cli-tkn-rhel9@sha256:fb102c952027a9fb5eed0ba8f0336fea51f0e37e5349a44d9bd5385ebe4fd32b
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cli-tkn-rhel9@sha256:fb102c952027a9fb5eed0ba8f0336fea51f0e37e5349a44d9bd5385ebe4fd32b
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cli-tkn-rhel9@sha256:fb102c952027a9fb5eed0ba8f0336fea51f0e37e5349a44d9bd5385ebe4fd32b
  - name: IMAGE_ADDONS_TKN_CLI_SERVE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/serve-tkn-cli-rhel9@sha256:3124a91105fd123c6ea5fb6dc2fc9c31327ea72d7225918ea895e5b714a04021
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/manual-approval-gate-webhook-rhel9@sha256:e661d7d22f183d09b405303e94caf7ec440c203f0d374a469f6456cc31230772
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/manual-approval-gate-controller-rhel9@sha256:ad5e622fd95e047212568180070e7a56bb730125a2fdae154aa2a3fd10587afc
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipelines-as-code-controller-rhel9@sha256:74b12ea5b1a5a7767f5a02d69d592d7c934efba7005ac25e09e8dacef2daf22c
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipelines-as-code-webhook-rhel9@sha256:67638aef16644dc1daa81a926f3f77d03424b5417f3963e3fa49888027abaf5a
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipelines-as-code-watcher-rhel9@sha256:1157ada600e2b567836fd2d62c88aa02cc7e5cb8e5504538a270e9c363d3a37f
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipelines-as-code-cli-rhel9@sha256:5fdf180ff6a528cd42628f6954a4db8895f9a0108d0ec4d3ec6fc3b2b540217d
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-operator-rhel9@sha256:d067139fd59f1aae672522800a0e7d533800adc91626a54155a069eb6e2399b2
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-operator-rhel9@sha256:d067139fd59f1aae672522800a0e7d533800adc91626a54155a069eb6e2399b2
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-proxy-rhel9@sha256:a70b2a8cc6b69d73204f3ac084eb08fdd40be22984edea447d6c6771250da83d
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-webhook-rhel9@sha256:0b602fc473d8cab00d69d018613cf19e732c533c987331c38917042f65309276
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cache-rhel9@sha256:5c9c9379acf3a1acf9c1b81524f82d8a230817fc50a968cb09d7fe8298bf8fe8
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cache-rhel9@sha256:5c9c9379acf3a1acf9c1b81524f82d8a230817fc50a968cb09d7fe8298bf8fe8
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:9e029261593573d5218209abcdb4acd237f5f503288b657c006f15dc32d30b68
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:9e029261593573d5218209abcdb4acd237f5f503288b657c006f15dc32d30b68
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:9e029261593573d5218209abcdb4acd237f5f503288b657c006f15dc32d30b68
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:9e029261593573d5218209abcdb4acd237f5f503288b657c006f15dc32d30b68
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:9e029261593573d5218209abcdb4acd237f5f503288b657c006f15dc32d30b68
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:9e029261593573d5218209abcdb4acd237f5f503288b657c006f15dc32d30b68
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/console-plugin-rhel9@sha256:66f2fcc54c1f79cc90ba053c232765c3e88527254b64b4357b3ab64a7b5c4fbf
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-bundle-rhel9@sha256:1ebb1900efb13af711fbf82feec8c5c6c0cc8a163bbb506d80dfdc448aea7f4d
  # opc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/opc-rhel9@sha256:3c4dfcfd0d9073ef1beaff9abf88dcd80370f0efd1825bd35d839bbc2d64fe77

  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pruner-controller-rhel9@sha256:85d5a2cfd3d1bf6e302b1dee186a98d90c37d89015c85df7d1f980ac2f87b447
