versions:
  current: 1.19.4
  previous: 1.19.3
  previous_range: 1.18.0
  channel: pipelines-1.19
  openshift:
    latest: 4.20 # lastest GA'ed openshift
    min: 4.14 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-controller-rhel9@sha256:ae34ed4ead57a26e1f65dcf433908ad75c5bcc243fcb2fdc3b4c211171c40480
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-webhook-rhel9@sha256:5856f089432130c1d06257914dbf1ab8b2b8767033621c5e376e186d31d485b8
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-resolvers-rhel9@sha256:a68bc519e86f1316bf2c536aab16ebfab329cb51b07cd02d3021bc8332c4c97c
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-events-rhel9@sha256:6a947bae0c64ffcf7c2f9d71b5f18d858e017ce6122b2499c555850fe7fe1fde
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:b65e645dd89784ad505f8d48d3f7e13a6c5644c2c3c26be6ff3521a99a0cd17b
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-workingdirinit-rhel9@sha256:1141200c99c69bbfbce4f7994b7d8b9eca36f5cc395acdf866233b3cc35be61b
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-nop-rhel9@sha256:408a3bf7a43068cbf2ef9af04faf3df161ac39e53446f47d9fcd083499a9e2a5
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:b65e645dd89784ad505f8d48d3f7e13a6c5644c2c3c26be6ff3521a99a0cd17b
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-sidecarlogresults-rhel9@sha256:908fdd97d42dbf5db4bdf893ca309dc239064a26a0f62e49ed1c71f44ec3dd13
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-controller-rhel9@sha256:e1b99c7a287125dc265c536e5aecbe9eb4e9981ff030d28b9b127fb546a45944
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-webhook-rhel9@sha256:49cb3cca3f9102384c96e93108d09969df22c3858b1933ecff9fbe1d41aed981
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-core-interceptors-rhel9@sha256:7eaab4455c1e416e4e0ba5f3e0e60c5a46aea23a939968e15eb6a953680a5f2c
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-eventlistenersink-rhel9@sha256:a585790aa11f5152c8a55ef36f74f731a34b2eecccd3250e5ef3cec8ec398409
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/chains-controller-rhel9@sha256:655a73b61984fbafe9194629705f51ff149d43a768a5a1c103045582eba8f2ec
  # tektoncd-hubpipelines-
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-db-migration-rhel9@sha256:5bfbde45a37d8b16cf0ab0be8f636c35a1d9041d6c8f7f611fc24a551eb890eb
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-api-rhel9@sha256:38a58fd012558192cd779ff8ac2ef3f02b8e82e2a1bcbbb9d53822c9d8890afd
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-ui-rhel9@sha256:1fef4759b410625fc797a8ecd166c20ad09312abfccc1cb941e946cfdccd2da4
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-watcher-rhel9@sha256:2d6640e6b91896ff455ab8e2246f166a3cdd9c53dfca00b3919f646f54a11f9f
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-api-rhel9@sha256:84450e886c5ce68f4f594982fab6140faebef5774339226b0be8d7e70b963fcf
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-retention-policy-agent-rhel9@sha256:40a099a9073bcc2f8da442d8225be03c8636e456c548c93e1a8366677e845830
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:d1887f9fcef589a761a922814b1e8693542c580b6990a3172528ac6e4999d314
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:d1887f9fcef589a761a922814b1e8693542c580b6990a3172528ac6e4999d314
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:d1887f9fcef589a761a922814b1e8693542c580b6990a3172528ac6e4999d314
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:41d669fbe8bb48481890fb9fb52de9d4cac98cb74e6a6b284d046a8d21b06e58
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-webhook-rhel9@sha256:ddbab8d6b9d1239451bf695276c8ddfe00e78cbb9ff4fc6562a9a5a2924b6082
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-controller-rhel9@sha256:66588ef48047d6589b7c810398ca16032125174d7cd9eaf1d6ddebbbf82147b4
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-controller-rhel9@sha256:a802bd8ea9104e77b6318bc3c05269c32c6435a696f62084da83f68b9426294a
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-webhook-rhel9@sha256:aab3b001f60510c73cf475b2c218a7aa921cbca99b855d28862c42e83d610ab0
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-watcher-rhel9@sha256:498238810108939ead8df1158c6ac892ad5f0bfad57fd2a893b5ce53853504d1
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-cli-rhel9@sha256:6a18f8d771900aa480560d1809c789d5243c4f6d9087185c610d9b8834d78625
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:ef97ea04bcea60e864467dd0efd5a6f1b61068321db4bb956eee7c796a8a7d8f
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:ef97ea04bcea60e864467dd0efd5a6f1b61068321db4bb956eee7c796a8a7d8f
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-proxy-rhel9@sha256:5300c73732b2789fa3e6bb102a81ed99be6686eab8b8d67c8ac0bed266295eb1
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-webhook-rhel9@sha256:13e18fc2dedd0979eef35c808fc4455b8753b111b2e18435c996a5fdc3462acc
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:3e2343b6121790f18b8d8868d8492af0b0541252f50e290f585f467c61660574
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:3e2343b6121790f18b8d8868d8492af0b0541252f50e290f585f467c61660574
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:e800c9642ae9c5e51da025c19943b3d159575162977c3fd86d32a8c53178a4e6
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:e800c9642ae9c5e51da025c19943b3d159575162977c3fd86d32a8c53178a4e6
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:e800c9642ae9c5e51da025c19943b3d159575162977c3fd86d32a8c53178a4e6
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:e800c9642ae9c5e51da025c19943b3d159575162977c3fd86d32a8c53178a4e6
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:e800c9642ae9c5e51da025c19943b3d159575162977c3fd86d32a8c53178a4e6
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:e800c9642ae9c5e51da025c19943b3d159575162977c3fd86d32a8c53178a4e6
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/console-plugin-rhel9@sha256:bb5bd9f505d0eb6ce6573b09898c2ad49f1d3602c36b380058b489d9383ba60d
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-bundle-rhel9@sha256:4964b9c53d734b9c8937d832fdabe7040a07b665d461e23303fe10bb63585ac4
  # opc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/opc-rhel9@sha256:13839cc4d1265689b9b97b2c15fb835b992c58d4ae2f2cf9dcc8034eceec7239
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pruner-controller-rhel9@sha256:cc5265e2e163446554453d4f5db1cc733758b450c7550db7b7caf9ede474aeca
