versions:
  current: 1.15.4
  previous: 1.15.3
  previous_range: 1.14.0
  channel: pipelines-1.15
  openshift:
    latest: 4.21 # lastest GA'ed openshift
    min: 4.14 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-controller-rhel8@sha256:c929433886455d419f268acdace2a801eb2a439b8119cfbcc1fb4d1a99aed1b2
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-webhook-rhel8@sha256:ee3ed6e1e7e618fb9cdc05b391627deea5fee2adc21a0f712a2e09111861b7fc
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-resolvers-rhel8@sha256:adb8f5ea1fbc88462cc61f187c752d09179868a4d533fffcca09de4efcc672ab
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-events-rhel8@sha256:3853a614447c224af856ab403877a997a5cc4e0e559b89c69ef6dfdf87ff1692
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-entrypoint-rhel8@sha256:ca29378365cdee6af6e8e149746f099ba607663e643c3a7c1281b95ec8cdb20c
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-workingdirinit-rhel8@sha256:eac0b54f9f70371757e3b80cd37a2d3da17898b96570fe4b961afccdccdcaeff
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-nop-rhel8@sha256:4dbeecad99d71f64eac8f09cf3f3b7ed7e60bacd3007624fc1cef79879358c75
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-entrypoint-rhel8@sha256:ca29378365cdee6af6e8e149746f099ba607663e643c3a7c1281b95ec8cdb20c
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-sidecarlogresults-rhel8@sha256:0ec70615debf7193cdb3634f24b1d0ded013dfdba610cc541bad5836c614a159
  # tektoncd-triggerspipelines
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/triggers-controller-rhel8@sha256:91d1e54480cdf6dc5545e1662f4dc7c204741991fd4013338afbc61da9e492dd
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/triggers-webhook-rhel8@sha256:4e77b4b9aceaa2886ca74d92e4b12c2d09b571cc11aca35c662dd9d9fc7d6e85
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/triggers-core-interceptors-rhel8@sha256:fa63c02dd9813c8751e6b9ca7673c655813f994ff9b5251034800aa024b60452
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/triggers-eventlistenersink-rhel8@sha256:d790104c93dd6b0d5aab7060d2149a672c196745f401e8ba398fe0393e0234e0
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/chains-controller-rhel8@sha256:ef157e1de9bcd21897e0074312d11833ea7f55426eb5fad043cbf323ade91050
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/hub-db-migration-rhel8@sha256:8ba9ea6ebc140dedf4b7378d8b7a36dfac737737f4d7bbb6ba1cf4988e90190b
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/hub-api-rhel8@sha256:dcd8ffd487303f15facec1cb51af72a1a0cb0a3335aa2b4489a48d0de48502ed
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/hub-ui-rhel8@sha256:95ef7a41303f0e8ac7bafbddd9f2968de75ab20cb43d5acdbe4116fa34bcf932
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/results-watcher-rhel8@sha256:bd7b9e10555b1804e977067d253656b3e58f98a8977dc5220c68dfd010148812
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/results-api-rhel8@sha256:6e81c7d5c0347fd10a7f917b008d231e11743731dfbb7f1219c85b8c3bb04057
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/cli-tkn-rhel8@sha256:470f93699fa49c076e1d8579b31d701dcd07ba1c2f3467431ab56a15843128f2
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/cli-tkn-rhel8@sha256:470f93699fa49c076e1d8579b31d701dcd07ba1c2f3467431ab56a15843128f2
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/cli-tkn-rhel8@sha256:470f93699fa49c076e1d8579b31d701dcd07ba1c2f3467431ab56a15843128f2
  - name: IMAGE_ADDONS_TKN_CLI_SERVE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/serve-tkn-cli-rhel8@sha256:06a6c9d2f12f9446342c407e0ee6caa397d0ed4f6eefdd4c9c58f08fc98f62a5
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/manual-approval-gate-webhook-rhel8@sha256:4fd5fdf40b0f4bc642a5d13aebbed7ad2abd91e0d15da5de0178f8af45b9379a
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/manual-approval-gate-controller-rhel8@sha256:3dbd423e3ff33e8b69707c2c2f26de74685cf9ebc0b2dfe3bba96d59b785a497
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipelines-as-code-controller-rhel8@sha256:b52633ecb7f3799617cfe27dcd8de0223022b9cd86ca5e2e5a1eaf5489cbea4e
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipelines-as-code-webhook-rhel8@sha256:c8c4711a2cf1f34b47a004e94686a4839d1bb8e9dea40beb1122aed59d7f1d8c
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipelines-as-code-watcher-rhel8@sha256:6fdf6c5acedfa337b2a84b361d40c80ddcc19ee5927ed22b08fdee2d6a356067
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipelines-as-code-cli-rhel8@sha256:5c529208b18cc45bdc9e1bd28c93e1880af234460a04e1a029c43abc8cc80ee3
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/operator-operator-rhel8@sha256:e2d4a2f85391c8d68ed0978d39a7341e091239e07acbb94c7e0605cfac7e05c8
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/operator-operator-rhel8@sha256:e2d4a2f85391c8d68ed0978d39a7341e091239e07acbb94c7e0605cfac7e05c8
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/operator-proxy-rhel8@sha256:ef0ebaa5eec80113ade29b955d1113070a3bb75b1337e060e2154c5e0dc909ac
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/operator-webhook-rhel8@sha256:85a575afce77fa6685e3865ad4400010b0987027b3c9d284f5511494716bf3ae
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:043080bff45cd129c0852b55a578c1a85e8911de80fadef22a21a034a1eccd56
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:043080bff45cd129c0852b55a578c1a85e8911de80fadef22a21a034a1eccd56
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:043080bff45cd129c0852b55a578c1a85e8911de80fadef22a21a034a1eccd56
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:043080bff45cd129c0852b55a578c1a85e8911de80fadef22a21a034a1eccd56
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:043080bff45cd129c0852b55a578c1a85e8911de80fadef22a21a034a1eccd56
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:043080bff45cd129c0852b55a578c1a85e8911de80fadef22a21a034a1eccd56
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/console-plugin-rhel8@sha256:abc6499c29b8afce917c1295bab115b98b0267fbac7ad369760fabd4f3397de2
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/operator-bundle-rhel8@sha256:421af98ed487a550098c2d0a36ceda1d535e86ee76042a058e684a45d4dc6e55
