versions:
  current: 1.19.3
  previous: 1.19.2
  previous_range: 1.18.0
  channel: pipelines-1.19
  openshift:
    latest: 4.20 # lastest GA'ed openshift
    min: 4.15 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-controller-rhel9@sha256:3f1ce5481fda83141dfa02189ef6e44e48d5de47f6523602cc895863f78486a7
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-webhook-rhel9@sha256:d0f2d77893d6628a1b347649882ab4f5c3fe9d7b725f526f1861b33ec4caba00
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-resolvers-rhel9@sha256:6cc2d48b94e204ab50e4155296d5e833e5bbf36c1ac11dc2f226673c4150c05b
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-events-rhel9@sha256:06e2b826024fcd72a37a647a0ca1968f2e144a099481222cf62927ab20da43b9
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:2efa14f22abd9d0b10ff8bcd748000a2ff5c9c8b1cf2345bfba417e46ffb6f94
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-workingdirinit-rhel9@sha256:43c9e7d2e77967814491d6ac9c4d290bfdc3f00f02315ce9488f1d0deaba582b
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-nop-rhel9@sha256:1f093231e414c06d87a34bc300ba871a96260c63bf26cfb431dc18bb986413f6
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:2efa14f22abd9d0b10ff8bcd748000a2ff5c9c8b1cf2345bfba417e46ffb6f94
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-sidecarlogresults-rhel9@sha256:b98c8720133256272000df2c6539bd1767e20f201ffa2ae9b4cc87c18e76e19b
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-controller-rhel9@sha256:7746441e258ad98c839390b16f7a52c2c313d0f2c9cf30de73a8bac01d3714c9
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-webhook-rhel9@sha256:010949bb7962dfb102d9926dc9065814bccbe843a4e79050d69be0b416ec8250
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-core-interceptors-rhel9@sha256:f62e3bdb34dda93f4c25ad11761195cb259b5808152a76cadb0a7c6f8fedae32
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-eventlistenersink-rhel9@sha256:77e505456c83b6ab964e1ce0df07fbd7adc9ee054861bce296c482f91cbebc01
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/chains-controller-rhel9@sha256:ad2c2f512179c9f8117e696a69d3894575baef89f5ad1627bbf9e16a64fbec33
  # tektoncd-hubpipelines-
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-db-migration-rhel9@sha256:cb77a4eb9bdc886645dea727f30d64dcc53ab6c0db1e4dc57e35eb769f5b2fa5
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-api-rhel9@sha256:6c6821b9d005fe087cf90924e7684199176f7142d9d969e2741f46e863357e0e
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-ui-rhel9@sha256:adbdfe30950c55e6a1d35d864f29722023a79a503ae055416fb96ada120c1e6d
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-watcher-rhel9@sha256:7901c981571d8eafe07b5841d74500280de6a2d23ab14b0c8ba9b5fdee029074
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-api-rhel9@sha256:6df634e3414b02e80fb8e8a3bd3b6881a1c6f7bdb60735f061e37cbd8abb4867
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-retention-policy-agent-rhel9@sha256:4404a20e40a4696091c6409c4b30ebab812b1291a317509cb3faea08fed2acdb
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:1b97b048e2d160b9c50aa9e090cf2591ca1f00ef0af075748cb4e97d0f15ad04
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:1b97b048e2d160b9c50aa9e090cf2591ca1f00ef0af075748cb4e97d0f15ad04
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:1b97b048e2d160b9c50aa9e090cf2591ca1f00ef0af075748cb4e97d0f15ad04
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:41d669fbe8bb48481890fb9fb52de9d4cac98cb74e6a6b284d046a8d21b06e58
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-webhook-rhel9@sha256:6f14689462786a5bb12d6aa3058c7fb46ea33505c1dab3d05efc4df2c538fc35
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-controller-rhel9@sha256:da3244f644a20bad9481bbe3d2d54e3de6e15a3d72887180401a543c00179bf0
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-controller-rhel9@sha256:0bb19ff65985f3d4a34decb925cb1b3d93c8be3979f831fd0b8f77dce282ab2c
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-webhook-rhel9@sha256:98e7903adc24b7193762bfdceed7a382cebd1da0d691f3768e5bd94d25b3419d
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-watcher-rhel9@sha256:7d680be0b6917d8efade1e6d24d2c04f7222900d87ce921a935e7bdbff28fe03
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-cli-rhel9@sha256:bf6d10d29ed914c307a8481ed23e9d7b6a2c1f4afaa3b9606f6cb7067fbaffac
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:3ce8ed273d3251a063b18ecddd33ee51ad3cd09ea57d911cc4337c89710f2bf5
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:3ce8ed273d3251a063b18ecddd33ee51ad3cd09ea57d911cc4337c89710f2bf5
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-proxy-rhel9@sha256:7d6e9c6a6d6703db0a7c43fe922a88ecd74c2ab22e525e00d6f8978e6e5af418
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-webhook-rhel9@sha256:872b549f45f630e2ec9e84fd68dbcbd2a0a91071b82404f20adba72da12ab8bd
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:bbf8ba5b22878c9c245a396bba5fd7d4fef89e2b3b46b9621935f9f6a4e04d8b
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:bbf8ba5b22878c9c245a396bba5fd7d4fef89e2b3b46b9621935f9f6a4e04d8b
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:30312d207b036668379bb062fae5a08325e8aaadf2b239e942a45f17c3e6483d
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:30312d207b036668379bb062fae5a08325e8aaadf2b239e942a45f17c3e6483d
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:30312d207b036668379bb062fae5a08325e8aaadf2b239e942a45f17c3e6483d
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:30312d207b036668379bb062fae5a08325e8aaadf2b239e942a45f17c3e6483d
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:30312d207b036668379bb062fae5a08325e8aaadf2b239e942a45f17c3e6483d
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:30312d207b036668379bb062fae5a08325e8aaadf2b239e942a45f17c3e6483d
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/console-plugin-rhel9@sha256:5e71623fba89d86edf757b9c0ed57f3f43804ce5e9b1574c7866d4880237f3ff
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: registry.redhat.io/openshift-pipelines/pipelines-operator-bundle@sha256:ba8eecb53cfe1326ef613558bcc49d7d991aab5a4a3089d8afd47e9d7dff43b8
  # opc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/opc-rhel9@sha256:13839cc4d1265689b9b97b2c15fb835b992c58d4ae2f2cf9dcc8034eceec7239
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pruner-controller-rhel9@sha256:bfd9883128f8334bc677786616c0ee3bf6a34675e7c483b6c5b9f7a238d23b45
