versions:
  current: 1.15.4
  previous: 1.15.3
  previous_range: 1.14.0
  channel: pipelines-1.15
  openshift:
    latest: 4.21 # lastest GA'ed openshift
    min: 4.14 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-controller-rhel8@sha256:082d6e713bb66f9aa5e7cea018474fd33dbf7942122353d2d9ddb276e9adb146
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-webhook-rhel8@sha256:403f8a7c9ab53b375e5b2145ed6b76d020c1e346c6ad89f2e0434beff49e97aa
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-resolvers-rhel8@sha256:2891ee8760dea9d68cb572c36afdcfc5012f6d6fa1fa5d0fe35d25d389e4694a
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-events-rhel8@sha256:879ee5a20f30dfc1e6038931e20a50bca343841a21adf2b453c8eb7bae87ca65
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-entrypoint-rhel8@sha256:56cfac698a18e5388f978b32af53f2d036918d2fe5639e4d991bebb23d9ea4d4
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-workingdirinit-rhel8@sha256:9df376ae2d349b697f5e3d5129fda537f4b89f5ee2f7447552eccc6109ac01f8
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-nop-rhel8@sha256:47590db97495f876a4dccae2e41e870d57ba27d5d09569a26ae3264d93154574
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-entrypoint-rhel8@sha256:56cfac698a18e5388f978b32af53f2d036918d2fe5639e4d991bebb23d9ea4d4
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-sidecarlogresults-rhel8@sha256:017b958a8839d1e6feb63c89c0fe1cc5f5f4cda4903f288d514899040019c2c8
  # tektoncd-triggerspipelines
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/triggers-controller-rhel8@sha256:914c06851268886e8c5aa86c623c7065bb887bebc79d616487de43ffc0b23488
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/triggers-webhook-rhel8@sha256:106b1f3d44fd6ab474c0011abb3264d0d792b0022a15aff5fdfbea5f76a1cbc5
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/triggers-core-interceptors-rhel8@sha256:b166b245ba89a17c0a8fba65474a1071594db75a8603dfa377f116a3d987e1ff
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/triggers-eventlistenersink-rhel8@sha256:96b324f0c1d1f2f78724fee45cf205201521e96734ec127f9d3885e00c38d74c
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/chains-controller-rhel8@sha256:4f0300ed9ed050092c8f27d4db968876ee20bf2c5c612e1293114d31a102632d
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/hub-db-migration-rhel8@sha256:0afe9bdc168c4c577820737e754fc2a712b5889487c1fb9b000fcb1bc7903cfe
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/hub-api-rhel8@sha256:dcd8ffd487303f15facec1cb51af72a1a0cb0a3335aa2b4489a48d0de48502ed
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/hub-ui-rhel8@sha256:21de62f6646534edfebea237d468ed8609454e92987cff0082b8290c74c38b2c
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/results-watcher-rhel8@sha256:69e35b4b716055fcf90c44487e981fef601c5e8499d6c765d3af68d467da040a
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/results-api-rhel8@sha256:ad35d4b282ae0a6b00ab997a04329428eba19fa2e98269e9f2319e7153d03a14
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/cli-tkn-rhel8@sha256:7349c9d72102815bf61394ea9c23c612e37daced8a15e910a43b2f95aec2a747
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/cli-tkn-rhel8@sha256:7349c9d72102815bf61394ea9c23c612e37daced8a15e910a43b2f95aec2a747
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/cli-tkn-rhel8@sha256:7349c9d72102815bf61394ea9c23c612e37daced8a15e910a43b2f95aec2a747
  - name: IMAGE_ADDONS_TKN_CLI_SERVE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/serve-tkn-cli-rhel8@sha256:1ba8e6d4de79959760ebaf35fee5df7db7224674da8b997a71a73115013d223f
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/manual-approval-gate-webhook-rhel8@sha256:e313b78fd58ea659897c5a964cf7becaf254b1f1097f8feb84e7375e94509295
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/manual-approval-gate-controller-rhel8@sha256:dabe7e1de212226e744dae0664f5229f38bd87c431b93ac2848bee58b713f177
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipelines-as-code-controller-rhel8@sha256:81ae9094ad9d198f7fdc2bc568a4063322067a05f3210cb535421ef5e05cbfd6
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipelines-as-code-webhook-rhel8@sha256:3c308c6aa58971b6ca5838fca15e150068744beeac0f32d0fff9de099d18c4cd
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipelines-as-code-watcher-rhel8@sha256:062acfccb6908fc17fdce06307e4cd4957e02a24b32925413dabd7bde4104c63
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipelines-as-code-cli-rhel8@sha256:4fe9af08579f18a9389fa3d142b384eb5c88a49b702d11720868595f3be52fa5
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/operator-operator-rhel8@sha256:6dae26c0946ef8597b3610b82013f26ff78ea74d308b75801bc392d351b4fcfb
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/operator-operator-rhel8@sha256:6dae26c0946ef8597b3610b82013f26ff78ea74d308b75801bc392d351b4fcfb
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/operator-proxy-rhel8@sha256:5f658bb12e430897e9f8569a32daba160b6ddd8d5f91af21010608332c7ae192
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/operator-webhook-rhel8@sha256:e46cb3268f5c74264d1fe1dada415f2f90ec600680c24a49dfa364c65aa680a0
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:b50aad5938b729d2f405683aedaeb9b5cdfb13f4a95dbd81c78130fa4677dfa9
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:b50aad5938b729d2f405683aedaeb9b5cdfb13f4a95dbd81c78130fa4677dfa9
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:b50aad5938b729d2f405683aedaeb9b5cdfb13f4a95dbd81c78130fa4677dfa9
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:b50aad5938b729d2f405683aedaeb9b5cdfb13f4a95dbd81c78130fa4677dfa9
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:b50aad5938b729d2f405683aedaeb9b5cdfb13f4a95dbd81c78130fa4677dfa9
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:b50aad5938b729d2f405683aedaeb9b5cdfb13f4a95dbd81c78130fa4677dfa9
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/console-plugin-rhel8@sha256:8270fa85989e0031e57eb47c58b58d6d94f61841eac6f6b8f43910d12a90110a
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/operator-bundle-rhel8@sha256:67b0f4f2afe3a0654de15a745f9fa6aa957c81d25e9953581a457b453a41ee8b
