versions:
  current: 1.19.4
  previous: 1.19.3
  previous_range: 1.18.0
  channel: pipelines-1.19
  openshift:
    latest: 4.20 # lastest GA'ed openshift
    min: 4.14 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-controller-rhel9@sha256:ae34ed4ead57a26e1f65dcf433908ad75c5bcc243fcb2fdc3b4c211171c40480
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-webhook-rhel9@sha256:67334d9a2a0bee4cfd62d3e3c26608df4f802adf8970981260e4051b4fb3d055
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-resolvers-rhel9@sha256:a68bc519e86f1316bf2c536aab16ebfab329cb51b07cd02d3021bc8332c4c97c
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-events-rhel9@sha256:6a947bae0c64ffcf7c2f9d71b5f18d858e017ce6122b2499c555850fe7fe1fde
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:e74f92e066f47a3eab9467f2253c3b85bc34fa41e2443e033b5e3470849b0d16
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-workingdirinit-rhel9@sha256:1141200c99c69bbfbce4f7994b7d8b9eca36f5cc395acdf866233b3cc35be61b
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-nop-rhel9@sha256:408a3bf7a43068cbf2ef9af04faf3df161ac39e53446f47d9fcd083499a9e2a5
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:e74f92e066f47a3eab9467f2253c3b85bc34fa41e2443e033b5e3470849b0d16
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-sidecarlogresults-rhel9@sha256:cb5958fdc6661e23f9957d53877a6f401af5a2f64a1305ae21579048846f1f70
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-controller-rhel9@sha256:e1b99c7a287125dc265c536e5aecbe9eb4e9981ff030d28b9b127fb546a45944
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-webhook-rhel9@sha256:49cb3cca3f9102384c96e93108d09969df22c3858b1933ecff9fbe1d41aed981
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-core-interceptors-rhel9@sha256:f6430ac69bc0017b80f81d3874ad4576a778ca4b84150316c73ac02d9e72a4a4
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-eventlistenersink-rhel9@sha256:34d7581b3310e0baa02b2677d9583e12ad894fcdb2c0e72b91bd87ef589addf7
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/chains-controller-rhel9@sha256:7d77d1259dd5cc68416c392171c0ee60b178bb82f6aa7a1a15ee2813aef3df92
  # tektoncd-hubpipelines-
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-db-migration-rhel9@sha256:285162b6b7527e7b32a41c63fb413faea538fce0b53d02cbd746d3e3b9089427
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-api-rhel9@sha256:fb15588eb5a99bd2079a0a97fac8ec5e4f91f70f911026df945b497cc2f300d1
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-ui-rhel9@sha256:a7f75412a5be3e9cf3b5be5274dd37ca0a96ed06baa0f1d786522877246eeac8
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-watcher-rhel9@sha256:2d6640e6b91896ff455ab8e2246f166a3cdd9c53dfca00b3919f646f54a11f9f
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-api-rhel9@sha256:84450e886c5ce68f4f594982fab6140faebef5774339226b0be8d7e70b963fcf
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-retention-policy-agent-rhel9@sha256:40a099a9073bcc2f8da442d8225be03c8636e456c548c93e1a8366677e845830
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:8fd5633ebc5ef869fe82b799524e6848f982bf64cc2621a0fe3151349f730fef
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:8fd5633ebc5ef869fe82b799524e6848f982bf64cc2621a0fe3151349f730fef
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:8fd5633ebc5ef869fe82b799524e6848f982bf64cc2621a0fe3151349f730fef
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:41d669fbe8bb48481890fb9fb52de9d4cac98cb74e6a6b284d046a8d21b06e58
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-webhook-rhel9@sha256:9e2d2dfabf5c203cc7a3eb9c172cd6080798ac39d7e208440a586a463a80c1e4
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-controller-rhel9@sha256:da2fad8895dfedbb90cc915bc42af999648d348b61746a5527a719df0e16a245
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-controller-rhel9@sha256:e59eb3d345c7ba66f3f4c876006d3ea1e16b6fd66ea7c73bd9570580fcf54a5f
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-webhook-rhel9@sha256:cc6f6e614cae08129239e9a7da9bd40a88eea5639edd000b706ea3e8b3ad5dd6
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-watcher-rhel9@sha256:1862f9a1d4b605305525de43e6d1da1675e413902e00dcd5620f74e8975357a2
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-cli-rhel9@sha256:398c20f91ff88a4e58e406059ba7a3d61b6bb6efc1a160c6b94a4f0158c40746
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:f151dda38d7fafe2d72e2cb064d074921c6b535543f29cfcf66405ba65e38ed5
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:f151dda38d7fafe2d72e2cb064d074921c6b535543f29cfcf66405ba65e38ed5
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-proxy-rhel9@sha256:d49f6cfcd815f93d0f1fad8a569bc8e52ffd86ba909530e95fdee19b0a1ca784
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-webhook-rhel9@sha256:4dd79bf0ff2403a9d0f305b5b178216264adb8d777d83ea9284f064a18f7269a
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:9d3839804b21f8e1426ee2eae4cba99245cbab3d5cf4a51383961c29d85da96d
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:9d3839804b21f8e1426ee2eae4cba99245cbab3d5cf4a51383961c29d85da96d
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:18bb4f4139d8b9f041ec5d38e5350d72290715f8ef235543365ca4b353bfa8c4
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:18bb4f4139d8b9f041ec5d38e5350d72290715f8ef235543365ca4b353bfa8c4
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:18bb4f4139d8b9f041ec5d38e5350d72290715f8ef235543365ca4b353bfa8c4
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:18bb4f4139d8b9f041ec5d38e5350d72290715f8ef235543365ca4b353bfa8c4
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:18bb4f4139d8b9f041ec5d38e5350d72290715f8ef235543365ca4b353bfa8c4
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:18bb4f4139d8b9f041ec5d38e5350d72290715f8ef235543365ca4b353bfa8c4
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/console-plugin-rhel9@sha256:af4f33a9bfd71aacc32eeeaefcf1529df2694f653f223f59840fd7a984ec9eda
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-bundle-rhel9@sha256:e33185d524a5c71961ab7361147f65e182a42993025abbdee5a77d48af4c3ae5
  # opc
  #- name: IMAGE_ADDONS_OPC
  #  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/opc-rhel9@sha256:5cbaf89e098f30883830c0864abb3b57d1e3336c08e5f8d457e3556e7cb6d92f
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pruner-controller-rhel9@sha256:cc5265e2e163446554453d4f5db1cc733758b450c7550db7b7caf9ede474aeca
