versions:
  current: 1.21.3
  previous: 1.21.2
  previous_range: 1.20.0
  channel: pipelines-1.21
  openshift:
    latest: 4.21 # lastest GA'ed openshift
    min: 4.14 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-controller-rhel9@sha256:f9a20f3aef3439ebf1e5ce6ea44f63f4067b02392ca6aab7f2df764acea29394
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-webhook-rhel9@sha256:9c9c3e105dc9811526a74eca5081a275cf533169d6aa89e4288be499608d474c
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-resolvers-rhel9@sha256:3cbedf3fb03935ce868c835b7b8a677357c0d9cb571ed4d7c03b3e7ecb50a9df
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-events-rhel9@sha256:ab4c985417c80be6ef092dd623ff490a4a87a70957bd4801614226e8f7b1b1be
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-entrypoint-rhel9@sha256:d1f9a6711543ebc6e8644cefcf287d910d9c9c4ea386ea9128c17edbe14d0c77
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-workingdirinit-rhel9@sha256:63013a3d0f42d40ee5e23287741a9e1fb89fccd60a14f62aef373a13ce774515
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-nop-rhel9@sha256:a65e6792c4d8d1c9bfe21d53a886a6c684d237af55c58cd378a037cf4a17e757
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-entrypoint-rhel9@sha256:d1f9a6711543ebc6e8644cefcf287d910d9c9c4ea386ea9128c17edbe14d0c77
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-sidecarlogresults-rhel9@sha256:5bb3015cb398055bd7e277aeade02ab17a2d5fe40f21b35f647b34526fdb4530
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-controller-rhel9@sha256:c0e55a4484cf270ff653ad18ddc1c476334c906b26a0dad350f1ce62bd37bbaa
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-webhook-rhel9@sha256:c00718108d5e6ee7a1fcd0cdc6f4ccb749b745716ab35a801500072fabed3b75
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-core-interceptors-rhel9@sha256:362b94661028b383132c5cfee4dc111bd6c6c3cd7ffd40a37108f7ffa3489962
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-eventlistenersink-rhel9@sha256:2dc41851923150d003792c5b4211192f397dee9de6eead7733f4b145d6d9d9d5
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-chains-controller-rhel9@sha256:96bc0b4dc72e561857c0a7c9f4ee54e33b6ffc504a797d3c89553e673f1748ac
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-hub-db-migration-rhel9@sha256:ccdedbee72cd1b16110b4b36aea4da01aea754ef60ec6f0cb20014905bb459ef
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-hub-api-rhel9@sha256:dbd601246fbfbf4ae096aa6e6b778c8a6c946784579bb7e987cc17d07adeec40
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-hub-ui-rhel9@sha256:d1ce22adb4da2c23af092f6a56fc99947d4f2573847e603dc5c05aa972736c75
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-results-watcher-rhel9@sha256:104c9e7d0fe8bdee782c6baa59acda5b09536f538d54e4db5a41559ab1ad97b7
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-results-api-rhel9@sha256:9d806f17c52dbb9fe414836752dcea7be9f5fea25f16cc364d45ce1eb468dc68
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-results-retention-policy-agent-rhel9@sha256:1ed010e2ef2925412f2d74d6d8ac0844a8c1d5b69d90520dda34d3b94572bd76
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cli-tkn-rhel9@sha256:decb75a001cf8c33bc923f470d224537fd4040829cd80c8274e64a674377d8d8
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cli-tkn-rhel9@sha256:decb75a001cf8c33bc923f470d224537fd4040829cd80c8274e64a674377d8d8
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cli-tkn-rhel9@sha256:decb75a001cf8c33bc923f470d224537fd4040829cd80c8274e64a674377d8d8
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-serve-tkn-cli-rhel9@sha256:9ba03831a00fab6daaf74fc5c3646dc51607b0bee1a88f0d52e45e8a36b5f253
  - name: IMAGE_ADDONS_TKN_CLI_SERVE_INIT_CONFIG
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-serve-tkn-cli-rhel9@sha256:9ba03831a00fab6daaf74fc5c3646dc51607b0bee1a88f0d52e45e8a36b5f253
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-manual-approval-gate-webhook-rhel9@sha256:d46e788ed052ec669b8e08fb013793927ddb0cdc06ab5fb8d6b1d7e4b46cf40e
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-manual-approval-gate-controller-rhel9@sha256:6f1cca24fc3249876b0342329866c8c53eb2cbe70f4216043bc41cc9834b12e8
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-controller-rhel9@sha256:8d5d675f1773b9ca134712a1aa9b5d0a4b96833b241d22ed93c58f5d56ac4954
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-webhook-rhel9@sha256:99dd539e87a36e69fc5c8debc64a71735eeb2211316ca52c422f97d10e3b5235
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-watcher-rhel9@sha256:1c0dfcb3bee53916c21966664abf6979599e1dd819ce1325bc622843921a66d5
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-cli-rhel9@sha256:c3ff596cd08556203d533e43e0baeeab1714d9224585d3e741909f2b1de3d1b6
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-rhel9-operator@sha256:49d83fcd3e55fb0b2293d3bfbb1e01ee1a3f427bb7a5e8a61e1d5041a92823f7
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-rhel9-operator@sha256:49d83fcd3e55fb0b2293d3bfbb1e01ee1a3f427bb7a5e8a61e1d5041a92823f7
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-operator-proxy-rhel9@sha256:85d45b35cbfd6bd7ef03ba0e64b0b99149a9666705ef778fd7ec47fdb82d9c0a
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-operator-webhook-rhel9@sha256:00ace6d7e839dfec80c53cd92c6532bd38633842182cd7fb32e80c2c213d4368
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cache-rhel9@sha256:f58a185d10fda84f3f7c02ce6bf040485ecbe860534bd53fb81b570bcef2a830
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cache-rhel9@sha256:f58a185d10fda84f3f7c02ce6bf040485ecbe860534bd53fb81b570bcef2a830
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:bfb78fa9f20533a790a645bc1c076c98f3efd2c4b9fab4802dfede4db89b1386
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:bfb78fa9f20533a790a645bc1c076c98f3efd2c4b9fab4802dfede4db89b1386
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:bfb78fa9f20533a790a645bc1c076c98f3efd2c4b9fab4802dfede4db89b1386
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:bfb78fa9f20533a790a645bc1c076c98f3efd2c4b9fab4802dfede4db89b1386
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:bfb78fa9f20533a790a645bc1c076c98f3efd2c4b9fab4802dfede4db89b1386
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:bfb78fa9f20533a790a645bc1c076c98f3efd2c4b9fab4802dfede4db89b1386
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-console-plugin-rhel9@sha256:a7aaf3bb071f7362b3107dbfaabadb06bc1b928fb19d5e0640c59151860176d1
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN_LEGACY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-console-plugin-pf5-rhel9@sha256:dbb2443f188c44a7e563f289e0415729b2d0b261aa7de02b471ab74d2acb54c5
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-opc-rhel9@sha256:6f893c4375428a358d31e0d6180af76969a41945eb7c8be0f84a87b4db036076
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pruner-controller-rhel9@sha256:c3616610fe4a7cca333a04d4886033755a4a5684489275a99fadaa16e6a10e2f
  - name: IMAGE_PRUNER_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pruner-webhook-rhel9@sha256:5a958a0bc11e02330d1cf615e9b1c73031918811e69dd76b400a31b3ff3d99b0
  # Scheduler
  - name: IMAGE_SCHEDULER_MANAGER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-scheduler-rhel9@sha256:4a787367ec32a7e60dfc9665e7ba4e8fecdda49da2a5d2f2b1d5cdfbe5a26250
  - name: IMAGE_SCHEDULER_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-scheduler-rhel9@sha256:4a787367ec32a7e60dfc9665e7ba4e8fecdda49da2a5d2f2b1d5cdfbe5a26250
  #multicluster proxy aae
  - name: IMAGE_MULTICLUSTERPROXYAAE_PROXY_SERVER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-multicluster-proxy-aae-proxy-server-rhel9@sha256:0d8fd07c948970b8081be3fab4b65a2eb853526efed9ee8b46e24c875eb1e0b6
