versions:
  current: 1.22.0
  previous: 1.21.0
  previous_range: 1.21.0
  channel: pipelines-1.22
  openshift:
    latest: 4.20 # lastest GA'ed openshift
    min: 4.16 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-controller-rhel9@sha256:baa97b21ba64511e05ecd18bf4ea3cff2042d99826f936c96e2d9337c8a1f4ab
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-webhook-rhel9@sha256:ae72c5bc1c5f8c956f6d10c46dda4c19d295e87b4a716078c2f50dfc2628986e
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-resolvers-rhel9@sha256:c21b1b71725732db1fff177fbf82cdf93f054b6ed561d91f6b2dc75c12129a8d
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-events-rhel9@sha256:d72592e74e7f6a7c15b469ccb60fd93e0f02adf23f7f492ab86e80bc547e0a10
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-entrypoint-rhel9@sha256:a85d0ffb5fb05efb89056ea062f0f018f0003a2360d224e825cf77bd3d05b7c8
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-workingdirinit-rhel9@sha256:555680a6d0413c9659d7a36658d845057fe7e95d7518628eba0415930c827afa
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-nop-rhel9@sha256:8962c47ba2d9a6d4cd8e6c9f66e4dd6167c0c335bef089eb10d69726a4243dc3
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-entrypoint-rhel9@sha256:a85d0ffb5fb05efb89056ea062f0f018f0003a2360d224e825cf77bd3d05b7c8
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-sidecarlogresults-rhel9@sha256:5de23f0f65da8b585b63fff2c8f236cb19e65b32055d6ea4c67f96beb435f5e4
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-controller-rhel9@sha256:01873f0bb1ee9eb4237e1cb6fa4054f5ad6e92a50aaae6b72b253d8e0b5be941
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-webhook-rhel9@sha256:6e7204475640d590208ae0d26b39fd9a4abad2f0008386a1f229695dc8be05df
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-core-interceptors-rhel9@sha256:41cd4980262e0e8c78f7ee41ab4047e667a5481ed980f8f01cfd84d23851a05a
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-eventlistenersink-rhel9@sha256:a0380cf9ca6d6e67f80caa8e69c65ec1d6784180794c233fe5c241103b8ec037
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-chains-controller-rhel9@sha256:58f89ac15f8c801a67c7649dc95c888720416e152e8a4ab3d16c6001004d2a3b
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-hub-db-migration-rhel9@sha256:84b0435aac4e93f42a81c64ae8d8fc8dc819b65deb80c1ddd64a405ee2c72273
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-hub-api-rhel9@sha256:c8443833598d8eb74859f07e92a6f3e4a20d574180d51d17527e1740c2c7a67c
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-hub-ui-rhel9@sha256:730184df80abf0f28d79a4f735cbacd0c7cc675aac9b2e3313eed427188649da
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-results-watcher-rhel9@sha256:4579a76d5475222960fc98e964e0d56e9133107ecfce45b6235275ad4f8f0cd9
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-results-api-rhel9@sha256:88b73c578908061cc0d6cd872945a2076e7067749f35942b6c0fafc91586765c
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-results-retention-policy-agent-rhel9@sha256:00984f30f91a4ccea0838260af78a6c61f04653ea65f87d6604a4c68629ff275
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cli-tkn-rhel9@sha256:2871101262adbe8c590340734a39578d95ac462983f8157383a13b51e10078ab
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cli-tkn-rhel9@sha256:2871101262adbe8c590340734a39578d95ac462983f8157383a13b51e10078ab
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cli-tkn-rhel9@sha256:2871101262adbe8c590340734a39578d95ac462983f8157383a13b51e10078ab
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-serve-tkn-cli-rhel9@sha256:83479f3be12ec9bf542600f6efe06fc7e3a36e351f7befef6d1d114396e468d5
  - name: IMAGE_ADDONS_TKN_CLI_SERVE_INIT_CONFIG
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-serve-tkn-cli-rhel9@sha256:83479f3be12ec9bf542600f6efe06fc7e3a36e351f7befef6d1d114396e468d5
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-manual-approval-gate-webhook-rhel9@sha256:ff472c514aa6f7c998b7bbf4c6a065e9b1c27d341714d42ae405cb3360482fb1
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-manual-approval-gate-controller-rhel9@sha256:9228d5164a5a32951733869153cf827308f53694f5c246df6294d8ba3ad1edd3
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-controller-rhel9@sha256:a0392825cdf2d02500ef85c2e91d0be9c7b593b7fb7358ed92d549bfddfea549
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-webhook-rhel9@sha256:33e8a66973b225b822b78480d1c6587a34edd877bbf4d19baba00060a19eeef1
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-watcher-rhel9@sha256:a45384b9487b820aa8816d93aa68e31bd3c58298f7cdc03f42fe1e57ebad148b
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-cli-rhel9@sha256:1530a779f043b62f46892f49467cb5a9a2b0dbbf90926e9b8f59aa09a463fea6
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-rhel9-operator@sha256:be18ec851ae55dcceedacfeb2314ecfe91dbe539fb18154b844826f8d46dedd5
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-rhel9-operator@sha256:be18ec851ae55dcceedacfeb2314ecfe91dbe539fb18154b844826f8d46dedd5
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-operator-proxy-rhel9@sha256:e0c41e50942f694436f5036762e2ac5afac7a12cb209a40d7c2bcaf9771bc796
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-operator-webhook-rhel9@sha256:962db05ca62d916d85bfc909c352f146646385bda4922f584694181be9b5b3c6
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cache-rhel9@sha256:52687d928cc24b3c8b4d414225db342f4ac4a8c88d2a379a66ca87131bf15b6b
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cache-rhel9@sha256:52687d928cc24b3c8b4d414225db342f4ac4a8c88d2a379a66ca87131bf15b6b
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-console-plugin-rhel9@sha256:bb058b3de08a97a38b1eb1c65df636dcb0632194c30c4d57569762097f9b6b86
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-operator-bundle@sha256:1daf75dd7bfc8c30098b3600d3592552f36d2e46077bf0be330dd3e61e751d75
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-opc-rhel9@sha256:0f4fb86deb1f34cf4a422835f2c5add41532c24858bc974211932f14c57f7346
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pruner-controller-rhel9@sha256:1bda4d788bf47e82f8d2df5c6cbfe5d294e15112d22b920625634832a8fdc810
  - name: IMAGE_PRUNER_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pruner-webhook-rhel9@sha256:e640d0e01736af6519d4341ce4b0440991e35044fd45d0a048d72af097d239e7
