versions:
  current: 1.20.1
  previous: 1.20.0
  previous_range: 1.19.0
  channel: pipelines-1.20
  openshift:
    latest: 4.20 # lastest GA'ed openshift
    min: 4.12 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-controller-rhel9@sha256:4d05c794b35907053d8ec927575097c6a138e9096415265fe2a5ec1a10fd43ff
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-webhook-rhel9@sha256:7bddad9ea3e77f285ece29ed67b405f4599cb54fa6a81e73c11cefa4cca3bd4d
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-resolvers-rhel9@sha256:4cd8f73f95612c82ab45dd193cae626a986f836ddefdf33ab37a9e2a991f7461
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-events-rhel9@sha256:3fc9679673cf7c9da183c303e1e4113419043e9346ea92cc964eccbbc601e934
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-entrypoint-rhel9@sha256:b55c638a96874619f524e4d227c117188d8395a0d3cc21e3ca63d60ba01af174
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-workingdirinit-rhel9@sha256:deab3b3997b0072a26a2e98309ef58f44bc684dc701da991d8d42d6c2ed4e5f2
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-nop-rhel9@sha256:8c414aac30ac5f636ab9636fbf60ea5bf07ae7ad8a4c90c021b3ae7ada1d4738
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-entrypoint-rhel9@sha256:b55c638a96874619f524e4d227c117188d8395a0d3cc21e3ca63d60ba01af174
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-sidecarlogresults-rhel9@sha256:e943501d76ed9fdcb2201fafcf441c182e68d454f3818500d1aae7a36ed193ed
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/triggers-controller-rhel9@sha256:68c7adfb88d67d2cfdf2454a3e2b04a5d3fe2faeace1b8b62553d92e0d7291d9
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/triggers-webhook-rhel9@sha256:42de551330f5db603fe5ec8e03b7cbb01dc269a1b5cc57edd2cde5766088bca7
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/triggers-core-interceptors-rhel9@sha256:8e5256a50ca28a273985821fd8962572cb8142f5f52f561d30d02ad3bcbfc528
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/triggers-eventlistenersink-rhel9@sha256:3d22f485e099431334b4be3c2155ce20e73145c009e9ee01d8e54200e8b7aded
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/chains-controller-rhel9@sha256:5958219a3c0a928a3ae57e533c52d3a440cf815b0878b5617269bb2913818411
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/hub-db-migration-rhel9@sha256:1bc2929e271f8658487b61d69f19fe4716df790b7a79a23472d46614c81ae908
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/hub-api-rhel9@sha256:8c9e1b7d21f325835a703172e5d501cc644bce316324cd18b8ca8127276f6aa8
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/hub-ui-rhel9@sha256:16c5cf2390ade2f806ade1ba548b40aa3ed06887faca380b093d1cfd66fb63c3
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/results-watcher-rhel9@sha256:407335e00835c811f584dd8c0672efce26297a6e7e58d734e9a99dc59c1ab5fe
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/results-api-rhel9@sha256:e715aea41c9c72f66bc114f2826db7460249d805bcd30785eb600f37b1026156
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/results-retention-policy-agent-rhel9@sha256:8baccb886c97925c8d0aec29fd085a9c295526c36f2b780e89ce0acb5ce6c6cc
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cli-tkn-rhel9@sha256:fe5ff08d2a56f91f6cc95a20e4d20595433503610efca79e8d0dcbb949eabb52
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cli-tkn-rhel9@sha256:fe5ff08d2a56f91f6cc95a20e4d20595433503610efca79e8d0dcbb949eabb52
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cli-tkn-rhel9@sha256:fe5ff08d2a56f91f6cc95a20e4d20595433503610efca79e8d0dcbb949eabb52
  - name: IMAGE_ADDONS_TKN_CLI_SERVE
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:115eea1a5ca87f3b6b72db1df05b7386bf73dc70c9c2e4dc5e1a66700d960c37
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/manual-approval-gate-webhook-rhel9@sha256:af1da75c86366c6ccda0061179859bf22188f39b5adf6427d7257d1556b4f109
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/manual-approval-gate-controller-rhel9@sha256:6c7f47eb3966d9c6cd6eb2c3d292439a67b6688c6edaf790bd2da91cf7bf6955
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipelines-as-code-controller-rhel9@sha256:af5065351313f2288bbad5f145e46c74b52bf11710dd9c6f70f28bd9db300279
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipelines-as-code-webhook-rhel9@sha256:35a26f367801cd7f09d7699c9a748348bb0df80554612418089ba20b86e294ff
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipelines-as-code-watcher-rhel9@sha256:38201b97f5ba7a074a473e9f9e926b2d5adbfcff6f48c2aac7ab9810cf924108
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipelines-as-code-cli-rhel9@sha256:6c0b9072c60c42deba41dc4022d16833588f1b7d0a07727f192b3edd701e07a2
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-operator-rhel9@sha256:3882d04a089e949cf5be650ad3c8d7cbc31b5964237372828fe0541871019f6e
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-operator-rhel9@sha256:3882d04a089e949cf5be650ad3c8d7cbc31b5964237372828fe0541871019f6e
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-proxy-rhel9@sha256:0a1c668abd8e40faa0fe04c3b402ff56ca266d19e28a3606e7ddf0809b0bf0ad
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-webhook-rhel9@sha256:1eeb48c9be678f7cdf043a62dd204053aeb30b23f51f4820569ec4f0e1adadaa
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cache-rhel9@sha256:5a2323d9743e72986c695bc1313208bb631e05aabf0b1d49103f7d9cbbb2c331
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cache-rhel9@sha256:5a2323d9743e72986c695bc1313208bb631e05aabf0b1d49103f7d9cbbb2c331
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:52444eaec63f4ff5fcf26d94d7b4d9bc32708b79bd8c20d5b7b569f1a01bcf8d
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:52444eaec63f4ff5fcf26d94d7b4d9bc32708b79bd8c20d5b7b569f1a01bcf8d
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:52444eaec63f4ff5fcf26d94d7b4d9bc32708b79bd8c20d5b7b569f1a01bcf8d
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:52444eaec63f4ff5fcf26d94d7b4d9bc32708b79bd8c20d5b7b569f1a01bcf8d
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:52444eaec63f4ff5fcf26d94d7b4d9bc32708b79bd8c20d5b7b569f1a01bcf8d
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:52444eaec63f4ff5fcf26d94d7b4d9bc32708b79bd8c20d5b7b569f1a01bcf8d
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/console-plugin-rhel9@sha256:f19098d1eb60049502d4a55f518743e1b5cc4cbe36f700428c46438459fc828d
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-bundle-rhel9@sha256:b7442b56f62c9b3b7d551fe602b1c3968d9f884363f39f141ecd7a9f87fa3086
  # opc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/opc-rhel9@sha256:5da3c4ddae0f124360042b227994ab407ef8d11bf0e42cec6394f3b08b814fd0
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pruner-controller-rhel9@sha256:48dcc269a4704e8f3ba345def7b81591db1c4af265916703d2387e71dda0aa3d
