versions:
  current: 1.19.3
  previous: 1.19.2
  previous_range: 1.18.0
  channel: pipelines-1.19
  openshift:
    latest: 4.20 # lastest GA'ed openshift
    min: 4.15 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-controller-rhel9@sha256:6b7bbdb999c4bbbea434e192e16177a48c78905ed4a104b1228d063d71e4884f
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-webhook-rhel9@sha256:9b91b03604af06c549fbc2b48dab81734db68ef8749e381f0748ece55709e4c2
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-resolvers-rhel9@sha256:680d4cd811d05212abd4e74ec5bee99331c74570776f766e67f074e3609dfbdd
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-events-rhel9@sha256:4c847ce61227b5c6ab8dafc77ba12a3fbe85a3025be0efd16fba2079dcea2c3b
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:7f156a3b6ac6f450372c80d055e908e84ad754a5eb88e7aedeb1f22ecb6e8506
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-workingdirinit-rhel9@sha256:8e8ce9e3588d833b43c8bba113d098d43db93b43d787ff525d8abffb06b92fac
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-nop-rhel9@sha256:1d4313f26ee99eda90dbf70fc7e744a1ea3cc98471e5acd3cb612d40d7d924bc
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:7f156a3b6ac6f450372c80d055e908e84ad754a5eb88e7aedeb1f22ecb6e8506
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-sidecarlogresults-rhel9@sha256:c46e2dcc763e0467b92e9fcca2d8b0e22170e59e031c40859a29dc83e4af5bdc
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-controller-rhel9@sha256:cb8a8f2760c2096aa6442f45520931a20211ac574deed7d181d8eed5c4f3194a
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-webhook-rhel9@sha256:7bfb29c211eb8000339e316d5701028cdc766d8ba8055b932a07b2c097ec9386
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-core-interceptors-rhel9@sha256:e40f0dbf65ca5488215431466521446ddbb1e99269f5c0aa31d68eacd2a5a34a
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-eventlistenersink-rhel9@sha256:7387edfe977ec901e34e8a6d2054076383c00641e885a18e32b1074a24ef22c1
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/chains-controller-rhel9@sha256:ed4cbaa8e7b59c5524c600413ebffbfce7ff6c4d300360396c5e68699579e0b8
  # tektoncd-hubpipelines-
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-db-migration-rhel9@sha256:cb77a4eb9bdc886645dea727f30d64dcc53ab6c0db1e4dc57e35eb769f5b2fa5
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-api-rhel9@sha256:6c6821b9d005fe087cf90924e7684199176f7142d9d969e2741f46e863357e0e
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-ui-rhel9@sha256:bb60d84bec05aebdf349ec1f51090b41f3a17b06a06b8ac6d6468f19904f8ff4
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-watcher-rhel9@sha256:8e1ec402d37d135b4e3c2f48636907c3c8c220b4e808d48f4979e3a9e76de9fa
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-api-rhel9@sha256:1a5f54e8630dbd8b27dcc34ae224b6bab5a1e7736943eff1d027b93442f0bf27
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-retention-policy-agent-rhel9@sha256:5a201e7d3c771acca6a6f0c4e1e9b71fc43cf7579fbea99afeaef1556296d969
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:1b97b048e2d160b9c50aa9e090cf2591ca1f00ef0af075748cb4e97d0f15ad04
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:1b97b048e2d160b9c50aa9e090cf2591ca1f00ef0af075748cb4e97d0f15ad04
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:1b97b048e2d160b9c50aa9e090cf2591ca1f00ef0af075748cb4e97d0f15ad04
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:41d669fbe8bb48481890fb9fb52de9d4cac98cb74e6a6b284d046a8d21b06e58
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-webhook-rhel9@sha256:d4ebf4c88e277e6474c0562d60f49939573a10a33558988ab69776625af526f0
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-controller-rhel9@sha256:eb4316387a335d27297d8be550ef921a825e3e824783eae9a1a416dac0637790
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-controller-rhel9@sha256:ef6e27ac5a7cbfbdd4534c6078284f7120db8b70321db3724813709441a47d48
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-webhook-rhel9@sha256:c63c6f82ed747f54ec0d5fe1f963ed64950418f7f313af47ed24165c1e55a9df
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-watcher-rhel9@sha256:7d680be0b6917d8efade1e6d24d2c04f7222900d87ce921a935e7bdbff28fe03
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-cli-rhel9@sha256:bf6d10d29ed914c307a8481ed23e9d7b6a2c1f4afaa3b9606f6cb7067fbaffac
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:aed3949c7fb6801459d6a7f2d0ab22d5367151442d7d01db2c7beca8b68c1e84
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:aed3949c7fb6801459d6a7f2d0ab22d5367151442d7d01db2c7beca8b68c1e84
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-proxy-rhel9@sha256:9a0731ee4c956e9a9614b99b12d111ed833f2e2b1a0269fe5fc53523dada96b2
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-webhook-rhel9@sha256:1210f0ba12606bf718a4cc72ca1a19003347734eac63889e769877fb2fb24c78
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:d6451e248f677284109ce18a6a07c19831497de7fb1fa871a343b6ef31e83893
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:d6451e248f677284109ce18a6a07c19831497de7fb1fa871a343b6ef31e83893
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:290a512db4af862af6d2431df7d43f51eca04f01450a6eb2c91976242e106bca
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:290a512db4af862af6d2431df7d43f51eca04f01450a6eb2c91976242e106bca
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:290a512db4af862af6d2431df7d43f51eca04f01450a6eb2c91976242e106bca
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:290a512db4af862af6d2431df7d43f51eca04f01450a6eb2c91976242e106bca
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:290a512db4af862af6d2431df7d43f51eca04f01450a6eb2c91976242e106bca
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:290a512db4af862af6d2431df7d43f51eca04f01450a6eb2c91976242e106bca
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/console-plugin-rhel9@sha256:d20e32bfb74e7af016ace851de3eb927497bfdbe691a88e119d963095715e4e2
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-bundle-rhel9@sha256:d80717535aa0133ed45d57b237c9fd808fa0342168cc9e7bb34bd4ea905d501b
  # opc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/opc-rhel9@sha256:13839cc4d1265689b9b97b2c15fb835b992c58d4ae2f2cf9dcc8034eceec7239
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pruner-controller-rhel9@sha256:30f52eddcae6613296b293dc7e9e57333ed46f714dcc6556a9901b26f60b8b66
