versions:
  current: 1.21.0
  previous: 1.20.1
  previous_range: 1.20.0
  channel: pipelines-1.21
  openshift:
    latest: 4.20 # lastest GA'ed openshift
    min: 4.14 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-controller-rhel9@sha256:f12e90615e74a57bda85781606796e33c53988995b5ba76b92ca10e8385f5608
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-webhook-rhel9@sha256:417145f697a155679dec08d1a417d56f74e74ebf23d25d0b550bfb870ecd6af2
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-resolvers-rhel9@sha256:6437fc208b365a2270c553636e7830ead41b3a585a26f771ae3333d51ce1590c
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-events-rhel9@sha256:8a7eae7285a4beb3b57416f350e9b4c7ce34ef97e93549bf84a3ec700b773c4c
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-entrypoint-rhel9@sha256:1b81de97d903f3db90df264e6ee390e5d32a655758547ad8a998bbff3a9fbac4
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-workingdirinit-rhel9@sha256:854be61024eb8b42bdc77a2bba8f54bf9b365811710e9848c2dd0bf6701d636e
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-nop-rhel9@sha256:58fb79ef1cfef8216d7585c8f0234d96b88b71a5d877575887d474defc007e41
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-entrypoint-rhel9@sha256:1b81de97d903f3db90df264e6ee390e5d32a655758547ad8a998bbff3a9fbac4
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-sidecarlogresults-rhel9@sha256:ef35210d4a1d516248521a1a92b10ca921b74120f9eed66dc984f9b71f723a6a
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/triggers-controller-rhel9@sha256:3686690bd6990aaabff551182d4011c52710b9f3b85ec2c90b0c384f5a52b1f4
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/triggers-webhook-rhel9@sha256:9da732aefd209a9bcf5a763358ef5ad4ad55a5d1f297217f9f33b85550f699f5
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/triggers-core-interceptors-rhel9@sha256:9b58809450ff0a0f095302c07604bc03996cb15a513bc5c9c376b1ee3aade06c
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/triggers-eventlistenersink-rhel9@sha256:6ddcd2bc594df131a83ed30bc42c7cc5999f36cb68bae1cb33f2b81671364a2f
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/chains-controller-rhel9@sha256:08123c8c80f006681df63b13319a018af29678d2deb0ff60ae502481f5c710cd
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/hub-db-migration-rhel9@sha256:1282a72b0708ab8839798044b585cdbf6f092ad3a523759a51cb18e209ed2df3
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/hub-api-rhel9@sha256:3e6ff34c17bd6385f03a16ba71370dffe0d83b5ab0e66923d1db4a8438382ef0
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/hub-ui-rhel9@sha256:8f56091b2ff69faca0966715dd6e46d85d2ce48385b33bfce8e5c650645c4549
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/results-watcher-rhel9@sha256:781b22ef1397973a67b25e3320c0a52764f40e428ebbf37654b44b1a955dcfb5
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/results-api-rhel9@sha256:54a7d13a0d6c1e285b7df40336c2b95ca916f3c759bb9f8055e017074ad8f967
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/results-retention-policy-agent-rhel9@sha256:d72db7158a6731c166237d7bd99fbde608f49904f181d8a3301ee9e67b8292ff
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cli-tkn-rhel9@sha256:cb2868fd0827b2d6dd3eff877a743c04573df10aaa70ee9fb538becc0032bf7d
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cli-tkn-rhel9@sha256:cb2868fd0827b2d6dd3eff877a743c04573df10aaa70ee9fb538becc0032bf7d
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cli-tkn-rhel9@sha256:cb2868fd0827b2d6dd3eff877a743c04573df10aaa70ee9fb538becc0032bf7d
  - name: IMAGE_ADDONS_TKN_CLI_SERVE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/serve-tkn-cli-rhel9@sha256:40592fa7c65cd2a6a2f40655b147e8d9563b23fef8389b0be525e66d3d717831
  - name: IMAGE_ADDONS_TKN_CLI_SERVE_INIT_CONFIG
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/serve-tkn-cli-rhel9@sha256:40592fa7c65cd2a6a2f40655b147e8d9563b23fef8389b0be525e66d3d717831
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/manual-approval-gate-webhook-rhel9@sha256:bb7f8815aa0e7fd0a197cf44ce9b754abf2af953a6baa916c96e35011fdb4182
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/manual-approval-gate-controller-rhel9@sha256:2431521236629eb9468c78af63c8cea3c5ae4d02d675312f0a6bad7e2e26d1d5
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipelines-as-code-controller-rhel9@sha256:32ab577b0d828f42adae3f4f4388f45c6885ae6d4391e10fbd15c1ced65906ba
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipelines-as-code-webhook-rhel9@sha256:41c490abcde0248bc6ca343ddc5d11a0000087a39a3019e12955737ab455fba7
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipelines-as-code-watcher-rhel9@sha256:771b9d95003a9d07acc18e3385927ab6892e1e4b0678f9c04d0ed65591963b1d
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipelines-as-code-cli-rhel9@sha256:cac0084a09a5d5fa3b1430e6b2beda485cf33e167fc7fa955a0ef457db299ab9
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-operator-rhel9@sha256:2924182ab21939de459c75351b10746c552bb49a63690a60f2b1edee390dffbc
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-operator-rhel9@sha256:2924182ab21939de459c75351b10746c552bb49a63690a60f2b1edee390dffbc
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-proxy-rhel9@sha256:79c4fca35bb7d04a7f515c7db23fb1521605dcbee507a175783f0bafd2ac41f0
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-webhook-rhel9@sha256:ddc8de6bc664c243d704ff2914646284db49185a1931a5355b0c08908f75c957
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cache-rhel9@sha256:ee97ac03ca8a83f2a822a98dce0a375af4d7d7f0d5233e2215557af0f25e65be
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cache-rhel9@sha256:ee97ac03ca8a83f2a822a98dce0a375af4d7d7f0d5233e2215557af0f25e65be
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:a2e044491e6e66ddcd50d1bf2c921ddf0e8f250c92dbeb9e6f6bfb9aa5a8b476
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:a2e044491e6e66ddcd50d1bf2c921ddf0e8f250c92dbeb9e6f6bfb9aa5a8b476
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:a2e044491e6e66ddcd50d1bf2c921ddf0e8f250c92dbeb9e6f6bfb9aa5a8b476
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:a2e044491e6e66ddcd50d1bf2c921ddf0e8f250c92dbeb9e6f6bfb9aa5a8b476
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:a2e044491e6e66ddcd50d1bf2c921ddf0e8f250c92dbeb9e6f6bfb9aa5a8b476
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:a2e044491e6e66ddcd50d1bf2c921ddf0e8f250c92dbeb9e6f6bfb9aa5a8b476
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/console-plugin-rhel9@sha256:d96e4409573ab23b4d0bdf1f16174e9d9637f26c26763640325c3e88715cc89b
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-bundle-rhel9@sha256:168ed6b755b7f0619a8b2e0fbb5b41bbadaa8110c4615edd5ff50f04daad486c
  # opc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/opc-rhel9@sha256:91a82639d5e5c7da45b7cc8f862d1a9781686547c6676bf5d6f3016bb81bf6dd
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pruner-controller-rhel9@sha256:3d5c4864d5a5dabee8dd62b68ba1e90ac9b3138d91727853c49f67ac49cdb2b6
  - name: IMAGE_PRUNER_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pruner-webhook-rhel9@sha256:03eb7adeaf60ffa0cd966e7bbef1d11f9c5ccabe140b1e7271437b56b74cb6e0
