versions:
  current: 1.17.2
  previous: 1.17.1
  previous_range: 1.17.0
  channel: pipelines-1.17
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.12 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-controller-rhel8@sha256:38d938f4aaeef70a7b92e51909bb3d8492d43b9ba6e4e01273bf4098f3e64811
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-webhook-rhel8@sha256:478356ba5df190cef6cac73fc77c27729e3a568551ae0c3a14a6e1178c962fd2
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-resolvers-rhel8@sha256:b3c5db03fc89a7c6e1966ac2086805ac35ba3135aa4417848b7d86e0a6df267e
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-events-rhel8@sha256:57cbdf64a0abbe774c2eebabc28ccb2f71f51ec211f2d6f7ed675f5f060e64ce
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-entrypoint-rhel8@sha256:cf0868583be3a1c80ec6ccc9cf7ba63e31238cd5afb57a3fe34c18d1a4c87bff
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-workingdirinit-rhel8@sha256:30aa605acf41519240920095b0382c4255abd7ec01c163a118be9dc31523631d
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-nop-rhel8@sha256:95dadbe727eb6c9670f5b235bfd6eea51f75efd2d8b1a10da86d7d4e3d46f67c
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-entrypoint-rhel8@sha256:cf0868583be3a1c80ec6ccc9cf7ba63e31238cd5afb57a3fe34c18d1a4c87bff
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipeline-sidecarlogresults-rhel8@sha256:eb759192098c52ed11cb107fdb35ba4dc1e32995138d4a44e57f1033792a058a
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/triggers-controller-rhel8@sha256:8c23277f151e90020cf3dc9739e03e70775156832f15e4811ee7f94dd3875860
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/triggers-webhook-rhel8@sha256:246fffe0d9512290766d2dca10e8f902afd97efa3690cbe8c244879110546cc2
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/triggers-core-interceptors-rhel8@sha256:be2618b44629c840e27390e31ae29cffeaa48daa1af9ceb288aaf65f9baf308d
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/triggers-eventlistenersink-rhel8@sha256:a24c63bfba5a8d09103ccddfab6398d39414635d12e3f8a7be96e3f953788b3e
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/chains-controller-rhel8@sha256:0f4a3750ae7bb4986852de7bf4b0808817f78e94f9fea79c81b29aad2d5f1b27
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/hub-db-migration-rhel8@sha256:8f9d4e51ea20705e2a2f1607c6313056a149074b183ca1eacde6056d9ca28d01
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/hub-api-rhel8@sha256:b1e4518704cdbe5dda3149636dc65ee5739e93cae09391be0664582673537b9c
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/hub-ui-rhel8@sha256:cdf80ed9b9a7daf2a35796001099cbfba396b28997d4be8aa62064aff970deec
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/results-watcher-rhel8@sha256:ec524e6bc01cfbb1e07269131788f6f57ee2be419db6b5cba318ba1747ecc90e
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/results-api-rhel8@sha256:3fba6c24e845cf6053276a9d0daf04571ecacb2f8a6d5c0bf3a66a1becdf4f9d
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/results-retention-policy-agent-rhel8@sha256:65a3d8b016905f03e23a111e091eb3998179ff9c7f0c932b1bde2d22e9f694a0
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/cli-tkn-rhel8@sha256:716afe958bd1f879940da679de1e144beda8ec7578d84534b500ce324197ff15
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/cli-tkn-rhel8@sha256:716afe958bd1f879940da679de1e144beda8ec7578d84534b500ce324197ff15
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/cli-tkn-rhel8@sha256:716afe958bd1f879940da679de1e144beda8ec7578d84534b500ce324197ff15
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel8@sha256:d055d2b35a663aef3e1aafdbed0b12957867c0670c946ebae66e9c44a768bda2
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/manual-approval-gate-webhook-rhel8@sha256:32416df654c142f9f5ace228c25eb6f0edc9f1aa49dd55caf65d1a4102e722b4
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/manual-approval-gate-controller-rhel8@sha256:decd4fb592accff66c1c607f41a03f8a4e05c5de7e2d8ab135f41793ae0722c9
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipelines-as-code-controller-rhel8@sha256:9568d8106c4ddf67889d6e4c064198f557a1674c0dd1fc79e54ace2a11a28237
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipelines-as-code-webhook-rhel8@sha256:d7150b8f90d643d91bd3efdb341e61f7350ebb6a806a816e4c79d6c2af5dc337
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipelines-as-code-watcher-rhel8@sha256:e479e665886188e0cefe8f03fb78db3e3cae34cc1ebf9f3a8733eb813fea9ba8
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/pipelines-as-code-cli-rhel8@sha256:ace545393350f9e86554e44c7957ea20a1a1633236d5d34a64d22fbe5ca3b6f6
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/operator-operator-rhel8@sha256:4f445671e6fabfeeb4de656b29534bf5c751104942935eb7cd597b9210e107e5
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/operator-operator-rhel8@sha256:4f445671e6fabfeeb4de656b29534bf5c751104942935eb7cd597b9210e107e5
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/operator-proxy-rhel8@sha256:9d00cd23e3ae63f3c065869e4a3b43c722de6e02d2e198a5f3b8d5128d9d0c64
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/operator-webhook-rhel8@sha256:4bc7f1bf6cffab52b3ab9a9e24852a2ebec9058fa2a1c4ca42dcc0ab04e2715e
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/cache-rhel8@sha256:579b65901de8b1400d2115410eaecf24bc38ae1048b22b9da43379f94966f81b
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/cache-rhel8@sha256:579b65901de8b1400d2115410eaecf24bc38ae1048b22b9da43379f94966f81b
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/git-init-rhel8@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/git-init-rhel8@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/git-init-rhel8@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/git-init-rhel8@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/git-init-rhel8@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/git-init-rhel8@sha256:a5212e90140427eb5c9328e8710be2121d207683ebb47cee95b8d76252e4839b
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/console-plugin-rhel8@sha256:67db2c7f5547253f6558ef8187114c695496af78ccfa3f3124f5b60ef98fa398
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-17/operator-bundle-rhel8@sha256:f2162408b5b02c6b1c819c1ec18f1e2c4e8a97e9271545ae4f8ad6dd18b42efa
