versions:
  current: 1.20.2
  previous: 1.20.1
  previous_range: 1.19.0
  channel: pipelines-1.20
  openshift:
    latest: 4.20 # lastest GA'ed openshift
    min: 4.12 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-controller-rhel9@sha256:4d05c794b35907053d8ec927575097c6a138e9096415265fe2a5ec1a10fd43ff
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-webhook-rhel9@sha256:7bddad9ea3e77f285ece29ed67b405f4599cb54fa6a81e73c11cefa4cca3bd4d
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-resolvers-rhel9@sha256:4cd8f73f95612c82ab45dd193cae626a986f836ddefdf33ab37a9e2a991f7461
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-events-rhel9@sha256:3fc9679673cf7c9da183c303e1e4113419043e9346ea92cc964eccbbc601e934
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-entrypoint-rhel9@sha256:b55c638a96874619f524e4d227c117188d8395a0d3cc21e3ca63d60ba01af174
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-workingdirinit-rhel9@sha256:deab3b3997b0072a26a2e98309ef58f44bc684dc701da991d8d42d6c2ed4e5f2
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-nop-rhel9@sha256:8c414aac30ac5f636ab9636fbf60ea5bf07ae7ad8a4c90c021b3ae7ada1d4738
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-entrypoint-rhel9@sha256:b55c638a96874619f524e4d227c117188d8395a0d3cc21e3ca63d60ba01af174
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-sidecarlogresults-rhel9@sha256:e943501d76ed9fdcb2201fafcf441c182e68d454f3818500d1aae7a36ed193ed
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/triggers-controller-rhel9@sha256:cfedfe21941f8f785339931ca12c89f08a7d54ca6e26477862861fccca49db58
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/triggers-webhook-rhel9@sha256:36386c59ca7e1b7cdf194ce45392b503edbfd604f103c2b2a74166d4739a707b
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/triggers-core-interceptors-rhel9@sha256:4247414a2838e10a4597cfd4d41a43f631d2399ada96c735eff5d7a308dad0ac
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/triggers-eventlistenersink-rhel9@sha256:dbf4da5e58f3cbeba5dce3a4a626a9019a2b5de37d55169023406e31c62581ce
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/chains-controller-rhel9@sha256:bfa04c1dbf645ee34b997bf00cec6bfc63cb1bccc342ef94f85e8d9364a8ac58
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/hub-db-migration-rhel9@sha256:524ec0a80fe01bc8e7503ba3a173ffe36d7bba5f2bd0cd70cba0f313657e0195
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/hub-api-rhel9@sha256:cb6664ff4c4d613b6cc0500418c2cebee3d1b65f9ed9f6dc423256b3d16bbe59
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/hub-ui-rhel9@sha256:768da476b528ea007836fe33cfe56d09ac470af2e6cf705c9f512f26c101c017
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/results-watcher-rhel9@sha256:15e01aa22bc0e014cf90374a49deb91b8152647341fc896a7fb87a1e9e861096
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/results-api-rhel9@sha256:29cfb42a1a4f73253b6d708040ad3d6e6ef2b0dba267b3596a05ffd95aa86d84
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/results-retention-policy-agent-rhel9@sha256:3cc071725df9ac0f8adde22b0b24ca170f7461a5e0f2a4c0988857c6f892e97e
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cli-tkn-rhel9@sha256:11aa1a4c159a6af4aaa42d90cfaad0d233a70bb53cb18b9c793d7b1dcf00d53d
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cli-tkn-rhel9@sha256:11aa1a4c159a6af4aaa42d90cfaad0d233a70bb53cb18b9c793d7b1dcf00d53d
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cli-tkn-rhel9@sha256:11aa1a4c159a6af4aaa42d90cfaad0d233a70bb53cb18b9c793d7b1dcf00d53d
  - name: IMAGE_ADDONS_TKN_CLI_SERVE
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:115eea1a5ca87f3b6b72db1df05b7386bf73dc70c9c2e4dc5e1a66700d960c37
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/manual-approval-gate-webhook-rhel9@sha256:032754c94bd57923dee350fec0fc7a47e757f5e41f508cf91eb75f9e4d3c6d6b
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/manual-approval-gate-controller-rhel9@sha256:399dbb9b769940bc603350bd681dd45237e8226e2bb52ef3540c9dfd73a64bd6
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipelines-as-code-controller-rhel9@sha256:c7870e1a5297ec0f26532f16f032b3a85cc6a763791315db2f9c47d248ad6a93
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipelines-as-code-webhook-rhel9@sha256:861f4c3f3521534ee147bbd5796277414944ded0bcd2733385ee043ef263578e
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipelines-as-code-watcher-rhel9@sha256:d941644bf6672ce0e6151f6ae7f775ba173795baf4a79eb8bba1d2b67ea359d5
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipelines-as-code-cli-rhel9@sha256:cc0ab5bf0b54686e936bc92d1d23151ef00e52f21e363bb02873c01638fce367
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-operator-rhel9@sha256:c27b41ab72d7878635bd5ae4933e2607bc82d34981ea077da302cbeb5150cbbc
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-operator-rhel9@sha256:c27b41ab72d7878635bd5ae4933e2607bc82d34981ea077da302cbeb5150cbbc
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-proxy-rhel9@sha256:62f49f54ea7df348332337fa33e073efb5b1a21a99210c38d8a0c641d51b3028
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-webhook-rhel9@sha256:cba1718306397fc60e1d6d468c92ea133188229f57a76f9b00eb8edd22cec5c3
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cache-rhel9@sha256:841d5d56f92cc8f4ee52badb0a191c17e0bae6d673cc3a57c8ddc9a79ce2a0dc
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cache-rhel9@sha256:841d5d56f92cc8f4ee52badb0a191c17e0bae6d673cc3a57c8ddc9a79ce2a0dc
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:52444eaec63f4ff5fcf26d94d7b4d9bc32708b79bd8c20d5b7b569f1a01bcf8d
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:52444eaec63f4ff5fcf26d94d7b4d9bc32708b79bd8c20d5b7b569f1a01bcf8d
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:52444eaec63f4ff5fcf26d94d7b4d9bc32708b79bd8c20d5b7b569f1a01bcf8d
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:52444eaec63f4ff5fcf26d94d7b4d9bc32708b79bd8c20d5b7b569f1a01bcf8d
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:52444eaec63f4ff5fcf26d94d7b4d9bc32708b79bd8c20d5b7b569f1a01bcf8d
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:52444eaec63f4ff5fcf26d94d7b4d9bc32708b79bd8c20d5b7b569f1a01bcf8d
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/console-plugin-rhel9@sha256:2f44e1d6488bdadcfc31613e6a742bfb96ad81a58e07410230d2d7d369475bf3
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-bundle-rhel9@sha256:04ec2e50e8b3e55d10ba0df490ede6e10412e554c38f9fae3989b45058558d17
  # opc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/opc-rhel9@sha256:f9c6bff2760b5d7a3f7f6c8e8355c2ca3e95292d532e2920dffb07f43ce5ecc7

  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pruner-controller-rhel9@sha256:6b707dd3bb4053d7c81a17305079b75717bdbd2015219b7e6b02e65a950ac653
