versions:
  current: 1.14.6
  previous: 1.14.5
  previous_range: 1.13.0
  channel: pipelines-1.14
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.12 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipeline-controller-rhel8@sha256:d01ba7ead670d5ab9c1355b90010657988e46b4d1aa0bb68b194eaf4001b2d7a
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipeline-webhook-rhel8@sha256:63fc1351191a54d12d4e463a1bb4cc732620cba3000af86ba7f7a579514f5fe4
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipeline-resolvers-rhel8@sha256:ddf0cb64ea57de872515e19de63b2dec5f56738c9d7eaa283a4a489545ef4902
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipeline-events-rhel8@sha256:7a63e7a762b9c7b15057ed9d5bcbea08acb4c8933a300c6ec336824d49a6e937
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipeline-entrypoint-rhel8@sha256:2261f4f657f70759f4d0c898e44ffafceb8dbe2144063d50227140463bdbf2c5
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipeline-workingdirinit-rhel8@sha256:ce0ea093c522af329acdc85148c2473ea45cd44270c15f8dd32965b0d56f304f
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipeline-nop-rhel8@sha256:57fb86ba112d79a228cbacc96cd0525c123464bcac956354722e3f2aeff42508
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipeline-entrypoint-rhel8@sha256:2261f4f657f70759f4d0c898e44ffafceb8dbe2144063d50227140463bdbf2c5
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipeline-sidecarlogresults-rhel8@sha256:6e7c7a1ca458e08ad85e1146815ec00a30016f709b45e28b464043e875c2a3e8
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/triggers-controller-rhel8@sha256:e23c901868229e4f6a4016aa7798f1aba879ff35ffe594f5b0e4d39f1bff9e52
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/triggers-webhook-rhel8@sha256:71d91c7b80b6d196025f68749bd8518b8b0affd8d5064a7c5c70d125656fbc36
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/triggers-core-interceptors-rhel8@sha256:5e7f5a2813a591e7b13fea9fc4e2f599b5ec855a015cd5a4c287c4e178358756
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/triggers-eventlistenersink-rhel8@sha256:9c29f6eff1f7019993446d85d226f04c5614a18351dfb4042a8bcb62276810de
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/chains-controller-rhel8@sha256:059c08316152c209de13017e322d6fe5eacfde81c3b0039e55b5de8f2f27183a
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/hub-db-migration-rhel8@sha256:abf4442b6acc714c2392b86af046d5f32d247ee0c3763bb18c57d0473edfcf02
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/hub-api-rhel8@sha256:83913744a1bb7ff23091cfa541b807cfb82b38dde0c37e0f1dd9c17cade99775
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/hub-ui-rhel8@sha256:ae0260abd2725c2f4bb25c0c07d86290978892a49050e0fd23f466401aba668c
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/results-watcher-rhel8@sha256:f68dc18a4dc6a1886507097551f4a6fce39062d03c6eb86c067d317812b0d34a
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/results-api-rhel8@sha256:82c8a91d521d7e6d81fb462fa2b804f420f52ee062df5cda39545165a2f19e0c
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/cli-tkn-rhel8@sha256:aa00832f286416eba71dc5b6c87b9a0358408ba398e8df253be60a2e5919be15
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/cli-tkn-rhel8@sha256:aa00832f286416eba71dc5b6c87b9a0358408ba398e8df253be60a2e5919be15
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/cli-tkn-rhel8@sha256:aa00832f286416eba71dc5b6c87b9a0358408ba398e8df253be60a2e5919be15
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel8@sha256:db3ff043410d1dd0621fef4483761727f7241d788b136e446fb861953350a2cb
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipelines-as-code-controller-rhel8@sha256:f9fed20cdfebbb226e035cc62f037174f5ecdb3139a5edc7e39f019f6d2b1e98
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipelines-as-code-webhook-rhel8@sha256:e2bd929246d62038a24a0685cb3e4873c131c9b7713d6a5268ca09a8614538be
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipelines-as-code-watcher-rhel8@sha256:8d4450d68ac03d8275e337d2c55692ef35e954400d0c9f041a943d163a8b7680
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/pipelines-as-code-cli-rhel8@sha256:b3bedee6084e9d9da549d3e637d2bf176aa365b5818e6b6377525577edd710dc
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/operator-operator-rhel8@sha256:6327385e3d3c9df1ea50e803955d980b4cd35fb15593fcfec0d477d91a45021f
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/operator-operator-rhel8@sha256:6327385e3d3c9df1ea50e803955d980b4cd35fb15593fcfec0d477d91a45021f
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/operator-proxy-rhel8@sha256:d9972bc64dfa7e260bd9b949bbb85ef5ae532e7c6df8d874d3d3963af1097726
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/operator-webhook-rhel8@sha256:bf0c38beefa24ca3d04ebfa6140a1cc5a9a56fba81ae05799279a559093b9033
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/git-init-rhel8@sha256:aa6eb4c7ade9d6add1e4ab94197c2ce72a253fea0d7461698ca0e37854f1dcbe
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/git-init-rhel8@sha256:aa6eb4c7ade9d6add1e4ab94197c2ce72a253fea0d7461698ca0e37854f1dcbe
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/git-init-rhel8@sha256:aa6eb4c7ade9d6add1e4ab94197c2ce72a253fea0d7461698ca0e37854f1dcbe
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/git-init-rhel8@sha256:aa6eb4c7ade9d6add1e4ab94197c2ce72a253fea0d7461698ca0e37854f1dcbe
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/git-init-rhel8@sha256:aa6eb4c7ade9d6add1e4ab94197c2ce72a253fea0d7461698ca0e37854f1dcbe
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/git-init-rhel8@sha256:aa6eb4c7ade9d6add1e4ab94197c2ce72a253fea0d7461698ca0e37854f1dcbe
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/console-plugin-rhel8@sha256:2e75096ffe20d1261e8a645fefd32e37295d727aa6a280f10041a44443917469
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-14/operator-bundle-rhel8@sha256:fb79a25668007d71ea4043bd5e3d5254dd7c35d614f743f105fdae19d134636c
