versions:
  current: 1.21.0
  previous: 1.20.1
  previous_range: 1.20.0
  channel: pipelines-1.21
  openshift:
    latest: 4.20 # lastest GA'ed openshift
    min: 4.14 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-controller-rhel9@sha256:e6fff3e787d46eef3021d8f56a3f90730c9188ccf3215c9eba86a257639f3118
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-webhook-rhel9@sha256:2d794021fe68fbf790db93659f0b2e9456dcaac36617d56903eb1d1c8648aaf3
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-resolvers-rhel9@sha256:a2f360ba00c6f30df898a5e7e46682f11d9927959328182d4c035a263b5ad4ce
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-events-rhel9@sha256:3fdfdbfe88b2435765ffcc9928547f898bf2241cf9df3c972997d4e5eefb1692
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-entrypoint-rhel9@sha256:168127911c3c16a7e6119d9c891bb456a40134a12b5ab9185eecc365a8bd16fe
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-workingdirinit-rhel9@sha256:39532b2516c5f8951e3e4f876a1279119d2372c366501490143a00c6516399fb
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-nop-rhel9@sha256:80430eb00c7d5360088488bb17b11987a2042296d6891b70578694a5e1d823d2
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-entrypoint-rhel9@sha256:39532b2516c5f8951e3e4f876a1279119d2372c366501490143a00c6516399fb
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-sidecarlogresults-rhel9@sha256:296018a3bf0f80941ea868477fbf0a789ded16a702ee658bb2825c58b23ff5c9
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/triggers-controller-rhel9@sha256:669459550b5c8b6d01aab85d39923d888a31a1ae0d7b91c23a2e8a80ef5d05e7
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/triggers-webhook-rhel9@sha256:bfc4293186d7edd165035178d40b9282e8342629228bffec6e544e342c06f824
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/triggers-core-interceptors-rhel9@sha256:4245a5d42ae40339a930918d293562c058207edafe0a596118de734b696e9fbd
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/triggers-eventlistenersink-rhel9@sha256:73d29426642a705877c7aecfe6d68fcbfb03327643b7650ea40f3a12a32b1071
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/chains-controller-rhel9@sha256:64a6656321c31636fd20ab6d0aea9fa873a522b738dfe20af2885c3268da34bc
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/hub-db-migration-rhel9@sha256:15947fed4e47a357ccc7300208952b30fa33cc09139d5d207ca13881010eebf4
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/hub-api-rhel9@sha256:f5b05030fa1d9f8b05b23becd78f8c2671a8014a08f15782125923079dcfb522
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/hub-ui-rhel9@sha256:39ed0b50d2b123508bcafa4de9766fde0fe05ab4fd3151c5b14070dadec67dd8
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/results-watcher-rhel9@sha256:76253fa174626fc17795eb58e9612c9490a1fb5dfd0955d3d39d9c30f6148b1e
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/results-api-rhel9@sha256:18f159ffa8d787a850b2f34400f70011431023abfa533a356cc14671fb7520ac
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/results-retention-policy-agent-rhel9@sha256:93d682498f83390c8c2f0dfc5cf8d93d43c80aa01e3946c2767e56829b53095a
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cli-tkn-rhel9@sha256:c9e50873e77e3c36bc99625fcd4f85b09f99e926b2028d37fa21679baf339e50
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cli-tkn-rhel9@sha256:c9e50873e77e3c36bc99625fcd4f85b09f99e926b2028d37fa21679baf339e50
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cli-tkn-rhel9@sha256:c9e50873e77e3c36bc99625fcd4f85b09f99e926b2028d37fa21679baf339e50
  - name: IMAGE_ADDONS_TKN_CLI_SERVE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/serve-tkn-cli-rhel9@sha256:40592fa7c65cd2a6a2f40655b147e8d9563b23fef8389b0be525e66d3d717831
  - name: IMAGE_ADDONS_TKN_CLI_SERVE_INIT_CONFIG
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/serve-tkn-cli-rhel9@sha256:40592fa7c65cd2a6a2f40655b147e8d9563b23fef8389b0be525e66d3d717831
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/manual-approval-gate-webhook-rhel9@sha256:85c91fb39b2b934b10d4831195f0d1d205f13fe761a4f27bb86fc2e78ba2882f
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/manual-approval-gate-controller-rhel9@sha256:e03fb4a21d5175547ce2d2db2d8b1e6fc4f2985e846a3e7fd06c387a458d6e9d
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipelines-as-code-controller-rhel9@sha256:776f012bb27aeb37e49ceefe8ce3d74673110a65ed5ed2de27fc50953ad0c91a
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipelines-as-code-webhook-rhel9@sha256:6cd04c322c321bcc002a5492819f6a091664c529bdcad06e943458e6cd3fbff4
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipelines-as-code-watcher-rhel9@sha256:65d96c216477985098b44a6317e9043fef707315c30892953a8836d82fb70bf1
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipelines-as-code-cli-rhel9@sha256:352727ba46ad2876fa4b778eb28b35605599a216231bebb28d6d2a81fc86722e
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-operator-rhel9@sha256:df2882e4675b6d864baabc4f20621050902b55d0e18beaa720e690c01b4289ce
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-operator-rhel9@sha256:df2882e4675b6d864baabc4f20621050902b55d0e18beaa720e690c01b4289ce
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-proxy-rhel9@sha256:5e5085bcfad8172c1b9fd955e65f02c86babb7895f513193a26b905962d8061b
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-webhook-rhel9@sha256:438a7ba8ccd1b8d7f54c911c9e34be2941bf8d22be82c52202fbb65e620a1a38
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cache-rhel9@sha256:64a6656321c31636fd20ab6d0aea9fa873a522b738dfe20af2885c3268da34bc
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cache-rhel9@sha256:64a6656321c31636fd20ab6d0aea9fa873a522b738dfe20af2885c3268da34bc
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:cb1e869c99579cb5e18aaa56ab9588d336d950d0e8050ce2228db7b19804005e
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:cb1e869c99579cb5e18aaa56ab9588d336d950d0e8050ce2228db7b19804005e
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:cb1e869c99579cb5e18aaa56ab9588d336d950d0e8050ce2228db7b19804005e
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:cb1e869c99579cb5e18aaa56ab9588d336d950d0e8050ce2228db7b19804005e
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:cb1e869c99579cb5e18aaa56ab9588d336d950d0e8050ce2228db7b19804005e
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:cb1e869c99579cb5e18aaa56ab9588d336d950d0e8050ce2228db7b19804005e
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/console-plugin-rhel9@sha256:3509f504da7e1868f07dfa29d8889693e96fbe674ea075d071b5d8887fae42b6
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-bundle-rhel9@sha256:197b3592459a456fa983519bf664e1d9f78a29495429283af1c2c9ab10732c9a
  # opc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/opc-rhel9@sha256:7fc1d230ae7b64a3e8bab76368b512673db572f8e2115d87d41dce31c1b113cf
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pruner-controller-rhel9@sha256:04fe54aa98a67d4185e9d9370888ddae17f70fc6f8d84b079de9c00400b7ebf2
  - name: IMAGE_PRUNER_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pruner-webhook-rhel9@sha256:26e117bd684ca61ac76b76ed857f1b13d96de30e4dea2ec7c35305e507db10d6
