versions:
  current: 1.15.4
  previous: 1.15.3
  previous_range: 1.14.0
  channel: pipelines-1.15
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.12 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-controller-rhel8@sha256:082d6e713bb66f9aa5e7cea018474fd33dbf7942122353d2d9ddb276e9adb146
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-webhook-rhel8@sha256:403f8a7c9ab53b375e5b2145ed6b76d020c1e346c6ad89f2e0434beff49e97aa
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-resolvers-rhel8@sha256:2891ee8760dea9d68cb572c36afdcfc5012f6d6fa1fa5d0fe35d25d389e4694a
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-events-rhel8@sha256:dfc3063e752735e42104ad1b4f0a676c3cc79401df3ed21108af44e83f91844b
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-entrypoint-rhel8@sha256:56cfac698a18e5388f978b32af53f2d036918d2fe5639e4d991bebb23d9ea4d4
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-workingdirinit-rhel8@sha256:9df376ae2d349b697f5e3d5129fda537f4b89f5ee2f7447552eccc6109ac01f8
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-nop-rhel8@sha256:f7a4378eb334575b23b2f20d9c370e9396448c2cfc4a0a8fac650c5613ec7257
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-entrypoint-rhel8@sha256:56cfac698a18e5388f978b32af53f2d036918d2fe5639e4d991bebb23d9ea4d4
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipeline-sidecarlogresults-rhel8@sha256:017b958a8839d1e6feb63c89c0fe1cc5f5f4cda4903f288d514899040019c2c8
  # tektoncd-triggerspipelines
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/triggers-controller-rhel8@sha256:7d8fb127e3dec7645aa8ff8f4b2d90ad0e9d3386e6f84c9135e5a286562521d6
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/triggers-webhook-rhel8@sha256:e6a5487638d280f8c5ba19164d309b8c5bbbc700ce0f26527b2b97cd3914b229
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/triggers-core-interceptors-rhel8@sha256:74c54b9b3bd75143dd20515c35a46e253838c404304841fdecfaf1fe15e674a0
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/triggers-eventlistenersink-rhel8@sha256:91af31c72b8ce6f317a71f52108cbd252d8505c7c0c95f215d2e64e4ca0c84fc
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/chains-controller-rhel8@sha256:3350b67ca6ca31c7bc837e02c708641cbd8b20d35da23fe2c4cfa2f1c9a0119e
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/hub-db-migration-rhel8@sha256:8e39a55f0c6d3c105f9dd406ca2845faead5f1a11eb56daac7bc226bfe724201
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/hub-api-rhel8@sha256:884ec676e01fb11a587300549113cdc5dc1f9521a8a3bcaec853d6c433779018
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/hub-ui-rhel8@sha256:8b8a70ca0f3078d85be57ec4c8027acdcda30be65f6f8c7801b16972a457e745
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/results-watcher-rhel8@sha256:79b90f23fe8b48c657d869c8c13b28d971c424fd43cdc647288786ccaee52f40
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/results-api-rhel8@sha256:3eb35e20507d5572c1908a1357e50abb032a04409d8273a9ee2e135c25f0bc96
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/cli-tkn-rhel8@sha256:51ecd29b1199057ece51eaa5911c2243561573d361bfccb44106a1c88444aacd
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/cli-tkn-rhel8@sha256:51ecd29b1199057ece51eaa5911c2243561573d361bfccb44106a1c88444aacd
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/cli-tkn-rhel8@sha256:51ecd29b1199057ece51eaa5911c2243561573d361bfccb44106a1c88444aacd
  - name: IMAGE_ADDONS_TKN_CLI_SERVE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/serve-tkn-cli-rhel8@sha256:ecee66ca69051e295232a8f1bb94238d583dd975caba43185e53bffb2d553eb0
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/manual-approval-gate-webhook-rhel8@sha256:6c33f9fed54cbfc354e186dffdd08c88bb209b098f7f6231dd293b1518dd9979
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/manual-approval-gate-controller-rhel8@sha256:4fe3ff4e2018b533964ec83e73ec747827e2f14c2cf8de9b3aa99d9ae49e3146
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipelines-as-code-controller-rhel8@sha256:57861ca35b143710d38ffd839e6dc7c0af4b5b29430eafcf3be1cfef854c2a94
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipelines-as-code-webhook-rhel8@sha256:215f7c39b2ac68b5d5ba277de98021ba687ca9a79e25a2ab0f380b77d7d44d5d
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipelines-as-code-watcher-rhel8@sha256:bd50b007d0923a798478a9653928effad68c367a18667875f9f44a370eeb9e8e
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/pipelines-as-code-cli-rhel8@sha256:7443bc3bfa4de4ea3a3506d59c847e8e1718bf14852718ea3e1597e30e8cba84
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/operator-operator-rhel8@sha256:6dae26c0946ef8597b3610b82013f26ff78ea74d308b75801bc392d351b4fcfb
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/operator-operator-rhel8@sha256:6dae26c0946ef8597b3610b82013f26ff78ea74d308b75801bc392d351b4fcfb
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/operator-proxy-rhel8@sha256:c3a6895e858c1a6e5a4d99167e6ce28149db30909859d9803b2cb03744dfcd87
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/operator-webhook-rhel8@sha256:2704c70d2a5caa7b0eea53c5c67717325db7739aaaec55e1fb9f0722663fe326
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:b50aad5938b729d2f405683aedaeb9b5cdfb13f4a95dbd81c78130fa4677dfa9
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:b50aad5938b729d2f405683aedaeb9b5cdfb13f4a95dbd81c78130fa4677dfa9
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:b50aad5938b729d2f405683aedaeb9b5cdfb13f4a95dbd81c78130fa4677dfa9
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:b50aad5938b729d2f405683aedaeb9b5cdfb13f4a95dbd81c78130fa4677dfa9
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:b50aad5938b729d2f405683aedaeb9b5cdfb13f4a95dbd81c78130fa4677dfa9
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/git-init-rhel8@sha256:b50aad5938b729d2f405683aedaeb9b5cdfb13f4a95dbd81c78130fa4677dfa9
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/console-plugin-rhel8@sha256:67255bdaa40c02bca908e9fa9b7844f5e683faf6ac776b63fb83329ece1a2030
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-15/operator-bundle-rhel8@sha256:550fe479fd1ab7ac34eeb87a42d26c29ca1554e84c1cd8f54907413eac453123
