versions:
  current: 1.20.1
  previous: 1.20.0
  previous_range: 1.19.0
  channel: pipelines-1.20
  openshift:
    latest: 4.20 # lastest GA'ed openshift
    min: 4.12 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-controller-rhel9@sha256:4d05c794b35907053d8ec927575097c6a138e9096415265fe2a5ec1a10fd43ff
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-webhook-rhel9@sha256:7bddad9ea3e77f285ece29ed67b405f4599cb54fa6a81e73c11cefa4cca3bd4d
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-resolvers-rhel9@sha256:4cd8f73f95612c82ab45dd193cae626a986f836ddefdf33ab37a9e2a991f7461
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-events-rhel9@sha256:3fc9679673cf7c9da183c303e1e4113419043e9346ea92cc964eccbbc601e934
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-entrypoint-rhel9@sha256:b55c638a96874619f524e4d227c117188d8395a0d3cc21e3ca63d60ba01af174
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-workingdirinit-rhel9@sha256:deab3b3997b0072a26a2e98309ef58f44bc684dc701da991d8d42d6c2ed4e5f2
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-nop-rhel9@sha256:8c414aac30ac5f636ab9636fbf60ea5bf07ae7ad8a4c90c021b3ae7ada1d4738
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-entrypoint-rhel9@sha256:b55c638a96874619f524e4d227c117188d8395a0d3cc21e3ca63d60ba01af174
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-sidecarlogresults-rhel9@sha256:e943501d76ed9fdcb2201fafcf441c182e68d454f3818500d1aae7a36ed193ed
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/triggers-controller-rhel9@sha256:c5c9cdd088907bad5963ae366463b848f93cddfe0cf95167a6cf69a18b2efe31
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/triggers-webhook-rhel9@sha256:406f5df9f2f8b1aaba92f060be8bc8f58f76a4286d7a6d2a81c5ca0416d1fef2
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/triggers-core-interceptors-rhel9@sha256:585049ad7bba55dc036e09b25a84d2686786defd2582e1e0f278722f7e1977bd
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/triggers-eventlistenersink-rhel9@sha256:23905283012ffb82b817763a0d6ae138d084a46b3404af2bfeeb0d32010c04a7
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/chains-controller-rhel9@sha256:5468c90739eda2f644df789714c42a5ffb1ef75ed4f2a7b26480fc2d16b081ed
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/hub-db-migration-rhel9@sha256:931d7426a123f064597a175b8b0bc1ea9642eb4e9907978388bdfac74f293261
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/hub-api-rhel9@sha256:fcacd67fdc9efc39d12bd2ffcb8da006384a6188971e3fc52b32c53bc3fe4f99
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/hub-ui-rhel9@sha256:860e6a6a4021a66a240bb6bc3feb8ea3e5c64a10e717a2b650fabec9df139205
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/results-watcher-rhel9@sha256:7ce49211cb47c519be105baf3587a4d516d4433031f1cb045188584cdcb99309
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/results-api-rhel9@sha256:f6a91cae22b6e804e9d477e019e615fa97bdb30efcb8c5726b14612488dbed2a
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/results-retention-policy-agent-rhel9@sha256:c624fcada7ce29149406b1fdc78cd50b4616ad2d5332b9330d96204cd10fd18d
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cli-tkn-rhel9@sha256:1901e1fcc7cf93c58f1e68bc7a7d642233de864efb607709b885bb075edd0406
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cli-tkn-rhel9@sha256:1901e1fcc7cf93c58f1e68bc7a7d642233de864efb607709b885bb075edd0406
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cli-tkn-rhel9@sha256:1901e1fcc7cf93c58f1e68bc7a7d642233de864efb607709b885bb075edd0406
  - name: IMAGE_ADDONS_TKN_CLI_SERVE
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:115eea1a5ca87f3b6b72db1df05b7386bf73dc70c9c2e4dc5e1a66700d960c37
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/manual-approval-gate-webhook-rhel9@sha256:050df6d37fc4dd87f3e5dd04619827650ad7ee5d0b8441a0c79247e8b4b06085
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/manual-approval-gate-controller-rhel9@sha256:3f16ab5b05d83af164ec7c57ae67b002f5acca94d33579aca3150e753b6e4c56
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipelines-as-code-controller-rhel9@sha256:5a3f1d6538b56916dc088665215887fc3a471c42d63613c5a1ecf910a05e2ba2
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipelines-as-code-webhook-rhel9@sha256:9992fd4b30ed36e9f0725f1e25bce48da8da41797074498dac7cbf58126eb2d7
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipelines-as-code-watcher-rhel9@sha256:541c31a4396459d6cd72b947865cf8c313b4d221d09f2fd66c188f3399e29cf5
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipelines-as-code-cli-rhel9@sha256:1af7d187084e2a3cb3d875aa2a86eacf3a9a4e922350176eb9456a45a7caaca6
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-operator-rhel9@sha256:e3613a5dd325c7f12563fcaafb2b1baba8c29586b317278a58eff46a3bb989cd
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-operator-rhel9@sha256:e3613a5dd325c7f12563fcaafb2b1baba8c29586b317278a58eff46a3bb989cd
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-proxy-rhel9@sha256:78ddfdc3ab9e3cb58cac0b35528182b4c0a0b56bc097a73cc4e83054c11cf933
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-webhook-rhel9@sha256:df22945aaa68bec626fc7bb8c205ff609d5c1fbc7e19dc625b4c3e43fa056055
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cache-rhel9@sha256:5a2323d9743e72986c695bc1313208bb631e05aabf0b1d49103f7d9cbbb2c331
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cache-rhel9@sha256:5a2323d9743e72986c695bc1313208bb631e05aabf0b1d49103f7d9cbbb2c331
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:52444eaec63f4ff5fcf26d94d7b4d9bc32708b79bd8c20d5b7b569f1a01bcf8d
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:52444eaec63f4ff5fcf26d94d7b4d9bc32708b79bd8c20d5b7b569f1a01bcf8d
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:52444eaec63f4ff5fcf26d94d7b4d9bc32708b79bd8c20d5b7b569f1a01bcf8d
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:52444eaec63f4ff5fcf26d94d7b4d9bc32708b79bd8c20d5b7b569f1a01bcf8d
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:52444eaec63f4ff5fcf26d94d7b4d9bc32708b79bd8c20d5b7b569f1a01bcf8d
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:52444eaec63f4ff5fcf26d94d7b4d9bc32708b79bd8c20d5b7b569f1a01bcf8d
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/console-plugin-rhel9@sha256:4440edc2b07d17bbc8932388e98225c38913ae60cb7c824210481db978038962
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-bundle-rhel9@sha256:a35147d0bf2c373a25f9e8151dd01d111b2f3084977e4bbd6fb4a45730027e40
  # opc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/opc-rhel9@sha256:9ae03521210e1f86084eb696518d3e01288166d245cdf176a68de6b6c131f51f
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pruner-controller-rhel9@sha256:0ebd14fd77cc45eaf804aa86b400541a143b798b59a7fadcec7f683a0a1e203e
