versions:
  current: 1.21.0
  previous: 1.20.1
  previous_range: 1.19.0
  channel: pipelines-1.21
  openshift:
    latest: 4.20 # lastest GA'ed openshift
    min: 4.14 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-controller-rhel9@sha256:169baba72361a07733b3b59d430d033895dfd8b1047535dd77150ddaddd1ef10
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-webhook-rhel9@sha256:03b07af41de8fd9aa6e95314454402aca7253f00d480234df2f74f89010b6bba
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-resolvers-rhel9@sha256:ec66018011062f9c47cb2d68f6fa5f6240e8bc0cde7822dc6d4332ca3a1c38be
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-events-rhel9@sha256:7ca94dfa448d4a091d53d2deaccdcbe2d1248b6a8006cbc5f5c0fcdd71582bbf
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-entrypoint-rhel9@sha256:058e9de80eaddec2dbef3761ddc1b27807b7c72b4f5b631fb8bb58d98d09ba59
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-workingdirinit-rhel9@sha256:de5e50e2193ea6bc529fd7379a0aa1dfe186a42ef02c791ab82c492114051851
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-nop-rhel9@sha256:70ade816c9f91371f0fb430ebcf1f0a1d6c4bfebed9110b2dc6253d83a55c1b2
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-entrypoint-rhel9@sha256:058e9de80eaddec2dbef3761ddc1b27807b7c72b4f5b631fb8bb58d98d09ba59
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-sidecarlogresults-rhel9@sha256:04a28de738345181501f48d9c6090447a4e1013d0096eedb7f486446f1bf212d
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/triggers-controller-rhel9@sha256:d139758b9a3c3fbada01c9ad0901975035b59439fab7826a28501555ff7386ab
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/triggers-webhook-rhel9@sha256:83ba6f2619bb64dbe190e6c8d735ae212adcfbd91c000e61275dd58df2a1edda
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/triggers-core-interceptors-rhel9@sha256:bfd4c4c538cc4b8b98850f5984570f742ea29110859f5a96619619f5760793df
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/triggers-eventlistenersink-rhel9@sha256:3337359b3fb74bcb2fb5b53eaf746dbeca258fdb15df3676921b7aeeabc44384
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/chains-controller-rhel9@sha256:167f9d89501838058e4aee9083a027bf82fa8247ffc282df8962bd0b739dcf3d
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/hub-db-migration-rhel9@sha256:7704dabe9b30ac8f7a8ecd49c1ef4feae44ed324d845daa8400e352edf4699ab
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/hub-api-rhel9@sha256:164ecf76545406e3ae19e82ae5c6736dd964204e7466a0d25115ffd31dd019ec
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/hub-ui-rhel9@sha256:33961c9a9c5d7d309e89f63e52cf9eae5d4e85980ce4f1522e5dc2a96c1bae39
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/results-watcher-rhel9@sha256:3648241a6e91f8e19113984b6bf6f9d457ba3a455f118a71d7e8960a60ed8b75
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/results-api-rhel9@sha256:fcfba5bd22bb2b69bb07024b4899dc222d820ebf4abe1085508398a6d7941feb
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/results-retention-policy-agent-rhel9@sha256:a67a5173c79fb9650bc8a6293625fdcc8dbdb1199053c667cf7bb61413ab06eb
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cli-tkn-rhel9@sha256:fe5ff08d2a56f91f6cc95a20e4d20595433503610efca79e8d0dcbb949eabb52
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cli-tkn-rhel9@sha256:fe5ff08d2a56f91f6cc95a20e4d20595433503610efca79e8d0dcbb949eabb52
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cli-tkn-rhel9@sha256:fe5ff08d2a56f91f6cc95a20e4d20595433503610efca79e8d0dcbb949eabb52
  - name: IMAGE_ADDONS_TKN_CLI_SERVE
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:115eea1a5ca87f3b6b72db1df05b7386bf73dc70c9c2e4dc5e1a66700d960c37
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/manual-approval-gate-webhook-rhel9@sha256:fdb8aacb72252b019ce256e33e65b333eff89bb2e52fe81957e3ef45040990a5
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/manual-approval-gate-controller-rhel9@sha256:ea73b6e6dbe66f7adb630029477e6c405af3d435bbf588f467467a1f4b126beb
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipelines-as-code-controller-rhel9@sha256:908444ab46d7169d146acfbe11fd2f4797bfe554d2ab02be26d1bc48c49f3883
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipelines-as-code-webhook-rhel9@sha256:a9f294dcb1a18aac0e0aee1f22fa6ff345c1dd352052cfb81d333d3f7dc57420
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipelines-as-code-watcher-rhel9@sha256:51598a9ea7fdbe540a383bae7ff6586164be79d3830f6c3b96e290264a6ce576
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipelines-as-code-cli-rhel9@sha256:004eb06526bc81cec17ea5da4b481429f7afc2062f9160bee62eeb578912280f
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-operator-rhel9@sha256:9c03749a4865885da6967059b7af3f4e5ba312d34a96984dfedf62c5bd4d39e5
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-operator-rhel9@sha256:9c03749a4865885da6967059b7af3f4e5ba312d34a96984dfedf62c5bd4d39e5
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-proxy-rhel9@sha256:0a1c668abd8e40faa0fe04c3b402ff56ca266d19e28a3606e7ddf0809b0bf0ad
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-webhook-rhel9@sha256:4d758074945c1fd53b995e83f8f6b35421c6e08046418204b928dd0205478c80
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cache-rhel9@sha256:855e5c3b43e77d2137f556a29ccaa4d4888ce53d40257f31f6b0fa2b5d53a60d
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cache-rhel9@sha256:855e5c3b43e77d2137f556a29ccaa4d4888ce53d40257f31f6b0fa2b5d53a60d
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:3fc4f5675f5a9123aec98b57df5d731a03528fc9f47e93bea4adef2fdc8a74e5
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:3fc4f5675f5a9123aec98b57df5d731a03528fc9f47e93bea4adef2fdc8a74e5
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:3fc4f5675f5a9123aec98b57df5d731a03528fc9f47e93bea4adef2fdc8a74e5
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:3fc4f5675f5a9123aec98b57df5d731a03528fc9f47e93bea4adef2fdc8a74e5
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:3fc4f5675f5a9123aec98b57df5d731a03528fc9f47e93bea4adef2fdc8a74e5
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:3fc4f5675f5a9123aec98b57df5d731a03528fc9f47e93bea4adef2fdc8a74e5
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/console-plugin-rhel9@sha256:f19098d1eb60049502d4a55f518743e1b5cc4cbe36f700428c46438459fc828d
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-bundle-rhel9@sha256:c9cf5383081db41086156fb76ceb75f5b0ce3743ed6fe836466152a2f7de9f51
  # opc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/opc-rhel9@sha256:348d01aa1b1e092baf164c820d295088162bb3518f07f4d740a21607236e5fda
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pruner-controller-rhel9@sha256:5579227c81155db825e9d2a5148348eccf2dd8fc15ed30fd0eb746d3906dbfca
  - name: IMAGE_PRUNER_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pruner-webhook-rhel9@sha256:1d098f9717153d4fa5fbf7250a5ed7798eb78d3b5cd5391e57d05c48033cb48d
