versions:
  current: 1.18.1
  previous: 1.18.0
  previous_range: 1.17.0
  channel: pipelines-1.18
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.15 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-controller-rhel9@sha256:b550a8bc2a87d07a5b22a3ec3fb83efd8eb26ca6e80d404f2e453cc9b8434da7
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-webhook-rhel9@sha256:8b4bf043e0fb237553503d63b129c432600bb4e65b2096b246b257b404b42be9
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-resolvers-rhel9@sha256:d72842a7c6a1e50a68576c93f60047afec801cf83db64d7d3e34b25bf3c753ec
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-events-rhel9@sha256:fa5c456fc91319c55fac9a011dc7bb32ef85db293c73d74436e903b76ceb4349
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-entrypoint-rhel9@sha256:b9675b22bc8759903472c1eb0e03f90c75460f02799d894294c161641cad9414
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-workingdirinit-rhel9@sha256:dbc462cb50385dec3a220b5d0caed0e0211c166182026f86e3c51a1351ba0de4
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-nop-rhel9@sha256:fcd5fd10de7334bd59a8da4997f91008ced95c6cde40d56d50f3b3e32c0f19e1
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-entrypoint-rhel9@sha256:b9675b22bc8759903472c1eb0e03f90c75460f02799d894294c161641cad9414
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-sidecarlogresults-rhel9@sha256:16d799503674641d4690822edc9c399c61429ccd31621d295eee4a4d1ef1c076
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/triggers-controller-rhel9@sha256:ca464cd6117acca56ba37af1d71ecc29af07c2d9f5f6d3c9c6168614d613d5ca
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/triggers-webhook-rhel9@sha256:1b57b64657eca0002145100bae262a19f02eb40068e07994df467e28a1618f90
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/triggers-core-interceptors-rhel9@sha256:5533bde7f230643d3b41cce84c35622971ff88bf92016f13efc2fc8bc65fa60f
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/triggers-eventlistenersink-rhel9@sha256:18ce88e2ca9c3ef380feb16e081a138b40adbed8b3c9f1633479bf0f45a29872
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/chains-controller-rhel9@sha256:c0c85f6c58a14dfaf7f85b73639a9f00373e862779b3b7d98cc0b270a7a926a4
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/hub-db-migration-rhel9@sha256:4077ee1c1d0fb4529025352e55fa11d7804f412c7e66a909eaaa6149afa7e196
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/hub-api-rhel9@sha256:8b9a52b748a65e337521834bceca1d68f28150ec99201b6e5bb503564f645963
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/hub-ui-rhel9@sha256:f4f03b80c444842d73df4f732e185a1ba4def34a95db50dd3caf20a2f9c41cba
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/results-watcher-rhel9@sha256:c71cb29b50734ebf7338aff500a432f960e54a371221f52241215e8b3ad55884
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/results-api-rhel9@sha256:a2d80f9b4048b758c3d767af46133b119723ed995202d3324c417995453c49a4
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/results-retention-policy-agent-rhel9@sha256:e371b11a4fbae4fae2a356abc44a81c87e9495348de1412fd183191215218eef
  - name: IMAGE_RESULTS_POSTGRES
    value: registry.redhat.io/rhel9/postgresql-13@sha256:36647bd6d50d2e0e9c99ecf190bd515577c7ce9476e49d927c4d4065011e3441
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cli-tkn-rhel9@sha256:9613b4fbf6b5b86d13880c448fe62abdc11b38fb05cd464eaf4a88a1ce490e5b
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cli-tkn-rhel9@sha256:9613b4fbf6b5b86d13880c448fe62abdc11b38fb05cd464eaf4a88a1ce490e5b
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cli-tkn-rhel9@sha256:9613b4fbf6b5b86d13880c448fe62abdc11b38fb05cd464eaf4a88a1ce490e5b
  - name: IMAGE_ADDONS_TKN_CLI_SERVE
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:d055d2b35a663aef3e1aafdbed0b12957867c0670c946ebae66e9c44a768bda2
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/manual-approval-gate-webhook-rhel9@sha256:92ce4259bb9f915fe6ccae9f11caa2c6481b901f8d18ecf3aef55ab9392dfe6e
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/manual-approval-gate-controller-rhel9@sha256:7d1ce653618324fd7c24f40d8d23f66ddf11d11169a27959578f7d82e580823b
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipelines-as-code-controller-rhel9@sha256:d9d06a4747135d27653e91567296e2eed4fa821ab7247d54bff5681baba19947
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipelines-as-code-webhook-rhel9@sha256:8756eec31bc8e89d423a4ec000db937f4807fe71192ecc65d85fe87fb0052954
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipelines-as-code-watcher-rhel9@sha256:8e221b92f230c9ee72b23c5463bffc731c64434fa81fbae6bdce3af7917cbb53
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipelines-as-code-cli-rhel9@sha256:b7dfaad856a1d4a856946d12dad3783dd5c04ecedbb76e3dfc8ee13405351b89
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-operator-rhel9@sha256:1ec85a3a2747b4634387c9f7989ffcaaa7e7ebacea8247bd50be940b1214291d
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-operator-rhel9@sha256:1ec85a3a2747b4634387c9f7989ffcaaa7e7ebacea8247bd50be940b1214291d
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-proxy-rhel9@sha256:36723896d37c8e5ea014c15d4b689cec6330ba829d4eda440ff2ae0234f3a17e
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-webhook-rhel9@sha256:450b954dd518a6422a6ed96f93e21114537e6f0ed21400bb664cff78f713cc2c
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cache-rhel9@sha256:1ada9cfd6bc3efd70172b87674248dd0ca52f9b2a6797e84cedbd07920e2a6c0
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cache-rhel9@sha256:1ada9cfd6bc3efd70172b87674248dd0ca52f9b2a6797e84cedbd07920e2a6c0
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:c35f4d893a19b08b681939bb3d5397f3e28343538cab1759dce2d059543096d7
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:c35f4d893a19b08b681939bb3d5397f3e28343538cab1759dce2d059543096d7
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:c35f4d893a19b08b681939bb3d5397f3e28343538cab1759dce2d059543096d7
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:c35f4d893a19b08b681939bb3d5397f3e28343538cab1759dce2d059543096d7
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:c35f4d893a19b08b681939bb3d5397f3e28343538cab1759dce2d059543096d7
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:c35f4d893a19b08b681939bb3d5397f3e28343538cab1759dce2d059543096d7
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/console-plugin-rhel9@sha256:f7e51c43a07a1e5fc4b9e186a36da1d6fea4b29a97592b725d8817fe27e865a8
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-bundle-rhel9@sha256:80893161e42f45b6b54462df2858741b29d3003899adb9ea8120426e13b14db2
