versions:
  current: 1.21.0
  previous: 1.20.1
  previous_range: 1.20.0
  channel: pipelines-1.21
  openshift:
    latest: 4.20 # lastest GA'ed openshift
    min: 4.14 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-controller-rhel9@sha256:f12e90615e74a57bda85781606796e33c53988995b5ba76b92ca10e8385f5608
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-webhook-rhel9@sha256:fec4ff6f33e03e85e150d7e4dd6d78f1b0d058de605f5c783fb2774cb5fbfbe4
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-resolvers-rhel9@sha256:084ba20ee85e06d66daea85c80a898568fe921b73e9af847db1cfde2c0940766
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-events-rhel9@sha256:ef681c3ef261e4a52bf899e59fbdcbd4e75a1cee890516b0984213e4c2de84f3
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-entrypoint-rhel9@sha256:1b81de97d903f3db90df264e6ee390e5d32a655758547ad8a998bbff3a9fbac4
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-workingdirinit-rhel9@sha256:1c261a95559f399fe7540756dc6358fe686418d969a60ed77ccd0b6d6f9c79e9
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-nop-rhel9@sha256:58fb79ef1cfef8216d7585c8f0234d96b88b71a5d877575887d474defc007e41
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-entrypoint-rhel9@sha256:1b81de97d903f3db90df264e6ee390e5d32a655758547ad8a998bbff3a9fbac4
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-sidecarlogresults-rhel9@sha256:03987cea84a592d0fd9b16e4f0d6b38be654928cbd927e1c14c5262dde89a14e
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/triggers-controller-rhel9@sha256:3686690bd6990aaabff551182d4011c52710b9f3b85ec2c90b0c384f5a52b1f4
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/triggers-webhook-rhel9@sha256:9da732aefd209a9bcf5a763358ef5ad4ad55a5d1f297217f9f33b85550f699f5
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/triggers-core-interceptors-rhel9@sha256:9b58809450ff0a0f095302c07604bc03996cb15a513bc5c9c376b1ee3aade06c
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/triggers-eventlistenersink-rhel9@sha256:6ddcd2bc594df131a83ed30bc42c7cc5999f36cb68bae1cb33f2b81671364a2f
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/chains-controller-rhel9@sha256:08123c8c80f006681df63b13319a018af29678d2deb0ff60ae502481f5c710cd
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/hub-db-migration-rhel9@sha256:1727c78d303cace842a7f892031ce167c4ed3f91da4c833835d207496b26fb00
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/hub-api-rhel9@sha256:e85d96dbc537ee7a1c9eb8ff3042de04671aecaf9f311c3cd50066eb114ce9e4
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/hub-ui-rhel9@sha256:4785441802d558065f6c01a64b56db2a22c772a81afd36e602e12e124cc17126
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/results-watcher-rhel9@sha256:58cf1348c5526ca53bc960c2eda3a8f1a471f34e4d8e701dc005e875c79cde09
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/results-api-rhel9@sha256:e34120c7d4dd958ea202885ffcaa7b67dffd7bb833cdbe9a22ef42b798baa3ba
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/results-retention-policy-agent-rhel9@sha256:1d07f6fcc5d8ac793d40e4164e44ce7f46bfcb64bbd95b0570cf1eb626529488
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cli-tkn-rhel9@sha256:cf1f095fbc436f829822455e97d89bd19ce5362952b3e7d281ba9a25e4bc11fa
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cli-tkn-rhel9@sha256:cf1f095fbc436f829822455e97d89bd19ce5362952b3e7d281ba9a25e4bc11fa
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cli-tkn-rhel9@sha256:cf1f095fbc436f829822455e97d89bd19ce5362952b3e7d281ba9a25e4bc11fa
  - name: IMAGE_ADDONS_TKN_CLI_SERVE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/serve-tkn-cli-rhel9@sha256:40592fa7c65cd2a6a2f40655b147e8d9563b23fef8389b0be525e66d3d717831
  - name: IMAGE_ADDONS_TKN_CLI_SERVE_INIT_CONFIG
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/serve-tkn-cli-rhel9@sha256:40592fa7c65cd2a6a2f40655b147e8d9563b23fef8389b0be525e66d3d717831
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/manual-approval-gate-webhook-rhel9@sha256:bb7f8815aa0e7fd0a197cf44ce9b754abf2af953a6baa916c96e35011fdb4182
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/manual-approval-gate-controller-rhel9@sha256:2431521236629eb9468c78af63c8cea3c5ae4d02d675312f0a6bad7e2e26d1d5
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipelines-as-code-controller-rhel9@sha256:3d34903d9437b1802cbe4addc8c71abb1f45b7fe73541dd8f7df2873c868aaed
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipelines-as-code-webhook-rhel9@sha256:fd202ab5831b06899af1c85d7a3433fbc7cfbaf972a58c04caa76ce65d985784
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipelines-as-code-watcher-rhel9@sha256:491b5130dbb8b97cd9ed7c32e60d5dd47f93a6da0be41bddeefada7e7e964fa5
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipelines-as-code-cli-rhel9@sha256:7d4241251fb09ad18b8350e097d58bd9c0554a27c765e2dfde358fac7b25e98a
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-operator-rhel9@sha256:28556882ef1a0a9f39250d7c39186a3325e0f26d7be793be7ec32bc267c6d4c2
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-operator-rhel9@sha256:28556882ef1a0a9f39250d7c39186a3325e0f26d7be793be7ec32bc267c6d4c2
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-proxy-rhel9@sha256:48503874cc4d18b66c994fef86a88ea9cb6fed9964f65aef7ec4e889ca57275a
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-webhook-rhel9@sha256:223219ff09415d354f622db97bb33e5f6557a56c2bd8dad8189b5f2d34508dd8
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cache-rhel9@sha256:855e5c3b43e77d2137f556a29ccaa4d4888ce53d40257f31f6b0fa2b5d53a60d
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cache-rhel9@sha256:855e5c3b43e77d2137f556a29ccaa4d4888ce53d40257f31f6b0fa2b5d53a60d
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:09e7149ccda940dee11abf9184bb58004462ab825f8aa635cd003d2645738d80
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:09e7149ccda940dee11abf9184bb58004462ab825f8aa635cd003d2645738d80
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:09e7149ccda940dee11abf9184bb58004462ab825f8aa635cd003d2645738d80
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:09e7149ccda940dee11abf9184bb58004462ab825f8aa635cd003d2645738d80
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:09e7149ccda940dee11abf9184bb58004462ab825f8aa635cd003d2645738d80
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:09e7149ccda940dee11abf9184bb58004462ab825f8aa635cd003d2645738d80
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/console-plugin-rhel9@sha256:81fa66370d537550b507ab31c2ce35fab1beae2ce2446eced089818072a47af3
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-bundle-rhel9@sha256:e0c7eb35dfd5fb564f54b1f0e1f25acc886d92e5e90b9c74915fa9cc2def1383
  # opc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/opc-rhel9@sha256:91a82639d5e5c7da45b7cc8f862d1a9781686547c6676bf5d6f3016bb81bf6dd
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pruner-controller-rhel9@sha256:3d5c4864d5a5dabee8dd62b68ba1e90ac9b3138d91727853c49f67ac49cdb2b6
  - name: IMAGE_PRUNER_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pruner-webhook-rhel9@sha256:03eb7adeaf60ffa0cd966e7bbef1d11f9c5ccabe140b1e7271437b56b74cb6e0
