versions:
  current: 1.21.0
  previous: 1.20.1
  previous_range: 1.20.0
  channel: pipelines-1.21
  openshift:
    latest: 4.20 # lastest GA'ed openshift
    min: 4.14 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-controller-rhel9@sha256:f12e90615e74a57bda85781606796e33c53988995b5ba76b92ca10e8385f5608
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-webhook-rhel9@sha256:fec4ff6f33e03e85e150d7e4dd6d78f1b0d058de605f5c783fb2774cb5fbfbe4
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-resolvers-rhel9@sha256:084ba20ee85e06d66daea85c80a898568fe921b73e9af847db1cfde2c0940766
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-events-rhel9@sha256:ef681c3ef261e4a52bf899e59fbdcbd4e75a1cee890516b0984213e4c2de84f3
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-entrypoint-rhel9@sha256:1b81de97d903f3db90df264e6ee390e5d32a655758547ad8a998bbff3a9fbac4
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-workingdirinit-rhel9@sha256:1c261a95559f399fe7540756dc6358fe686418d969a60ed77ccd0b6d6f9c79e9
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-nop-rhel9@sha256:58fb79ef1cfef8216d7585c8f0234d96b88b71a5d877575887d474defc007e41
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-entrypoint-rhel9@sha256:1b81de97d903f3db90df264e6ee390e5d32a655758547ad8a998bbff3a9fbac4
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-sidecarlogresults-rhel9@sha256:03987cea84a592d0fd9b16e4f0d6b38be654928cbd927e1c14c5262dde89a14e
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/triggers-controller-rhel9@sha256:874fa6d4a3ef2935c1dd333291ee2e2db7dd85ed446bbaf25facab9c80a1560b
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/triggers-webhook-rhel9@sha256:3e8f5c5066b1ce4d4708af4d8fc75bee2b1d27d99488257071a7af8b425fc65a
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/triggers-core-interceptors-rhel9@sha256:9b58809450ff0a0f095302c07604bc03996cb15a513bc5c9c376b1ee3aade06c
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/triggers-eventlistenersink-rhel9@sha256:a70d364349dc25fd119c3c4a27218c0dffdee33cc03f0897d233af1d113e9fbc
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/chains-controller-rhel9@sha256:167f9d89501838058e4aee9083a027bf82fa8247ffc282df8962bd0b739dcf3d
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/hub-db-migration-rhel9@sha256:79c240b2be1c4334f02575257956a80ff01e9ae4f547ededcb1b9a5ad6209306
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/hub-api-rhel9@sha256:e4f234371377bf2a766021c3d9ff86df98c192e0d1f86ebd3494ae4d9264b978
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/hub-ui-rhel9@sha256:56784afc5f579c412411df2fb13a4c06da3320fcd445ca517214b451e7799e33
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/results-watcher-rhel9@sha256:3648241a6e91f8e19113984b6bf6f9d457ba3a455f118a71d7e8960a60ed8b75
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/results-api-rhel9@sha256:fcfba5bd22bb2b69bb07024b4899dc222d820ebf4abe1085508398a6d7941feb
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/results-retention-policy-agent-rhel9@sha256:a67a5173c79fb9650bc8a6293625fdcc8dbdb1199053c667cf7bb61413ab06eb
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cli-tkn-rhel9@sha256:b0522305f1d0ea568d8ca7503b5c23a8d1d7c19e6470b0070d64aad2c0db4e88
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cli-tkn-rhel9@sha256:b0522305f1d0ea568d8ca7503b5c23a8d1d7c19e6470b0070d64aad2c0db4e88
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cli-tkn-rhel9@sha256:b0522305f1d0ea568d8ca7503b5c23a8d1d7c19e6470b0070d64aad2c0db4e88
  - name: IMAGE_ADDONS_TKN_CLI_SERVE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/serve-tkn-cli-rhel9@sha256:40592fa7c65cd2a6a2f40655b147e8d9563b23fef8389b0be525e66d3d717831
  - name: IMAGE_ADDONS_TKN_CLI_SERVE_INIT_CONFIG
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/serve-tkn-cli-rhel9@sha256:40592fa7c65cd2a6a2f40655b147e8d9563b23fef8389b0be525e66d3d717831
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/manual-approval-gate-webhook-rhel9@sha256:fdb8aacb72252b019ce256e33e65b333eff89bb2e52fe81957e3ef45040990a5
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/manual-approval-gate-controller-rhel9@sha256:ea73b6e6dbe66f7adb630029477e6c405af3d435bbf588f467467a1f4b126beb
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipelines-as-code-controller-rhel9@sha256:3d34903d9437b1802cbe4addc8c71abb1f45b7fe73541dd8f7df2873c868aaed
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipelines-as-code-webhook-rhel9@sha256:fd202ab5831b06899af1c85d7a3433fbc7cfbaf972a58c04caa76ce65d985784
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipelines-as-code-watcher-rhel9@sha256:491b5130dbb8b97cd9ed7c32e60d5dd47f93a6da0be41bddeefada7e7e964fa5
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipelines-as-code-cli-rhel9@sha256:7d4241251fb09ad18b8350e097d58bd9c0554a27c765e2dfde358fac7b25e98a
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-operator-rhel9@sha256:2787fe720e8b45570e2f04354c572697ed3e074b0404b4417dfcbaefc8d49d2c
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-operator-rhel9@sha256:2787fe720e8b45570e2f04354c572697ed3e074b0404b4417dfcbaefc8d49d2c
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-proxy-rhel9@sha256:94d51190fd32c9ae0bffbcc3c837cdb5a53b79bd2584bf5ca2920359eb56430c
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-webhook-rhel9@sha256:312d37fbb3540f930f277a4a36e4086fc0308073e7b3bc9c7884830d497c3890
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cache-rhel9@sha256:855e5c3b43e77d2137f556a29ccaa4d4888ce53d40257f31f6b0fa2b5d53a60d
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cache-rhel9@sha256:855e5c3b43e77d2137f556a29ccaa4d4888ce53d40257f31f6b0fa2b5d53a60d
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:e9d8c9210d44ae19f5a872a0696ceff49ef35f8817d58e0d6cf577336939be04
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:e9d8c9210d44ae19f5a872a0696ceff49ef35f8817d58e0d6cf577336939be04
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:e9d8c9210d44ae19f5a872a0696ceff49ef35f8817d58e0d6cf577336939be04
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:e9d8c9210d44ae19f5a872a0696ceff49ef35f8817d58e0d6cf577336939be04
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:e9d8c9210d44ae19f5a872a0696ceff49ef35f8817d58e0d6cf577336939be04
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:e9d8c9210d44ae19f5a872a0696ceff49ef35f8817d58e0d6cf577336939be04
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/console-plugin-rhel9@sha256:c78b8b5b7cf4b9729e97b929d5c93e440525108e2e8eb5b3cd447f8eb1515b1b
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-bundle-rhel9@sha256:0b03c43f82fe77874d6cb1e53ab870b4321df03157d2154390049c9a9c988961
  # opc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/opc-rhel9@sha256:348d01aa1b1e092baf164c820d295088162bb3518f07f4d740a21607236e5fda
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pruner-controller-rhel9@sha256:9cfd0b59920117a7b14cf6c11a6336202f1fa5edfedd05d8056c9afbf08f46ad
  - name: IMAGE_PRUNER_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pruner-webhook-rhel9@sha256:e30d95a978a8c57f2147fe257f9ca6327902ae432f4bbd7ea138f49ec4219f3d
