versions:
  current: 1.22.0
  previous: 1.21.0
  previous_range: 1.21.0
  channel: pipelines-1.22
  openshift:
    latest: 4.20 # lastest GA'ed openshift
    min: 4.16 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-controller-rhel9@sha256:ec720993e61d488280b11b4448f792b8ef1f60e7be987a8b962712e6125b985a
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-webhook-rhel9@sha256:d80157114c218bd693beadeb965a0c311b96d4ba48457ca777d1cc0e82d220de
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-resolvers-rhel9@sha256:2d18a832bb0f7a2a204b2b40178dfd11615ed1028b05fb7bc21177a5edc7b82e
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-events-rhel9@sha256:50e777e6b314d2d9611d2ff6d2a340404653bbc00ae81060a8cd0b0281fa5045
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-entrypoint-rhel9@sha256:330d3789901765b01d1fe7cb78a0eebedb2963712ff65947b68c105d15b2d9a2
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-workingdirinit-rhel9@sha256:f3b2389b505bd28e9c25d8ebbed4af220d512274fc97088b96e67920bb65c3a2
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-nop-rhel9@sha256:e67623926ce5242de2df5fc79435f36f494d02955fcc79144247cbb14ba3beca
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-entrypoint-rhel9@sha256:330d3789901765b01d1fe7cb78a0eebedb2963712ff65947b68c105d15b2d9a2
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-sidecarlogresults-rhel9@sha256:54d69bdff09ba74364554a3f76dd9ac043d1e05858eeb093858d8f6d420cf6aa
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-controller-rhel9@sha256:2ebb6f9a4cc0b3ce596feafd2a69c55561c7cc6573a5f6db498bad6d7858065b
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-webhook-rhel9@sha256:b250d4662967227cc892d007bb9ad72b1a12aa791839a0d1c8772cb8cea46d85
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-core-interceptors-rhel9@sha256:adfbb835bb0d613fc465a6d97e30c5e6b16998cf827387a8b4940b9e7529d69a
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-eventlistenersink-rhel9@sha256:cd07f7db82638879761cbc686ecc6d475324a4c5755d68255765190e6cd89cd5
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-chains-controller-rhel9@sha256:594abd79fa5d0cd91c68e6fb92df127bea919c2c5ac8246171fb458ba9bfdbcc
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-hub-db-migration-rhel9@sha256:7dff546519fce797ab51e193b9a8fb842852468477ae13042647d87f382f2909
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-hub-api-rhel9@sha256:e3122bdc5522895a5ded8da8bb49704377ef11b744090dc678b558a7ff8216c5
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-hub-ui-rhel9@sha256:bb2787a20d8ddfc227ac77aa42f8d7af0f4f835e0a605bcfd1bbe0d2f746c7a2
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-results-watcher-rhel9@sha256:a0aa6e5bf4bfe9b381f5484243bb0b25762a18827b5ff2c990381c3c15fd902e
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-results-api-rhel9@sha256:00360381f845cc27eb8cd47d44f8cf09ea9ae292a345f29f8d025bd7d5392732
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-results-retention-policy-agent-rhel9@sha256:8314d57a051d387c8d78e93bb139dc35e7b1211aa9549dee205113b0280d566f
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cli-tkn-rhel9@sha256:38544f9383318677e3836cac5c1e44b011f8bcc2a83eeef74a39d2cf63b1ad83
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cli-tkn-rhel9@sha256:38544f9383318677e3836cac5c1e44b011f8bcc2a83eeef74a39d2cf63b1ad83
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cli-tkn-rhel9@sha256:38544f9383318677e3836cac5c1e44b011f8bcc2a83eeef74a39d2cf63b1ad83
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/serve-tkn-cli/pipelines-serve-tkn-cli-rhel9@sha256:de509e1dcbb7dee0cd381120cef304bad59d51c19ff419ced82ffb78bab0f8b0
  - name: IMAGE_ADDONS_TKN_CLI_SERVE_INIT_CONFIG
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/serve-tkn-cli/pipelines-serve-tkn-cli-rhel9@sha256:de509e1dcbb7dee0cd381120cef304bad59d51c19ff419ced82ffb78bab0f8b0
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-manual-approval-gate-webhook-rhel9@sha256:fc0cac81b8ed589c88b33723f5b8621c198309462f6f9949eaf9cf3ac2d7508e
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-manual-approval-gate-controller-rhel9@sha256:39224de43574de84f25e4aed98b5f1ad8374e4913aa11056e05f82f3fe201f46
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-controller-rhel9@sha256:3792585160722402b7fb9d27e942e1a774a72e2e8139153316ad1b51651ed976
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-webhook-rhel9@sha256:c176ecb204131a4276685a0189fde4e18309c1a5fe1bf60703e14bc3d906e555
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-watcher-rhel9@sha256:8a786bb02d7c26f639d3d2d7b489b3de65889cfc88d2f161a9bf918d601a56a7
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-cli-rhel9@sha256:34c2d688b7239a3ffdc82c531bcd74c0310c32207e31dcf5910487b192559f5a
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-rhel9-operator@sha256:d66a751bfac1a559eb66ddde490514db9126ef0440ba01753358d3107dedca8a
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-rhel9-operator@sha256:d66a751bfac1a559eb66ddde490514db9126ef0440ba01753358d3107dedca8a
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-operator-proxy-rhel9@sha256:1f90ef83aecf3bf10138d2648b0f2c47b5f679372a2856a3a6ba2f93a2bb99c8
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-operator-webhook-rhel9@sha256:bf85d29b8682f1fc3b4c33b97697bc0b26a11331b635a407e323efcd89b4c6a5
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cache-rhel9@sha256:754b68efffa8bc1c959725e80e85292f758e0569aff9b0e7d8652eb1d5254e6d
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cache-rhel9@sha256:754b68efffa8bc1c959725e80e85292f758e0569aff9b0e7d8652eb1d5254e6d
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:47ac8a309b88a4930b0743c6c0f6258446ff499c947e4c2f7cc30a88f0094868
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:47ac8a309b88a4930b0743c6c0f6258446ff499c947e4c2f7cc30a88f0094868
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:47ac8a309b88a4930b0743c6c0f6258446ff499c947e4c2f7cc30a88f0094868
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:47ac8a309b88a4930b0743c6c0f6258446ff499c947e4c2f7cc30a88f0094868
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:47ac8a309b88a4930b0743c6c0f6258446ff499c947e4c2f7cc30a88f0094868
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:47ac8a309b88a4930b0743c6c0f6258446ff499c947e4c2f7cc30a88f0094868
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-console-plugin-rhel9@sha256:538c64cd0715b81d9d97580cdb053c519d56b21f5ca398fb69e073bae1107b98
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-operator-bundle@sha256:7cc11526387f36e25631eaf8e14100985b6e8986209fd33377f69aca762f131c
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-opc-rhel9@sha256:1ae8df50a48afd0f2c5e45d56bb7aa6a99168704157fa7827057acd834c2e905
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pruner-controller-rhel9@sha256:63b5888a87cf45ae008f8b0241394ee59760fbc659ab200536c204cf1b345546
  - name: IMAGE_PRUNER_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pruner-webhook-rhel9@sha256:34e66d49dfaa5b02c0eea281ee73e77f75f41f2b09312df03374da300778066f
  # Scheduler
  - name: IMAGE_SCHEDULER_MANAGER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-scheduler-rhel9@sha256:ba1fc862eea6a3ac848de3026d87f065327312ddbde3623ad00cd945795fc867
  - name: IMAGE_SCHEDULER_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-scheduler-rhel9@sha256:ba1fc862eea6a3ac848de3026d87f065327312ddbde3623ad00cd945795fc867
