versions:
  current: 1.21.0
  previous: 1.20.2
  previous_range: 1.20.0
  channel: pipelines-1.21
  openshift:
    latest: 4.20 # lastest GA'ed openshift
    min: 4.14 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-controller-rhel9@sha256:81bc3c514f3b41cb880ad4d1dc01b0f45a8f9a18fc278865d92072fc3e09d84c
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-webhook-rhel9@sha256:6e94e40ffeb40f92a6a4cde5d5f93e4e967fb682c7e820fd1544780b697cc241
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-resolvers-rhel9@sha256:5a194173b913be56ec82f5bd831ab2dd6b5bdc32b129c51e812d694543571a89
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-events-rhel9@sha256:05b92e6cf3cc8bf3ec5f37eb2692ef68030a7ac07bc1ce953f3f870e53f13413
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-entrypoint-rhel9@sha256:06af4d4300717a3735ca5edfef90573803423e51032b821ef5a4a0708fd6a3fe
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-workingdirinit-rhel9@sha256:d84507ab40bc07869c4c4c5914c31c18bfca3b27e2e5b0d778933b4c4e00d426
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-nop-rhel9@sha256:3df2d1d173bb65fd6bc11844430385c506dd7277f13cf8451fb45a4ab4dafbbf
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-entrypoint-rhel9@sha256:06af4d4300717a3735ca5edfef90573803423e51032b821ef5a4a0708fd6a3fe
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-sidecarlogresults-rhel9@sha256:88ab5714873a26dab3f918440918cbeb94f3dc3d47bda04e3e2028ef097be6b0
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/triggers-controller-rhel9@sha256:431c6f8d8864497390b04c2b23332d647015fced6c0f64ddb63552941394aed1
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/triggers-webhook-rhel9@sha256:c2452cda88f7976e19960e3b0c29ecf719a3fde24231d3b57a89b167642839ad
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/triggers-core-interceptors-rhel9@sha256:064677ed3f81aee490cc25f061dde5008c7410a503e00e26dc2b6910d54cb6ba
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/triggers-eventlistenersink-rhel9@sha256:7fbf2fdaa98bf1cfbdd6412a6cdfb7063a4f174f8d71f0d7bdc73fdbfba88820
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/chains-controller-rhel9@sha256:da8c904ebef9137f1be76d8ae317a042d99fff46025c5425b7ff09e04b048d43
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/hub-db-migration-rhel9@sha256:721e65ad2c9561841db263e19dfbe716cb0d12b954ee8e1468dfbe3028da0f91
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/hub-api-rhel9@sha256:181da28eebbe47d5e98aa18ba0352c8be7169f5bc92330f9343c9d96500fe344
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/hub-ui-rhel9@sha256:3b45b3c1686e29f9277e85e4320c6a2a3976df2319a3d9ed372cf7495ba5c4ff
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/results-watcher-rhel9@sha256:baf5c05a730e9a19bedf783b6070e7bc3f32417d5e02ae684e440521f7c1f964
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/results-api-rhel9@sha256:43b2f1c0bbebe2062ba9d74adbaf653769514672aacdcf7849f45c3553dead7a
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/results-retention-policy-agent-rhel9@sha256:9816cb86c44759148fca608f5ea8f10da0bc82f26cbe655254992b52febbe11e
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cli-tkn-rhel9@sha256:c59eb850cf59615b2d54247101e146a7d8818b1c6e95279863a512a3e0f93ae4
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cli-tkn-rhel9@sha256:c59eb850cf59615b2d54247101e146a7d8818b1c6e95279863a512a3e0f93ae4
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cli-tkn-rhel9@sha256:c59eb850cf59615b2d54247101e146a7d8818b1c6e95279863a512a3e0f93ae4
  - name: IMAGE_ADDONS_TKN_CLI_SERVE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/serve-tkn-cli-rhel9@sha256:86d4d2d86f3fa1b103c260d6ef7e861d4c3ca1edbe952803d0b524c6f7935eaa
  - name: IMAGE_ADDONS_TKN_CLI_SERVE_INIT_CONFIG
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/serve-tkn-cli-rhel9@sha256:86d4d2d86f3fa1b103c260d6ef7e861d4c3ca1edbe952803d0b524c6f7935eaa
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/manual-approval-gate-webhook-rhel9@sha256:396ce34a6470d077782d2508891e98eedd93df4f20426bb494cc7cb87ff8eaa7
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/manual-approval-gate-controller-rhel9@sha256:8e3594e397e4b4023534456c0dc452a8dfc0d0d315d4c567854fe29a22be2825
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipelines-as-code-controller-rhel9@sha256:33868591f112652403336ac60c7049d674a8dfde2b6f4d877954c2f8c08dcb92
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipelines-as-code-webhook-rhel9@sha256:e773a7fd7e27d56b3cc8d79dfd2df64e303c5e190b8fd8093fbf9754406d3492
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipelines-as-code-watcher-rhel9@sha256:fe7f35d879d6628ffd3256673604451656318d596a821cf2bc038096eb91bb71
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipelines-as-code-cli-rhel9@sha256:31a3afdf9e7e864eadcf315cbdb7c0a47757512c211a6ee459745292ccafd2c3
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-operator-rhel9@sha256:36374598abb8d0b17d26b78ce2f92d87fe3a1f2ac8b4434f1397e0d02619bee5
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-operator-rhel9@sha256:36374598abb8d0b17d26b78ce2f92d87fe3a1f2ac8b4434f1397e0d02619bee5
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-proxy-rhel9@sha256:f3b3a1adbfdae9b0cfe563dbbd2f8ab021a10705665b436f65bf108f75cc704b
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-webhook-rhel9@sha256:8fb8b0b5d1b066820a81fbc116d2f9fcd6309f7bd53c291a1f9aa15891422e09
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cache-rhel9@sha256:ce548401247c025aa5dee6ed641ede514a8ce19cbfb6fbe41edeabcdb1d493f2
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cache-rhel9@sha256:ce548401247c025aa5dee6ed641ede514a8ce19cbfb6fbe41edeabcdb1d493f2
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:665dae0d8a843f89e5bff8ae7e56f27829b2218242085a09ac0cc1659e2acf85
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:665dae0d8a843f89e5bff8ae7e56f27829b2218242085a09ac0cc1659e2acf85
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:665dae0d8a843f89e5bff8ae7e56f27829b2218242085a09ac0cc1659e2acf85
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:665dae0d8a843f89e5bff8ae7e56f27829b2218242085a09ac0cc1659e2acf85
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:665dae0d8a843f89e5bff8ae7e56f27829b2218242085a09ac0cc1659e2acf85
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:665dae0d8a843f89e5bff8ae7e56f27829b2218242085a09ac0cc1659e2acf85
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/console-plugin-rhel9@sha256:9bd9cd6f769b17095f9adaa370358d83b64d735dd811bb6dc6aea1936bb290e7
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-bundle-rhel9@sha256:c49def0d6a9578f2aecfeba782eb7ecbc938ffb3f9fa460b5588a5c358743c3d
  # opc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/opc-rhel9@sha256:d7e2ee83dec6f23ad9cfc0d173aaf9930c2e458cee7e464a1c8437dd3525612f
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pruner-controller-rhel9@sha256:f5d24a923cf6a3051bccc6f37adefb8fe34e108330f558f29c06f8ae454fb32e
  - name: IMAGE_PRUNER_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pruner-webhook-rhel9@sha256:30d850de2064a8207a2429ecd61c2e34230b597daae08dc787e140e6d684cdcf
