versions:
  current: 1.16.4
  previous: 1.16.3
  previous_range: 1.15.0
  channel: pipelines-1.16
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.12 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/pipeline-controller-rhel8@sha256:5672f3a375c6a274200b423eb2643c818aba75488dec0b210fec2532814ba51e
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/pipeline-webhook-rhel8@sha256:aacdabe243dc573f3161a3d04fbf014b77d9962207305d70fcafce475f7eea93
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/pipeline-resolvers-rhel8@sha256:d36dbb60c7b5caca7f3be08705f8ab91d7f01abaf8bfee4aee73bdbbb3e7e71a
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/pipeline-events-rhel8@sha256:aeeed543412cde0bd3a9baec965cb99d80f2b6acb77ae6356ed51b4b1262d006
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/pipeline-entrypoint-rhel8@sha256:e1fe4a86211cf22e5ad2b23c989d24b69f597db4c3604e84777dbd0c585ec186
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/pipeline-workingdirinit-rhel8@sha256:7da7f929d2711fc55dda01fe51a474bfa7adf5aaf78be6d65a6d65850958d6e7
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/pipeline-nop-rhel8@sha256:7edbd11e5a449408d673cae1fc2b9b5bab492ecff2ac6e640c8cd69a9b90ff08
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/pipeline-entrypoint-rhel8@sha256:e1fe4a86211cf22e5ad2b23c989d24b69f597db4c3604e84777dbd0c585ec186
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/pipeline-sidecarlogresults-rhel8@sha256:eb5866c21b21ccf2761c5c0cc22f3893e85472682c14f976ccca4282d8e9b748
  # tektoncd-triggerspipelines
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/triggers-controller-rhel8@sha256:90e2a7ea498da756e09c7e4d19c7fb91d429cc28c57f97c6958958e3466cb58c
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/triggers-webhook-rhel8@sha256:b41b888fc1a3b7215e6b71ee97bf64a1816914a8f33e96ad3930a4e2d5b5ffa7
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/triggers-core-interceptors-rhel8@sha256:19b3dd69c1d7e17890b7163aef322c1efbc76fed7f2b1faf26aaa05fd8161184
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/triggers-eventlistenersink-rhel8@sha256:856229e9e37683c926e3449658d76f93d910384eff62c2ca192768a653b71533
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/chains-controller-rhel8@sha256:dcab4a3d519975340ade59a0ca0222104e68acd052a61f2aeb8c736be4b672cb
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/hub-db-migration-rhel8@sha256:d2bb3f9f79ef719d8fdafef3a639e3eb8bc199ee56fcfb33e85975d536d2a6ac
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/hub-api-rhel8@sha256:c6d654c71aba35c3c7f5c1a2ca5b8401e95adf6f649c599a9aff25177c2b3323
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/hub-ui-rhel8@sha256:47f094ccd12db7a43c8a91c1a3d2a190bc2b83f1745e7eb8ce097d0c8e1e2c88
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/results-watcher-rhel8@sha256:b94bd566ae3d9ce5f47273d867164486826b19fca0ce11d1a7d18312413e87ba
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/results-api-rhel8@sha256:549d74a18ec52db91fa949cac9b8e3d943d478d5dec9850d2ba0cb1bb526f578
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/results-retention-policy-agent-rhel8@sha256:8cb87920e6fc8185ead49aafb7799fead6a4a510eafdae0ee29e85248dae3945
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/cli-tkn-rhel8@sha256:18ce3639182ccb3f967c069a6e5a73248c47c0d1a0009ba06c9ed12c10ac9fb3
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/cli-tkn-rhel8@sha256:18ce3639182ccb3f967c069a6e5a73248c47c0d1a0009ba06c9ed12c10ac9fb3
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/cli-tkn-rhel8@sha256:18ce3639182ccb3f967c069a6e5a73248c47c0d1a0009ba06c9ed12c10ac9fb3
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel8@sha256:6acc31f179b08658976cddcb9ef42f377edb29933d1d83a2ecebfd455bb68571
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/manual-approval-gate-webhook-rhel8@sha256:f9122d71c3862cd2afafc8eb7f1a39c83eee306e5baf38514e6e39215c70a72b
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/manual-approval-gate-controller-rhel8@sha256:2fea7d8e29d70c5893ddb6caf2bf1d4144787f5f0de8739351d2097ed09ee751
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/pipelines-as-code-controller-rhel8@sha256:5d2d12a22a4a9f431233b62a28163a98ddfddd78196a3bc64d9964449873a167
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/pipelines-as-code-webhook-rhel8@sha256:80d46bc5ce8c931af22a97ccbce05b59740e313167c88ad910febcc2f2dc0320
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/pipelines-as-code-watcher-rhel8@sha256:8129e62906c68f04075a44c939375a7bafdeaeac673a20a4fa74ffd6285187ac
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/pipelines-as-code-cli-rhel8@sha256:5d6dd987661a6423e1e70b7ab0f61dbadad7bac404f64868fd32542a4953b8ec
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/operator-operator-rhel8@sha256:dcc79af75401cb53e44781cb23b2b068e6f5b4e8586f970a873f1a0f13d17544
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/operator-operator-rhel8@sha256:dcc79af75401cb53e44781cb23b2b068e6f5b4e8586f970a873f1a0f13d17544
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/operator-proxy-rhel8@sha256:9594cf87fa4d03c287b0c00c199d3c2d024030fa7bd7204b4c5960fd2e6f0491
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/operator-webhook-rhel8@sha256:413e5c42358a192af6453815aa379a10ef7b745ac4ee3d1fd88c145981905c3c
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/git-init-rhel8@sha256:f3e6df07fd86acb91037d55a1970e5f8c6ab12a7517752692c224c7687022812
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/git-init-rhel8@sha256:f3e6df07fd86acb91037d55a1970e5f8c6ab12a7517752692c224c7687022812
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/git-init-rhel8@sha256:f3e6df07fd86acb91037d55a1970e5f8c6ab12a7517752692c224c7687022812
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/git-init-rhel8@sha256:f3e6df07fd86acb91037d55a1970e5f8c6ab12a7517752692c224c7687022812
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/git-init-rhel8@sha256:f3e6df07fd86acb91037d55a1970e5f8c6ab12a7517752692c224c7687022812
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/git-init-rhel8@sha256:f3e6df07fd86acb91037d55a1970e5f8c6ab12a7517752692c224c7687022812
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/console-plugin-rhel8@sha256:92042dcacd4ab0f2a78aab03fd91a9a39d7d7366b5398fd797ecb145acf5fce4
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-16/operator-bundle-rhel8@sha256:650ebe62eed5536c43277aa0f72b072f2be09e05c702cb3a5fa1e85da8c3d35a
