versions:
  current: 5.0.5-868
  previous: 5.0.5-867
  previous_range: 1.20.0
  channel: pipelines-5.0
  openshift:
    latest: 4.20 # lastest GA'ed openshift
    min: 4.12 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-controller-rhel10@sha256:d4f09654cb08a27cc431e53824eb9618cc501a3e31dda2bff7bdbb1c6d4bde70
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-webhook-rhel10@sha256:3b8c2a22fb8c97b6daae7e84920c955081907347983764e75420308853a80713
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-resolvers-rhel10@sha256:16c68bf2958e959bc70f97ea5d66be7743c40f94588ff999757c17a2496f20b5
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-events-rhel10@sha256:14a5995c058298d1aa6bd63cd068e2407f7ca2a56b388d43a5dac14d0870bd29
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-entrypoint-rhel10@sha256:4c665fdd6585814f1c2177c9ee70b7b951545c0d9540c0bc46a4d962745c1db5
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-workingdirinit-rhel10@sha256:60706904f365acbd3cc8341ff524aa8fc455052c1d5e33226ee9059a88d1cdf2
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-nop-rhel10@sha256:56411c014dfd9953a91df1f8e52b06484a0da7f514a6af638bdbe7e76c665089
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-entrypoint-rhel10@sha256:4c665fdd6585814f1c2177c9ee70b7b951545c0d9540c0bc46a4d962745c1db5
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-sidecarlogresults-rhel10@sha256:d05815c83458d7fd2ba76f1e1d3400e9df1c661700b2269cb06c00fd7e0cd9d6
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-controller-rhel10@sha256:364d8ba9f8ade92be9cac0b41b1c456a67ab5a8b00353984d8c29b0fc860ce0c
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-webhook-rhel10@sha256:54c63fba63b871be98e956393f4df2a7585983d8eaea6ba27cdad7473febd54c
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-core-interceptors-rhel10@sha256:e940a7b6c44e698eb048dafd17f7aaa43e0965775479a284d01a12d898c7c98c
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-eventlistenersink-rhel10@sha256:33d30b080fb5ed9884486810a08192a55fcc4b3832c0d0221e4b846d7a654617
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-chains-controller-rhel10@sha256:e071941996059cb6b487172e0ef47556ca55f56db00c7785e33298f9146bd1b1
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-hub-db-migration-rhel10@sha256:320ee8c417b4bd5711cae4e13a9511c353c39a72b844eb77da994832c64607b7
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-hub-api-rhel10@sha256:6b49fdc50c9b93e7ad8f5253c84eb4ba06c220b19f76aadc1bf9f6c320cff7cf
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-hub-ui-rhel10@sha256:0da5a2f385275a660cc5a34bfda4875ac0a0acf9a94dcb259ba6a0559ccda733
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-results-watcher-rhel10@sha256:7d746ad0b9715531966f4b13c0cf1e11fd637d52c5787e3632f842afc33d0398
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-results-api-rhel10@sha256:55238c22687647cf72af76d6a5165be82935f3311d7ee2288afb452b43b990f8
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-results-retention-policy-agent-rhel10@sha256:f440cb051b0bd388c300f77b103cba4b44a8cf6665ecb1cf8354f713082c48d2
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cli-tkn-rhel10@sha256:b30c992214a3954ec63c194f420fca000b616627fa259f88408dadf8121b41c3
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cli-tkn-rhel10@sha256:b30c992214a3954ec63c194f420fca000b616627fa259f88408dadf8121b41c3
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cli-tkn-rhel10@sha256:b30c992214a3954ec63c194f420fca000b616627fa259f88408dadf8121b41c3
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-serve-tkn-cli-rhel10@sha256:0ce5f2603e60684aae8c35a131db9d698519184a0fe638924f75036eb80c3cc2
  - name: IMAGE_ADDONS_TKN_CLI_SERVE_INIT_CONFIG
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-serve-tkn-cli-rhel10@sha256:0ce5f2603e60684aae8c35a131db9d698519184a0fe638924f75036eb80c3cc2
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-manual-approval-gate-webhook-rhel10@sha256:c0e6331aaa01744292b0419b988361f5020047ca4e1f93c280a09f0eb109815c
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-manual-approval-gate-controller-rhel10@sha256:ec9e9967a81df0dc2f0006a340630cd49a5597239f742ade21f03a122b0a527b
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-controller-rhel10@sha256:e21e9cdb17cae1a8202691dedb0f952de400a681832e4c7038d9b58989b415ad
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-webhook-rhel10@sha256:cdae6e64978c0e019f2bc850764a37cbbf4831a68c4e1e3bdd05f15331562a19
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-watcher-rhel10@sha256:5f821f80fe5d999b22884530aafafd8a6e2f4b2bfed368debee5169df96fafac
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-cli-rhel10@sha256:401a217b6b5a45dca471af870a3b5dcc83bcf220f302ba04c8e7c5b9e971c6ac
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-rhel9-operator@sha256:b8051e91ce403611c94dc1441d7fefb4cca60e50c04f2be50b3c8d30e742a263
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-rhel9-operator@sha256:b8051e91ce403611c94dc1441d7fefb4cca60e50c04f2be50b3c8d30e742a263
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-operator-proxy-rhel10@sha256:c28c51d422a5c4889a35101cd13b7c85883fa5f818f6eb36b5e28ab5d14bfd3e
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-operator-webhook-rhel10@sha256:f935e018ae9dc9aca75d75e653d8c445e8a8cb389eba0c03eba34489fb32d256
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cache-rhel10@sha256:627c81b67b6a1905b10ce27dda45d1154879ef794946cdd3554a0e8160480780
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cache-rhel10@sha256:627c81b67b6a1905b10ce27dda45d1154879ef794946cdd3554a0e8160480780
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel10@sha256:1055abc8bdef9baf3243e4cf286258059238325272c91f7804fbcd649088bed9
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel10@sha256:1055abc8bdef9baf3243e4cf286258059238325272c91f7804fbcd649088bed9
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel10@sha256:1055abc8bdef9baf3243e4cf286258059238325272c91f7804fbcd649088bed9
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel10@sha256:1055abc8bdef9baf3243e4cf286258059238325272c91f7804fbcd649088bed9
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel10@sha256:1055abc8bdef9baf3243e4cf286258059238325272c91f7804fbcd649088bed9
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel10@sha256:1055abc8bdef9baf3243e4cf286258059238325272c91f7804fbcd649088bed9
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-console-plugin-rhel10@sha256:809feee86cb52a0f9b5aaaf15bf7274bc709f445d680e8856d199c92c83216a5
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN_LEGACY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-console-plugin-pf5-rhel10@sha256:9594260c0bd85a54b8f42dc26bcf25ee9c67b94dcd585c26d757ca5ab889d11c
  # OPC
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-opc-rhel10@sha256:e720b46f2cf7efa55daf5da307d52fa1e10e2cd65a9c4f5973336f29ceb1114e
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pruner-controller-rhel10@sha256:45dbfcd8013a06e3801f8bd51ce7dbd08c2d0ffd6de0b0cd74a7ea4f384a35a3
  - name: IMAGE_PRUNER_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pruner-webhook-rhel10@sha256:c91d97e27fd760938607d8d182bbb2dd06e2a56a203890a1d3c60e35e00d56e6
  # Kueue
  - name: IMAGE_KUEUE_MANAGER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-scheduler-rhel10@sha256:8852645378685602a6a2d4a4e1db79bb2af1e66d4d02ad9f45e59ca1f8030a06
  - name: IMAGE_KUEUE_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-scheduler-rhel10@sha256:8852645378685602a6a2d4a4e1db79bb2af1e66d4d02ad9f45e59ca1f8030a06
  #multicluster proxy aae
  - name: IMAGE_MULTICLUSTERPROXYAAE_PROXY_AAE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-multicluster-proxy-aae-rhel10@sha256:66f9b9f8a71d4d91045096de015f85c17631346cfce59de57be92cda8f0c7ac6
  #Syncer Service Workload Controller
  - name: IMAGE_SYNCER_SERVICE_WORKLOAD_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-syncer-service-rhel10@sha256:218a12c8c187d17c0f3b5987587113665f9431d20f4fd99ae455a942f3b84032
