versions:
  current: 1.21.0
  previous: 1.20.1
  previous_range: 1.20.0
  channel: pipelines-1.21
  openshift:
    latest: 4.20 # lastest GA'ed openshift
    min: 4.14 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-controller-rhel9@sha256:5421eab93f46a35eb1bdf7209f941a34844cc8d953e5049e998c450bf3f1b393
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-webhook-rhel9@sha256:177ef7f2c302092482e0793861b32ae5012c1825dbc55bbf5f9065ef0459b0bc
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-resolvers-rhel9@sha256:6863ac71e0a349159eafc22d7a7dfe946848a58250154785ec3b870cff4a7ad8
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-events-rhel9@sha256:d7f69fe5267f7a639ac946be7d932e634d0eef30f2cfa2f0aaf33cdf45fbbf4d
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-entrypoint-rhel9@sha256:61453a89cd50892d31481be8c65e66a688e15f537fbb0d7fd9ef4f4ffecb672e
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-workingdirinit-rhel9@sha256:c1bf784d904ae03f52ab2b402b28b87339f051218abfdd0184e38ebc519dca32
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-nop-rhel9@sha256:5b0e1351bb1ed26846ac4eceae47ea0e4e371dbe0be001a0d24496f9e2adbabb
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-entrypoint-rhel9@sha256:61453a89cd50892d31481be8c65e66a688e15f537fbb0d7fd9ef4f4ffecb672e
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipeline-sidecarlogresults-rhel9@sha256:de8507ac84c5833a04ebe3c11ce74bb627e6243166c670676d870667ae2c9cfc
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/triggers-controller-rhel9@sha256:3686690bd6990aaabff551182d4011c52710b9f3b85ec2c90b0c384f5a52b1f4
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/triggers-webhook-rhel9@sha256:9da732aefd209a9bcf5a763358ef5ad4ad55a5d1f297217f9f33b85550f699f5
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/triggers-core-interceptors-rhel9@sha256:9b58809450ff0a0f095302c07604bc03996cb15a513bc5c9c376b1ee3aade06c
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/triggers-eventlistenersink-rhel9@sha256:6ddcd2bc594df131a83ed30bc42c7cc5999f36cb68bae1cb33f2b81671364a2f
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/chains-controller-rhel9@sha256:08123c8c80f006681df63b13319a018af29678d2deb0ff60ae502481f5c710cd
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/hub-db-migration-rhel9@sha256:5de8d815750dffe53e91037c074bdc69d4cc0cd6ad456882b059369c2b704450
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/hub-api-rhel9@sha256:962830aca1f9dd0cf38d918013cc10b5401600a9247e7ac473ac7ec54c27c3c7
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/hub-ui-rhel9@sha256:c8cbcbab53cca547862903820ba5ad30f6309a240c002540087c199753f4150e
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/results-watcher-rhel9@sha256:781b22ef1397973a67b25e3320c0a52764f40e428ebbf37654b44b1a955dcfb5
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/results-api-rhel9@sha256:54a7d13a0d6c1e285b7df40336c2b95ca916f3c759bb9f8055e017074ad8f967
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/results-retention-policy-agent-rhel9@sha256:d72db7158a6731c166237d7bd99fbde608f49904f181d8a3301ee9e67b8292ff
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cli-tkn-rhel9@sha256:cb2868fd0827b2d6dd3eff877a743c04573df10aaa70ee9fb538becc0032bf7d
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cli-tkn-rhel9@sha256:cb2868fd0827b2d6dd3eff877a743c04573df10aaa70ee9fb538becc0032bf7d
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cli-tkn-rhel9@sha256:cb2868fd0827b2d6dd3eff877a743c04573df10aaa70ee9fb538becc0032bf7d
  - name: IMAGE_ADDONS_TKN_CLI_SERVE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/serve-tkn-cli-rhel9@sha256:40592fa7c65cd2a6a2f40655b147e8d9563b23fef8389b0be525e66d3d717831
  - name: IMAGE_ADDONS_TKN_CLI_SERVE_INIT_CONFIG
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/serve-tkn-cli-rhel9@sha256:40592fa7c65cd2a6a2f40655b147e8d9563b23fef8389b0be525e66d3d717831
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/manual-approval-gate-webhook-rhel9@sha256:bb7f8815aa0e7fd0a197cf44ce9b754abf2af953a6baa916c96e35011fdb4182
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/manual-approval-gate-controller-rhel9@sha256:2431521236629eb9468c78af63c8cea3c5ae4d02d675312f0a6bad7e2e26d1d5
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipelines-as-code-controller-rhel9@sha256:32ab577b0d828f42adae3f4f4388f45c6885ae6d4391e10fbd15c1ced65906ba
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipelines-as-code-webhook-rhel9@sha256:41c490abcde0248bc6ca343ddc5d11a0000087a39a3019e12955737ab455fba7
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipelines-as-code-watcher-rhel9@sha256:771b9d95003a9d07acc18e3385927ab6892e1e4b0678f9c04d0ed65591963b1d
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pipelines-as-code-cli-rhel9@sha256:cac0084a09a5d5fa3b1430e6b2beda485cf33e167fc7fa955a0ef457db299ab9
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-operator-rhel9@sha256:acf3090c9dbb5dce66535f25b8c4a42bae804b46cfd92e20922ccf44b0120511
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-operator-rhel9@sha256:acf3090c9dbb5dce66535f25b8c4a42bae804b46cfd92e20922ccf44b0120511
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-proxy-rhel9@sha256:70f010583bd9d930317813e69a43c6a675bb693e818d0ef5065dacff7edd53d8
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-webhook-rhel9@sha256:6bf5714c7b9bcc0abd65045c71570c8d6291e5a802d213b10c54096346cee603
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cache-rhel9@sha256:ee97ac03ca8a83f2a822a98dce0a375af4d7d7f0d5233e2215557af0f25e65be
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/cache-rhel9@sha256:ee97ac03ca8a83f2a822a98dce0a375af4d7d7f0d5233e2215557af0f25e65be
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:a2e044491e6e66ddcd50d1bf2c921ddf0e8f250c92dbeb9e6f6bfb9aa5a8b476
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:a2e044491e6e66ddcd50d1bf2c921ddf0e8f250c92dbeb9e6f6bfb9aa5a8b476
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:a2e044491e6e66ddcd50d1bf2c921ddf0e8f250c92dbeb9e6f6bfb9aa5a8b476
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:a2e044491e6e66ddcd50d1bf2c921ddf0e8f250c92dbeb9e6f6bfb9aa5a8b476
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:a2e044491e6e66ddcd50d1bf2c921ddf0e8f250c92dbeb9e6f6bfb9aa5a8b476
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/git-init-rhel9@sha256:a2e044491e6e66ddcd50d1bf2c921ddf0e8f250c92dbeb9e6f6bfb9aa5a8b476
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/console-plugin-rhel9@sha256:d96e4409573ab23b4d0bdf1f16174e9d9637f26c26763640325c3e88715cc89b
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/operator-bundle-rhel9@sha256:64b8060d972f65f6c82ffc1532bdb9c3c11486cc2e74cf4151f16b25d30c7b1c
  # opc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/opc-rhel9@sha256:91a82639d5e5c7da45b7cc8f862d1a9781686547c6676bf5d6f3016bb81bf6dd
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pruner-controller-rhel9@sha256:87eb7d3805476035e98bba2499b439777767e46bc5327164c7a38ab034c26ecb
  - name: IMAGE_PRUNER_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-21/pruner-webhook-rhel9@sha256:03eb7adeaf60ffa0cd966e7bbef1d11f9c5ccabe140b1e7271437b56b74cb6e0
