versions:
  current: 1.18.0
  previous: 1.17.1
  previous_range: 1.17.0
  channel: pipelines-1.18
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.15 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-controller-rhel9@sha256:4799884fcf1edf09954d0d278bf726ff4e4a30cf84f9d1b1dc2c078bc01f6154
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-webhook-rhel9@sha256:e4842ed74ad57fa09f292b9600efa1ead65fd74149bfd756daaaf56bb971413d
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-resolvers-rhel9@sha256:c674dcacd4ff3f6769773708a6f54fd8e21349f6a0660df6225327415af0e7ed
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-events-rhel9@sha256:ccba273e1e8431dae1df8b200c637b9de4162f6c195eb8949a996742f54e0a3a
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-entrypoint-rhel9@sha256:20258e7b1dc3d9bd3386bc3569b11952b9fd72c6efc75f992d2fbca1f648d1d0
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-workingdirinit-rhel9@sha256:78fa74448ff0de1beab8a927c64722ac636d407893c24e9b2da654faa046605d
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-nop-rhel9@sha256:19ef8b61c1fb394c60378e54ffece84ee23e0c3c8b2d72ebff4e826e567dc042
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-entrypoint-rhel9@sha256:20258e7b1dc3d9bd3386bc3569b11952b9fd72c6efc75f992d2fbca1f648d1d0
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-sidecarlogresults-rhel9@sha256:4a750ec108033fc0df5c13e9205018b5b3bd174d23bc2ffeaf9e16043f8f2cf4
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/triggers-controller-rhel9@sha256:6716df356f1c4d412eb210eb6a379b7d6535a320ee4af189998abf762064aba0
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/triggers-webhook-rhel9@sha256:18f13d36a3b6ee45909df9061dfc1c4c6dc8c166e648270da5457499c58b4793
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/triggers-core-interceptors-rhel9@sha256:d4adf21adf9aff676c9d3f1cbfab1d6bb2782a9c1b29cf5454d361b983d79d94
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/triggers-eventlistenersink-rhel9@sha256:fcdbdd5d770ad00a8a869f11662ad38bbc43641271f389bef4c1147e748b5cbe
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/chains-controller-rhel9@sha256:2595a86cb4837430c4ff87575357f6f9acfe68d75d7c24c115cd23c37446124f
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/hub-db-migration-rhel9@sha256:d0700e9cf7995d1351b0027d7694030d2f23f76250d6cd0d35918c098c3ce4f0
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/hub-api-rhel9@sha256:c9461040f49b5c2c462d76e378a0a3238e924fc51c33c7632bba6671986d768e
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/hub-ui-rhel9@sha256:3a62b233c05f3662222c9cbf94e4e012164e1d6cc0e8c8ec5d52617ff53f33ca
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/results-watcher-rhel9@sha256:fd0c16e29734d91cc23752608adba3880e1b3209636a895bef2229dfd1f6ac60
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/results-api-rhel9@sha256:29a664124b18e2f924c4c42213d2f5e35a2596e4ecac276b8fb27794cf66c621
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/results-retention-policy-agent-rhel9@sha256:dc275d2e3d57dbaf092f2b1dc2d80806bf7e0d3b8f5774da58b5f9c68877d82e
  - name: IMAGE_RESULTS_POSTGRES
    value: registry.redhat.io/rhel9/postgresql-13@sha256:36647bd6d50d2e0e9c99ecf190bd515577c7ce9476e49d927c4d4065011e3441
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cli-tkn-rhel9@sha256:3d1dbad31e7425a26ba6442d2e582a9215a4f2dba91c810c1a81e844ca6b824a
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cli-tkn-rhel9@sha256:3d1dbad31e7425a26ba6442d2e582a9215a4f2dba91c810c1a81e844ca6b824a
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cli-tkn-rhel9@sha256:3d1dbad31e7425a26ba6442d2e582a9215a4f2dba91c810c1a81e844ca6b824a
  - name: IMAGE_ADDONS_TKN_CLI_SERVE
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:d055d2b35a663aef3e1aafdbed0b12957867c0670c946ebae66e9c44a768bda2
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/manual-approval-gate-webhook-rhel9@sha256:f2b741e1385604274020cf7f6855ff7ee13bc513d59cce0b7ebcf3590e54178c
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/manual-approval-gate-controller-rhel9@sha256:11bd27fcae01cf1ce8c4f04c029a583ee929c5da25e67d1d589e18d8f518b1a0
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipelines-as-code-controller-rhel9@sha256:caf5c1668fcd23335c40be79623d02f2d228850e6be19265dd27d6e6d78d8fb6
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipelines-as-code-webhook-rhel9@sha256:d8ecdd7a33f5148c9034fd5c219a125b9b6908d56468cbb297fe8ec17ba0fef0
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipelines-as-code-watcher-rhel9@sha256:6625551114447d2a67fd9cf36ebea68d130132ce28ccb46e53e8cd90e65fe5b2
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipelines-as-code-cli-rhel9@sha256:0dea9431af9e30e302711818116b1cb42b4f541ccec6be155a00eafb743900c4
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-operator-rhel9@sha256:8420e92b5cc69d5314bc2ec715e5cfd3b8862faa333ef604c53157a9774b798f
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-operator-rhel9@sha256:8420e92b5cc69d5314bc2ec715e5cfd3b8862faa333ef604c53157a9774b798f
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-proxy-rhel9@sha256:08e16bd1724f2ea542b3569d101cc3568ff9b0173fdfaa4360c4224fc6f555d3
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-webhook-rhel9@sha256:eb08887b8dade2eabca441bdd4edb0b11536918f2a8cfd2466c9bc2c136d0cd8
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cache-rhel9@sha256:eb423e6d74e69c60a403d2497b7fd9c9b0783f7400de2f88077434114ac8955e
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cache-rhel9@sha256:eb423e6d74e69c60a403d2497b7fd9c9b0783f7400de2f88077434114ac8955e
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:5ae94449dff62c187f237b37b851f21b92fd948b926cabff589b2d7ddd37f2f4
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:5ae94449dff62c187f237b37b851f21b92fd948b926cabff589b2d7ddd37f2f4
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:5ae94449dff62c187f237b37b851f21b92fd948b926cabff589b2d7ddd37f2f4
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:5ae94449dff62c187f237b37b851f21b92fd948b926cabff589b2d7ddd37f2f4
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:5ae94449dff62c187f237b37b851f21b92fd948b926cabff589b2d7ddd37f2f4
  - name: IMAGE_ADDONS_KN
    value: registry.redhat.io/openshift-serverless-1/kn-client-kn-rhel8@sha256:d21cc7e094aa46ba7f6ea717a3d7927da489024a46a6c1224c0b3c5834dcb7a6
  - name: IMAGE_ADDONS_PARAM_KN_IMAGE
    value: registry.redhat.io/openshift-serverless-1/kn-client-kn-rhel8@sha256:d21cc7e094aa46ba7f6ea717a3d7927da489024a46a6c1224c0b3c5834dcb7a6
  - name: IMAGE_ADDONS_SKOPEO_RESULTS
    value: registry.redhat.io/rhel9/skopeo@sha256:993f799d58c48151ecae7a84e63860f6c0039e8e18efed5ad67e7752f4b7e408
  - name: IMAGE_ADDONS_SKOPEO_COPY
    value: registry.redhat.io/rhel9/skopeo@sha256:993f799d58c48151ecae7a84e63860f6c0039e8e18efed5ad67e7752f4b7e408
  - name: IMAGE_ADDONS_BUILD
    value: registry.redhat.io/rhel9/buildah@sha256:a6e04c061b8d261dba85d01dcb64d3f7dba8c0b9765e03f05ec79850a248d75a
  - name: IMAGE_ADDONS_S2I_BUILD
    value: registry.redhat.io/rhel9/buildah@sha256:a6e04c061b8d261dba85d01dcb64d3f7dba8c0b9765e03f05ec79850a248d75a
  - name: IMAGE_ADDONS_PARAM_BUILDER_IMAGE
    value: registry.redhat.io/rhel9/buildah@sha256:a6e04c061b8d261dba85d01dcb64d3f7dba8c0b9765e03f05ec79850a248d75a
  - name: IMAGE_ADDONS_S2I_GENERATE
    value: registry.redhat.io/source-to-image/source-to-image-rhel8@sha256:3696cf724ce7865626ae408d82fd87727c741e4d3eb3475c271ec6d56f0882a4
  - name: IMAGE_ADDONS_GEN_ENV_FILE
    value: registry.redhat.io/source-to-image/source-to-image-rhel8@sha256:3696cf724ce7865626ae408d82fd87727c741e4d3eb3475c271ec6d56f0882a4
  - name: IMAGE_ADDONS_GENERATE
    value: registry.redhat.io/source-to-image/source-to-image-rhel8@sha256:3696cf724ce7865626ae408d82fd87727c741e4d3eb3475c271ec6d56f0882a4        
  - name: IMAGE_ADDONS_LOAD_SCRIPTS
    value: registry.redhat.io/ubi9/ubi-minimal@sha256:bafd57451de2daa71ed301b277d49bd120b474ed438367f087eac0b885a668dc
  - name: IMAGE_ADDONS_MAVEN_GENERATE
    value: registry.redhat.io/ubi9/ubi-minimal@sha256:bafd57451de2daa71ed301b277d49bd120b474ed438367f087eac0b885a668dc
  - name: IMAGE_ADDONS_PREPARE
    value: registry.redhat.io/ubi9/ubi-minimal@sha256:bafd57451de2daa71ed301b277d49bd120b474ed438367f087eac0b885a668dc
  - name: IMAGE_ADDONS_MVN_SETTINGS
    value: registry.redhat.io/ubi9/ubi-minimal@sha256:bafd57451de2daa71ed301b277d49bd120b474ed438367f087eac0b885a668dc
  - name: IMAGE_ADDONS_MAVEN_GOALS
    value: registry.redhat.io/ubi9/openjdk-17@sha256:cdbd64ba1b7826d09bc180fa19aa6fbc09ddb5bff5e02b7e1351353bbabebb78
  - name: IMAGE_ADDONS_PARAM_MAVEN_IMAGE
    value: registry.redhat.io/ubi9/openjdk-17@sha256:cdbd64ba1b7826d09bc180fa19aa6fbc09ddb5bff5e02b7e1351353bbabebb78
  - name: IMAGE_HUB_TEKTON_HUB_DB
    value: registry.redhat.io/rhel9/postgresql-13@sha256:36647bd6d50d2e0e9c99ecf190bd515577c7ce9476e49d927c4d4065011e3441
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/console-plugin-rhel9@sha256:d37c28b1aaae82e81d26032658aefcf916c3cbbbd1207dec17e7dac176114b10
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-bundle-rhel9@sha256:4771639859de0270c053f29e6e33ec47de6e2bf6e715833d0c635aa04ff91738
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:5ae94449dff62c187f237b37b851f21b92fd948b926cabff589b2d7ddd37f2f4
