versions:
  current: 5.0.5-479
  previous: 5.0.5-478
  previous_range: 1.16.0
  channel: pipelines-5.0
  openshift:
    latest: 4.17 # lastest GA'ed openshift
    min: 4.16    # Minimum version OSP supports
images:
# tektoncd-pipeline
- name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/controller@sha256:724b4dca50d2d99147510c6a6f8eb6db7b737094df32c5de95a395d6bed590e7
- name: IMAGE_PIPELINES_WEBHOOK
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/webhook@sha256:3bae6d5007850d59f059c8b441668c2495c4346d55231b5d77bbc35e0f0779ab
- name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/resolvers@sha256:f7cb0e53130094f1fd6c065069e3c64505f9c4a031fc543ae334c2c6fa859565
- name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/events@sha256:372f4bfc50b9800294c96880052c4aa0c1422b4a0d62fe59f80740a24f61ed45
- name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/entrypoint@sha256:fc5ffd9f32b2ed36c4fca4a11e6c1711346df8356fe18738ba97e613da56a35f
- name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/workingdirinit@sha256:96ea351a0a499bd28d852f6cf7f12c40515e0c3dcf8a77e25e2d2a31a793e0ef
- name: IMAGE_PIPELINES_ARG__NOP_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/nop@sha256:6b810f779b28464e6a7c7c6776c5bb56528ba57a6c7588b9041f4773c60e75fa
- name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/entrypoint@sha256:fc5ffd9f32b2ed36c4fca4a11e6c1711346df8356fe18738ba97e613da56a35f
# tektoncd-triggers
- name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-main/controller@sha256:f510e05cd8d7ac1d315f389869ec8e4e1b221ad85d7d682f375327c35125e731
- name: IMAGE_TRIGGERS_WEBHOOK
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-main/webhook@sha256:d3eb7d1669bbb7c1676c6e1311c712742f13c8060f36c35c37ac0572f0901e25
- name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-main/core-interceptors@sha256:07fcfec6d4cd475806e91244f261c225d19f7b364b98d55abf811799df7d9b4a
- name: IMAGE_TRIGGERS_ARG__EL_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-main/eventlistenersink@sha256:967c46eb620736f51267b46b15944ff27f2ad23c5276fe6d8660fc2da0ee5756
# tektoncd-chains
- name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-chains-main/controller@sha256:030fe6b1daa979479aaa9cc43b34fced7b74d9283ceb2889843a6842db898a95
# tektoncd-hub
- name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-hub-main/db-migration@sha256:db7cbb324c6925bb0af1f8c3ec0dd9b800e7a71aee2dac14ad0835528c13d3e3
- name: IMAGE_HUB_TEKTON_HUB_API
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-hub-main/hub-api@sha256:4f614c4f843f20669cd047046e91351304c9c90e05775ab5f0d9ab6950867a0d
- name: IMAGE_HUB_TEKTON_HUB_UI
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-hub-main/hub-ui@sha256:8fdc88542c6b613bb09e2e709d99e94de76b09d5d511b965e5e268f4e7c430cc
# tektoncd-results
- name: IMAGE_RESULTS_WATCHER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-results-main/watcher@sha256:85d472af9437cc1553f1521ef550246cfef368132b61ef0fd01fbe96b4e6f577
- name: IMAGE_RESULTS_API
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-results-main/api@sha256:85d472af9437cc1553f1521ef550246cfef368132b61ef0fd01fbe96b4e6f577
- name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-results-main/retention-policy-agent@sha256:85d472af9437cc1553f1521ef550246cfef368132b61ef0fd01fbe96b4e6f577
- name: IMAGE_RESULTS_POSTGRES
  value: registry.redhat.io/rhel8/postgresql-13@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
# tektoncd-cli
- name: IMAGE_JOB_PRUNER_TKN
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-main/tkn@sha256:f5736dd54cd9eeba5831aaa370e74dfabd5e8da5e16ea1c3d3952ef80fb255dd
- name: IMAGE_ADDONS_PARAM_TKN_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-main/tkn@sha256:f5736dd54cd9eeba5831aaa370e74dfabd5e8da5e16ea1c3d3952ef80fb255dd
- name: IMAGE_ADDONS_TKN
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-main/tkn@sha256:f5736dd54cd9eeba5831aaa370e74dfabd5e8da5e16ea1c3d3952ef80fb255dd
- name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
  # value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-main/serve-tkn@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
  value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel8@sha256:cc5234d6a6afc213d24786253c8ea70bb77f3f5c3e1ea1526debb8a1776e4ffc
# manual-approval-gate
- name: IMAGE_MAG_MANUAL_APPROVAL
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/manual-approval-gate-main/webhook@sha256:7d66504c9038d6cd776522ad711d139522082d4127bfdaa1aad1a06cf7e2dda6
- name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/manual-approval-gate-main/controller@sha256:47e258ca9f6e4fef52480d74c24e36343a318ba1f61614cceb0f303dc7e1c2cc
# pipelines-as-code
- name: IMAGE_PAC_PAC_CONTROLLER
  value: quay.io/openshift-pipeline/openshift-pipelines-pipelines-as-code:1.16
- name: IMAGE_PAC_PAC_WEBHOOK
  value: quay.io/openshift-pipeline/openshift-pipelines-pipelines-as-code:1.16
- name: IMAGE_PAC_PAC_WATCHER
  value: quay.io/openshift-pipeline/openshift-pipelines-pipelines-as-code:1.16
# operator
- name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/operator@sha256:884809d7f36f9039cd9cc10f951b26429d71ab1e5d0a56595ba64820c08bb629
- name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/operator@sha256:884809d7f36f9039cd9cc10f951b26429d71ab1e5d0a56595ba64820c08bb629
- name: IMAGE_PIPELINES_PROXY
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/proxy@sha256:8a44f753b029e139440c1bfa0d3cbbf2b98ebdd20d2fd14b5cc8b5337380d911
- name: TEKTON_OPERATOR_WEBHOOK
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/webhook@sha256:099dc6734fa7ed6023a8b2b186d62db0bc3a8f359bd1dac491c7af0236e840d1
# Addons
- name: IMAGE_PIPELINES_ARG__GIT_IMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
- name: IMAGE_ADDONS_PARAM_GITINITIMAGE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
- name: IMAGE_ADDONS_GIT_RUN
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
- name: IMAGE_ADDONS_REPORT
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
- name: IMAGE_ADDONS_GIT_CLONE
  value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images/git-init@sha256:30e4dd2f4907c1602769a7347080db3b96b527cb13a7ef696b8d6b388b783e4f
- name: IMAGE_ADDONS_KN
  value: registry.redhat.io/openshift-serverless-1/client-kn-rhel8@sha256:a5a7b2be50f211d4d9d555b2a2e2302096c139ff5011d984cc386f1530007f16
- name: IMAGE_ADDONS_SKOPEO_RESULTS
  value: registry.redhat.io/rhel8/skopeo@sha256:1dcb4189c92da21ee58b3ca5433615e0208194c8412f7f1fb45fa491179aaf9b
- name: IMAGE_ADDONS_BUILD
  value: registry.redhat.io/rhel8/buildah@sha256:5c7cd7c9a3d49e8905fc98693f6da605aeafae36bde5622dc78e12f31db3cd59
- name: IMAGE_ADDONS_S2I_BUILD
  value: registry.redhat.io/rhel8/buildah@sha256:5c7cd7c9a3d49e8905fc98693f6da605aeafae36bde5622dc78e12f31db3cd59
- name: IMAGE_ADDONS_S2I_GENERATE
  value: registry.redhat.io/source-to-image/source-to-image-rhel8@sha256:6a6025914296a62fdf2092c3a40011bd9b966a6806b094d51eec5e1bd5026ef4
- name: IMAGE_ADDONS_LOAD_SCRIPTS
  value: registry.redhat.io/ubi8/ubi-minimal@sha256:a47c89f02b39a98290f88204ed3d162845db0a0c464b319c2596cfd1e94b444e
- name: IMAGE_ADDONS_MAVEN_GENERATE
  value: registry.redhat.io/ubi8/ubi-minimal@sha256:a47c89f02b39a98290f88204ed3d162845db0a0c464b319c2596cfd1e94b444e
- name: IMAGE_ADDONS_PREPARE
  value: registry.redhat.io/ubi8/ubi-minimal@sha256:a47c89f02b39a98290f88204ed3d162845db0a0c464b319c2596cfd1e94b444e
- name: IMAGE_ADDONS_MAVEN_GOALS
  value: registry.redhat.io/ubi8/openjdk-17@sha256:632e78989471859ca4ed1148b951a911f7e3b6e6516482be20967c4171612c55
