versions:
  current: 5.0.5-594
  previous: 5.0.5-593
  previous_range: 1.18.0
  channel: pipelines-5.0
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.15 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-controller-rhel9@sha256:08ad951b165686b12f84dc1aad4b0bc3af73b5e26b34750bfeac6442cd23d74e
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-webhook-rhel9@sha256:26c76e5a6a5ebe8121b449387c4a178a2f0121f4385ee10940dfa18aac9789cb
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-resolvers-rhel9@sha256:a344a9a4406b6c1f94da1f33cd39e2711aa4c44d861e1d11e6ef6e781de63443
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-events-rhel9@sha256:bd1718d847cb37a6880e0956df066a01067fad0573a6b26f317654b0b647a898
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:f06c6629a56243f04c07e0d9d73c601305bfd4129db22cbc43e9d258c13da298
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-workingdirinit-rhel9@sha256:95301f409459e72c34c8a6295fae3e1b04996ae1854f080b1b4bf28eb6f22fed
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-nop-rhel9@sha256:7514870c08a6890b43356ba077e775ad3d783fbd1acaf4f08c8b8c80d09667e0
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-entrypoint-rhel9@sha256:f06c6629a56243f04c07e0d9d73c601305bfd4129db22cbc43e9d258c13da298
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipeline-sidecarlogresults-rhel9@sha256:c42a4db5d9ef0087fe62ff0746e20dcbe62642867c6c420c3b70403cd72d713f
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-controller-rhel9@sha256:42ba426b189c08e0fca6b6239d76f5dc75ee160626d05ded19d3062ee3b62f69
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-webhook-rhel9@sha256:8e64fa62f96fe3064fcf768cc14100136bcfeaa22b2ac3d77bd8277ff63f4ff0
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-core-interceptors-rhel9@sha256:9214dac912d7fba70c0873a2446a2092b4c63413bc08e7ff770b7d34c3a75c54
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/triggers-eventlistenersink-rhel9@sha256:75ea05780ac894e7657e921bb512695cc2e8e142e329efc8468f5d47d02883cf
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/chains-controller-rhel9@sha256:20038e2bb5ef012c6cc9c3ac1c8ec823189734f9c81e7afc5c9ce124d26eef67
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-db-migration-rhel9@sha256:b23691aa8e14efd692b487c3b12cd96efb50851263b8e0bc172e99e739787476
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-api-rhel9@sha256:ea9dc2c55288f780ceb4f1ef4f0d9c682153cba53f2c928078512af9dc125b35
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/hub-ui-rhel9@sha256:4ca6899b7ad161ee8fbe09900b98c5112b50f8cc1e08fc80f9210ee0276def17
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-watcher-rhel9@sha256:e51bae74c26aefadccbba431ef047383022d2fb3ac4c528b2e5dbf066ff77332
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-api-rhel9@sha256:e267419bcdb96a31fabdc099628998db39f6862e30f666d00a60b850deb309a7
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/results-retention-policy-agent-rhel9@sha256:96a3a57a0f26b2336919a8103d3d37ac1336c8b5bf936b359290ca53c494e0b6
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:3a479ae6d3eaba68d0f206e92d6dbf9c061b422519ffbaf54086aa84676b541b
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:3a479ae6d3eaba68d0f206e92d6dbf9c061b422519ffbaf54086aa84676b541b
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cli-tkn-rhel9@sha256:3a479ae6d3eaba68d0f206e92d6dbf9c061b422519ffbaf54086aa84676b541b
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:d055d2b35a663aef3e1aafdbed0b12957867c0670c946ebae66e9c44a768bda2
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-webhook-rhel9@sha256:7cf31108549190c3b3b7d1c83d906be5f51614f9bf65d5fe7b3a3f93244d7843
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/manual-approval-gate-controller-rhel9@sha256:a398b4a7fd7b5d8b7eaf171bfd2f061d90d7c8287cb3ab171ccbfeeed5efa9d6
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-controller-rhel9@sha256:3ff0097701fc6e1de5edda5f7c0066249273bcd705aec77d7c5dfa521648b89f
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-webhook-rhel9@sha256:82481553caebddde61c6c1adb61306f17fd104cd126a02f095704b563c55c5d1
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-watcher-rhel9@sha256:66f8c53b9c4d6afc2af8d4ea84e530b5339a9f17bb9266bec4e48ed576fc0598
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pipelines-as-code-cli-rhel9@sha256:d8c565bfea2edc4f6b3af935b38635d679d8c9ca5127823a9e14081f4ede150c
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:b6e3a51eb3235bd17da14206df0c3ea4101fd81336fae92ee95f09d40dfe9638
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-operator-rhel9@sha256:b6e3a51eb3235bd17da14206df0c3ea4101fd81336fae92ee95f09d40dfe9638
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-proxy-rhel9@sha256:977fd2d48245db7285e4e65e8944d1c127975bb4446c62934bd34e3f3d62618d
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-webhook-rhel9@sha256:adc010c520645982b711031d300c3905291a3c3ab5344fd54397832ace672ded
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:8befdc7866ba645c00133d7aef46ba782772d529af28a18604ea97e0cd4d6e94
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/cache-rhel9@sha256:8befdc7866ba645c00133d7aef46ba782772d529af28a18604ea97e0cd4d6e94
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:7eee14366c516d92cf7480c9bc256cf0e544bf06da5d46ffb5e8bfe3e448326c
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:7eee14366c516d92cf7480c9bc256cf0e544bf06da5d46ffb5e8bfe3e448326c
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:7eee14366c516d92cf7480c9bc256cf0e544bf06da5d46ffb5e8bfe3e448326c
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:7eee14366c516d92cf7480c9bc256cf0e544bf06da5d46ffb5e8bfe3e448326c
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:7eee14366c516d92cf7480c9bc256cf0e544bf06da5d46ffb5e8bfe3e448326c
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/git-init-rhel9@sha256:7eee14366c516d92cf7480c9bc256cf0e544bf06da5d46ffb5e8bfe3e448326c
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/console-plugin-rhel9@sha256:4bec53cb6db4e6b5eb1668af71e32ffc22d83837435e8d80011c212f59f6a543
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/operator-bundle-rhel9@sha256:a64325578085d3a3ecb188343c7491f98d2bc3c06d932d7aa990d87a13ee772d
  # opc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/opc-rhel9@sha256:5f79a3b1348060c478c5b24841b1f1b4e633175caa513ef904a95cf50c5d5b8d
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-19/pruner-controller-rhel9@sha256:0f16301424f4a0ffcc498cb08fa45cd495bb663382e30132744754da0dc61c43
