versions:
  current: 1.22.0
  previous: 1.21.0
  previous_range: 1.21.0
  channel: pipelines-1.22
  openshift:
    latest: 4.20 # lastest GA'ed openshift
    min: 4.16 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-controller-rhel9@sha256:69f76d67931f30f135857d6b64f61c1f8263c900eebf2f2ec103950756dd035d
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-webhook-rhel9@sha256:c476fa92661fe1f51f4d3d8f7d0a49fc33a0f90c407200c61a200e6faf4e3f68
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-resolvers-rhel9@sha256:c21b1b71725732db1fff177fbf82cdf93f054b6ed561d91f6b2dc75c12129a8d
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-events-rhel9@sha256:368aa1484d972f4482913f0853d3896edee0bf672bfe32e9abb321d1abdedf80
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-entrypoint-rhel9@sha256:0ff0165cf1b7fef424f1e6208b0f7a242db3cf45ee6224d574d5ec449b392341
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-workingdirinit-rhel9@sha256:a3d85e1b436cb84e98988490c1fdf71e3314891858b542ddd4735e3ba7f62616
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-nop-rhel9@sha256:aaefffc3204b344b7d9a938ba3eb30e88ffc3084c5ea8e5807a229fe28f50d20
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-entrypoint-rhel9@sha256:0ff0165cf1b7fef424f1e6208b0f7a242db3cf45ee6224d574d5ec449b392341
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-sidecarlogresults-rhel9@sha256:f4a8edfe8c552ce83fb16861f2a3e505a94ff4ea5643def386c9c9216ce8068a
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-controller-rhel9@sha256:27965a61052d86d7526a039f72b65b0319c9717a76fc3c5415a2e3170cd1044a
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-webhook-rhel9@sha256:bf1645bb1be8514f5a7ba2831ed81c544d65287be51dc05e968d44cbf2b2e72a
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-core-interceptors-rhel9@sha256:31893ae633e06fb808ae5cf5f1956aa952bd30888a2ed46de95588b2f213fffe
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-eventlistenersink-rhel9@sha256:73ab82b2769bd91b14107a00ba0f995640ce61358f7f14cfc5f4b62bdcca3cd0
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-chains-controller-rhel9@sha256:4ded8f48d67ad5f2662f81fcc1f4d4d065343527b499fa215453436dec67c212
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-hub-db-migration-rhel9@sha256:e29fa8d4bb0a85e50702052e3b7e41b3765fb80695438f949d0c96bb3e2921cd
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-hub-api-rhel9@sha256:46d8a410b37c8be1e05582591aa8ac53fc2ace47195c68136ecfacd791a6803f
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-hub-ui-rhel9@sha256:52bee3bca2ef3550761c8fe19ff99765ecceb08c7de7adcde1aa705c1e9d7338
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-results-watcher-rhel9@sha256:aa6be9062f60bf86b5ef4d69eafa4f377dc9cedbac77a6150de5c1d7c7bde25b
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-results-api-rhel9@sha256:ae5c5e1aa22e8112bcff348fff6e1f4ead9df523d244012994a7292e69a48768
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-results-retention-policy-agent-rhel9@sha256:236dc451d7059b0a6d95d29f8371f9dbde98816d9203fdfd3221c632e980dc1c
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cli-tkn-rhel9@sha256:58bbf82fcc6569a26265a5cdf13f682842cd477fbac1a920a6abb40970e1b5b6
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cli-tkn-rhel9@sha256:58bbf82fcc6569a26265a5cdf13f682842cd477fbac1a920a6abb40970e1b5b6
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cli-tkn-rhel9@sha256:58bbf82fcc6569a26265a5cdf13f682842cd477fbac1a920a6abb40970e1b5b6
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/serve-tkn-cli/pipelines-serve-tkn-cli-rhel9@sha256:b6e3ffabb0906101a3126ad5c4e9d9e54decb5fcd317dde35c9de1255f931cd8
  - name: IMAGE_ADDONS_TKN_CLI_SERVE_INIT_CONFIG
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/serve-tkn-cli/pipelines-serve-tkn-cli-rhel9@sha256:b6e3ffabb0906101a3126ad5c4e9d9e54decb5fcd317dde35c9de1255f931cd8
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-manual-approval-gate-webhook-rhel9@sha256:a066a5431de11a4f8763bc45eee4dad64887695fa3bb0875f65c04c669a01855
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-manual-approval-gate-controller-rhel9@sha256:45bef054c5ce44660405e04a507cd775a2effadd1b7fafbb5cd0cda0a69f4eae
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-controller-rhel9@sha256:b7d5caf40c278fc769ad60a651905f36235596e80d224d508fe6dfd1c8e079a1
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-webhook-rhel9@sha256:6eb36b10a5b03f08893f119c83a7e97be614f45fc9515dfc394d05294633ac15
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-watcher-rhel9@sha256:cbe06b6508641755253bcdd2d63085935a4c551c4680fa7976c08792c6b5f3b6
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-cli-rhel9@sha256:32d3aa6042c7960ad7d3dd3ef6c4382c9ad5744a79a64944d44d9795fcdac192
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-rhel9-operator@sha256:baaa63dc8e5495495b07dde79dc986bc2a83a92f20f1f9608a8530dd0c3ebd86
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-rhel9-operator@sha256:baaa63dc8e5495495b07dde79dc986bc2a83a92f20f1f9608a8530dd0c3ebd86
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-operator-proxy-rhel9@sha256:af4ab2195d91f83298bb15b865a223f818854f36edf5dcd5991a7f44a7aa5c96
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-operator-webhook-rhel9@sha256:fb4fb6377bdec42f616bf5ac101dc669f639fea8c187f5968c838f889cc7639a
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cache-rhel9@sha256:3fa6b7772a4e9a0f344e0f80110a0b9287c9e60597a21f96ab2a8c0efeefda6b
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cache-rhel9@sha256:3fa6b7772a4e9a0f344e0f80110a0b9287c9e60597a21f96ab2a8c0efeefda6b
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-console-plugin-rhel9@sha256:bb058b3de08a97a38b1eb1c65df636dcb0632194c30c4d57569762097f9b6b86
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-operator-bundle@sha256:55e1782ed857e8674b35cc4fdb2c3e1a8b1346f423dfd543ef7dd23f4f37bccc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-opc-rhel9@sha256:736e130794c7326c5682df64e8ad0cacce11f1c3445ecc3225040c18d3f73198
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pruner-controller-rhel9@sha256:48a151b923a5fac02946c508bda9f4503c218ff7e080466f5e97469136175424
  - name: IMAGE_PRUNER_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pruner-webhook-rhel9@sha256:322d84268ed64620e864cc17294d1dd2ab8d2aef3656f6052ffe625d13f9648b
  # Scheduler
  - name: IMAGE_SCHEDULER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-scheduler-rhel9@sha256:ec8e3228876a838010db9b3e5d5532e051dc08aa52c724d3f923230dccba231f
  - name: IMAGE_SCHEDULER_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-scheduler-rhel9@sha256:ec8e3228876a838010db9b3e5d5532e051dc08aa52c724d3f923230dccba231f
