versions:
  current: 1.20.1
  previous: 1.20.0
  previous_range: 1.19.0
  channel: pipelines-1.20
  openshift:
    latest: 4.20 # lastest GA'ed openshift
    min: 4.12 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-controller-rhel9@sha256:4d05c794b35907053d8ec927575097c6a138e9096415265fe2a5ec1a10fd43ff
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-webhook-rhel9@sha256:7bddad9ea3e77f285ece29ed67b405f4599cb54fa6a81e73c11cefa4cca3bd4d
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-resolvers-rhel9@sha256:4cd8f73f95612c82ab45dd193cae626a986f836ddefdf33ab37a9e2a991f7461
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-events-rhel9@sha256:3fc9679673cf7c9da183c303e1e4113419043e9346ea92cc964eccbbc601e934
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-entrypoint-rhel9@sha256:b55c638a96874619f524e4d227c117188d8395a0d3cc21e3ca63d60ba01af174
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-workingdirinit-rhel9@sha256:deab3b3997b0072a26a2e98309ef58f44bc684dc701da991d8d42d6c2ed4e5f2
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-nop-rhel9@sha256:8c414aac30ac5f636ab9636fbf60ea5bf07ae7ad8a4c90c021b3ae7ada1d4738
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-entrypoint-rhel9@sha256:b55c638a96874619f524e4d227c117188d8395a0d3cc21e3ca63d60ba01af174
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipeline-sidecarlogresults-rhel9@sha256:e943501d76ed9fdcb2201fafcf441c182e68d454f3818500d1aae7a36ed193ed
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/triggers-controller-rhel9@sha256:83133ea600d088c64e10a106d0d5659ffafaef20d17580206f34a9bd67ae608a
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/triggers-webhook-rhel9@sha256:42de551330f5db603fe5ec8e03b7cbb01dc269a1b5cc57edd2cde5766088bca7
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/triggers-core-interceptors-rhel9@sha256:8e5256a50ca28a273985821fd8962572cb8142f5f52f561d30d02ad3bcbfc528
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/triggers-eventlistenersink-rhel9@sha256:66c21387bfff55533db78cb7f90655203026fb5d5ae1a5af10b5ac25e998068c
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/chains-controller-rhel9@sha256:5468c90739eda2f644df789714c42a5ffb1ef75ed4f2a7b26480fc2d16b081ed
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/hub-db-migration-rhel9@sha256:1bc2929e271f8658487b61d69f19fe4716df790b7a79a23472d46614c81ae908
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/hub-api-rhel9@sha256:8c9e1b7d21f325835a703172e5d501cc644bce316324cd18b8ca8127276f6aa8
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/hub-ui-rhel9@sha256:92533a578c03dfe152e4de5de2fb1f0d8c90521b3a94debfa438cef6f57f99d7
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/results-watcher-rhel9@sha256:1c3d1ede88ae11adbe9b94e67a14ee22b6ce9acf6748fd738cceeef8bc2a376a
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/results-api-rhel9@sha256:f6a91cae22b6e804e9d477e019e615fa97bdb30efcb8c5726b14612488dbed2a
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/results-retention-policy-agent-rhel9@sha256:c624fcada7ce29149406b1fdc78cd50b4616ad2d5332b9330d96204cd10fd18d
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cli-tkn-rhel9@sha256:07b0603e296bba2a79dc9256ead8ffc27c4dd4c1b22e8fa7721bf2817e58f9f1
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cli-tkn-rhel9@sha256:07b0603e296bba2a79dc9256ead8ffc27c4dd4c1b22e8fa7721bf2817e58f9f1
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cli-tkn-rhel9@sha256:07b0603e296bba2a79dc9256ead8ffc27c4dd4c1b22e8fa7721bf2817e58f9f1
  - name: IMAGE_ADDONS_TKN_CLI_SERVE
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:115eea1a5ca87f3b6b72db1df05b7386bf73dc70c9c2e4dc5e1a66700d960c37
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/manual-approval-gate-webhook-rhel9@sha256:050df6d37fc4dd87f3e5dd04619827650ad7ee5d0b8441a0c79247e8b4b06085
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/manual-approval-gate-controller-rhel9@sha256:3f16ab5b05d83af164ec7c57ae67b002f5acca94d33579aca3150e753b6e4c56
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipelines-as-code-controller-rhel9@sha256:f50de5d2f4d3fcdf4738753eaed4a57f648845dd73afeab12d30a71f507863d5
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipelines-as-code-webhook-rhel9@sha256:da8a6eac416718089c6e247209d409324967652d3939e19d7d52273acc5654cd
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipelines-as-code-watcher-rhel9@sha256:c4c871f74d8612c46358ef32cb0356167a1f92fd51912e9d4080de6db12bb20e
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pipelines-as-code-cli-rhel9@sha256:816bf626bb3f04caaca91b98d44f239e63ed70f892e323341dfad476694a4d0b
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-operator-rhel9@sha256:158ed9b91be28fcdcdfb7407b0ddc57c32d10aeebef291262097ae77b5f74966
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-operator-rhel9@sha256:158ed9b91be28fcdcdfb7407b0ddc57c32d10aeebef291262097ae77b5f74966
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-proxy-rhel9@sha256:009721110b4ae318f361d4a0a7ac03a828d8e3f6bf16874011fe11b1b7c5034d
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-webhook-rhel9@sha256:3410770bda0b931233cf80b0afac95a480cf5711003f71db8cfb17a85a5f6725
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cache-rhel9@sha256:5a2323d9743e72986c695bc1313208bb631e05aabf0b1d49103f7d9cbbb2c331
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/cache-rhel9@sha256:5a2323d9743e72986c695bc1313208bb631e05aabf0b1d49103f7d9cbbb2c331
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:52444eaec63f4ff5fcf26d94d7b4d9bc32708b79bd8c20d5b7b569f1a01bcf8d
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:52444eaec63f4ff5fcf26d94d7b4d9bc32708b79bd8c20d5b7b569f1a01bcf8d
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:52444eaec63f4ff5fcf26d94d7b4d9bc32708b79bd8c20d5b7b569f1a01bcf8d
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:52444eaec63f4ff5fcf26d94d7b4d9bc32708b79bd8c20d5b7b569f1a01bcf8d
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:52444eaec63f4ff5fcf26d94d7b4d9bc32708b79bd8c20d5b7b569f1a01bcf8d
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/git-init-rhel9@sha256:52444eaec63f4ff5fcf26d94d7b4d9bc32708b79bd8c20d5b7b569f1a01bcf8d
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/console-plugin-rhel9@sha256:34901e547bcfcdb85635c1156a1a49e65d134afccd059e5142f67089bb30e327
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/operator-bundle-rhel9@sha256:8de2dc8bb94494de1940be4e53c384e8351bae02fc17ed0fb5abd2e4416d546a
  # opc
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/opc-rhel9@sha256:c3610bf005e445a8ba9d0709403d064b86ba6e1cc1fc77dce9db94c92ec78777
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-20/pruner-controller-rhel9@sha256:0ebd14fd77cc45eaf804aa86b400541a143b798b59a7fadcec7f683a0a1e203e
