versions:
  current: 1.22.0
  previous: 1.21.0
  previous_range: 1.21.0
  channel: pipelines-1.22
  openshift:
    latest: 4.20 # lastest GA'ed openshift
    min: 4.16 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-controller-rhel9@sha256:18f44d56098bd4f6c2e4aace7f08420ac256e79d96fd6f43a06053bdca365fba
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-webhook-rhel9@sha256:c88741d3e2a2c268c8e730e2b70d73cbeadd49a08460891cff113004a17ac1dc
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-resolvers-rhel9@sha256:2d18a832bb0f7a2a204b2b40178dfd11615ed1028b05fb7bc21177a5edc7b82e
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-events-rhel9@sha256:3cd69f47927731fd648a3575db4a854a8feb07dc2cef217d8f795920a37ea006
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-entrypoint-rhel9@sha256:d66acd75eeba4704579bf69f62c777d86e88b016b2473718d67767ce8f943dcd
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-workingdirinit-rhel9@sha256:317dc152495c29e41aa6cbaa681642550756269e725e1e50c8dd6d08301c987b
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-nop-rhel9@sha256:1c3ddca02c5747fd4cd230b6f40b86a0b214303566bc2b317422af1bd6776d2e
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-entrypoint-rhel9@sha256:d66acd75eeba4704579bf69f62c777d86e88b016b2473718d67767ce8f943dcd
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-sidecarlogresults-rhel9@sha256:5b4744dfb327c4a01bd51cca41a18ca1069f14069eee5b063855e587595b77a0
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-controller-rhel9@sha256:f44c70d5104a2f15494be9e74d90196a9ae480a120baf896efe1c8a6fe1795b6
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-webhook-rhel9@sha256:1ce820b8fc2a15c6c3536ab61bddc998512b1966be9f0dbaa66fa8595be98384
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-core-interceptors-rhel9@sha256:3d03fc434e9f7f71362ea3e5567d6b2959d3e61f7b4f9ec938d6e4c8d2cef496
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-eventlistenersink-rhel9@sha256:8cbac26c7f5182c182f5909ae0dc38748a00555f4d55473b7c067c9b0fcc5569
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-chains-controller-rhel9@sha256:5cc6defbe041e05cc3fbcae943fc5e922302ea73737bfa395173ce0aa396d9c9
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-hub-db-migration-rhel9@sha256:381f34b5903b5774ee851e879832bb070dd4efef6bd6401928fbe8842ee8a3b4
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-hub-api-rhel9@sha256:b435a641a838620b8bd6792e8942e53cc1f65fd6338b2152b14ae504a87f4501
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-hub-ui-rhel9@sha256:131f6b93518fa18548207dd1a776f9d08ed67b846ec28ab7ca8fd597dd981560
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-results-watcher-rhel9@sha256:d1e01fc18769fb4099f0c1bf3b1d6e02229d12de9dd5fa7c60ed6e0782d80244
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-results-api-rhel9@sha256:f93953452b0530f186a0366552e3e89739a809b34ffe5ca03ab1f5c1747c7031
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-results-retention-policy-agent-rhel9@sha256:8314d57a051d387c8d78e93bb139dc35e7b1211aa9549dee205113b0280d566f
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cli-tkn-rhel9@sha256:220012a2cd9794ee78a59f163b0c2ab0d2ebedfb823734f548824948c67974ad
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cli-tkn-rhel9@sha256:220012a2cd9794ee78a59f163b0c2ab0d2ebedfb823734f548824948c67974ad
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cli-tkn-rhel9@sha256:220012a2cd9794ee78a59f163b0c2ab0d2ebedfb823734f548824948c67974ad
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/serve-tkn-cli/pipelines-serve-tkn-cli-rhel9@sha256:ec0648832e6110e1e6564c1185395ecc0740913fd4359ecdb653f22f74b6070c
  - name: IMAGE_ADDONS_TKN_CLI_SERVE_INIT_CONFIG
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/serve-tkn-cli/pipelines-serve-tkn-cli-rhel9@sha256:ec0648832e6110e1e6564c1185395ecc0740913fd4359ecdb653f22f74b6070c
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-manual-approval-gate-webhook-rhel9@sha256:2b3e070b7c2ec326a0c161c5e478a9e38083d0f564e2e4a39ed2f92c002e632a
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-manual-approval-gate-controller-rhel9@sha256:6c5458dd0e238c7b9712ed64c0c6c46cba32d04bbb2127bb76f6ff29516ef709
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-controller-rhel9@sha256:349320627a57be40f9dc3a0856ef870031fd36039831b53ea713212efebafb73
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-webhook-rhel9@sha256:955ffd59551e18808307b9fa894e692d927857ffd1c62a288b54498c07ce8df0
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-watcher-rhel9@sha256:cbe06b6508641755253bcdd2d63085935a4c551c4680fa7976c08792c6b5f3b6
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-cli-rhel9@sha256:d7099b8c97ab8f978d864ba61b17ef5fea19da7831fb6e61f64a54057512a2ec
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-rhel9-operator@sha256:e2919533ed6564bf349f5b74b47bb1b17084a459fb381471f5ca5d0715d1c6c6
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-rhel9-operator@sha256:e2919533ed6564bf349f5b74b47bb1b17084a459fb381471f5ca5d0715d1c6c6
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-operator-proxy-rhel9@sha256:9bd10a71bbb679dcc18c0640de32074a8265df844f112d97e3fc1b8548ae9993
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-operator-webhook-rhel9@sha256:d000fd479baa32f6c009dc2170005023599528e6389e4384d6e13ca044772c27
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cache-rhel9@sha256:754b68efffa8bc1c959725e80e85292f758e0569aff9b0e7d8652eb1d5254e6d
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cache-rhel9@sha256:754b68efffa8bc1c959725e80e85292f758e0569aff9b0e7d8652eb1d5254e6d
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:2f8c821d2bcfef42e4be8d0867f83d9517e2ca88fc74981961789454953b4b07
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:2f8c821d2bcfef42e4be8d0867f83d9517e2ca88fc74981961789454953b4b07
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:2f8c821d2bcfef42e4be8d0867f83d9517e2ca88fc74981961789454953b4b07
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:2f8c821d2bcfef42e4be8d0867f83d9517e2ca88fc74981961789454953b4b07
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:2f8c821d2bcfef42e4be8d0867f83d9517e2ca88fc74981961789454953b4b07
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:2f8c821d2bcfef42e4be8d0867f83d9517e2ca88fc74981961789454953b4b07
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-console-plugin-rhel9@sha256:1fcee21d2090793c66ac1be871f2f03970f447f77875702765e9efe8ae2d1716
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-operator-bundle@sha256:779edc8a63d0c5dcd746a61e95eff394a394cedcd6238aed8829c03095cd404b
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-opc-rhel9@sha256:1ae8df50a48afd0f2c5e45d56bb7aa6a99168704157fa7827057acd834c2e905
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pruner-controller-rhel9@sha256:63b5888a87cf45ae008f8b0241394ee59760fbc659ab200536c204cf1b345546
  - name: IMAGE_PRUNER_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pruner-webhook-rhel9@sha256:34e66d49dfaa5b02c0eea281ee73e77f75f41f2b09312df03374da300778066f
  # Scheduler
  - name: IMAGE_SCHEDULER_MANAGER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-scheduler-rhel9@sha256:ba1fc862eea6a3ac848de3026d87f065327312ddbde3623ad00cd945795fc867
  - name: IMAGE_SCHEDULER_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-scheduler-rhel9@sha256:ba1fc862eea6a3ac848de3026d87f065327312ddbde3623ad00cd945795fc867
