versions:
  current: 1.18.1
  previous: 1.18.0
  previous_range: 1.17.0
  channel: pipelines-1.18
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.15 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-controller-rhel9@sha256:b550a8bc2a87d07a5b22a3ec3fb83efd8eb26ca6e80d404f2e453cc9b8434da7
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-webhook-rhel9@sha256:f7b5c9b88306a91787b4bb9bd8460aaf4e5a2f480c0d1897e94d64a562086878
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-resolvers-rhel9@sha256:293f4af56e923c9110de4f2c850e18ad2870f172d8e41700779802a976500a8a
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-events-rhel9@sha256:fa5c456fc91319c55fac9a011dc7bb32ef85db293c73d74436e903b76ceb4349
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-entrypoint-rhel9@sha256:b9675b22bc8759903472c1eb0e03f90c75460f02799d894294c161641cad9414
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-workingdirinit-rhel9@sha256:e9eccd7399d7d7071614ce89cb6b8be796069bb5ae18852b1d6832a991a2d853
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-nop-rhel9@sha256:e1640b4b302c5b68bde2fc91dda6f1aa3c07db7ae082a2fc88903414db82a383
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-entrypoint-rhel9@sha256:b9675b22bc8759903472c1eb0e03f90c75460f02799d894294c161641cad9414
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipeline-sidecarlogresults-rhel9@sha256:16d799503674641d4690822edc9c399c61429ccd31621d295eee4a4d1ef1c076
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/triggers-controller-rhel9@sha256:8fec8e7a8b3e5182c67104de4e3abe32593b682c4a8986d1e9ab835dafb95ff4
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/triggers-webhook-rhel9@sha256:1b57b64657eca0002145100bae262a19f02eb40068e07994df467e28a1618f90
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/triggers-core-interceptors-rhel9@sha256:e27a30d471dda4983a5b8192709d283a9d082558f3caf31b30db2214e418b017
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/triggers-eventlistenersink-rhel9@sha256:776d34b0ea2e35c11ad4050e6b40cf4b40c84dbe0d5f3e6ad669c494a210ea8e
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/chains-controller-rhel9@sha256:409c14649d8e7007d4b72b6feffb71dabd26322bf2a7c77f5307f2546fdfe81b
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/hub-db-migration-rhel9@sha256:eaad37453a5ebef51c28d4a068f56e9f394e710c72bb86342cd2189001420836
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/hub-api-rhel9@sha256:72901cf4e091fe5f6a577144fdffaea8570712e9887a8bd715d5ae5bc346ff1d
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/hub-ui-rhel9@sha256:e63d956a0534f2e726301e00e877c4fe2f34ca4559e59d2df7567c04ded311a3
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/results-watcher-rhel9@sha256:c20ab6fa719506bca942669ea84b113335b05df3ed275257b88be234cade7c8d
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/results-api-rhel9@sha256:6abc903c784bb455e1f2fde45a48afe775239668e1d0dbc1b3cc6afca3c0b477
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/results-retention-policy-agent-rhel9@sha256:0a60ce46c05256c74f770901e0bb79ad89e88ba882b643c1ff7b2a1738463acc
  - name: IMAGE_RESULTS_POSTGRES
    value: registry.redhat.io/rhel9/postgresql-13@sha256:36647bd6d50d2e0e9c99ecf190bd515577c7ce9476e49d927c4d4065011e3441
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cli-tkn-rhel9@sha256:1ea7d0b5b938a90da6a990661c0856d4b670e40fd8553aa3390d168684456c14
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cli-tkn-rhel9@sha256:1ea7d0b5b938a90da6a990661c0856d4b670e40fd8553aa3390d168684456c14
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cli-tkn-rhel9@sha256:1ea7d0b5b938a90da6a990661c0856d4b670e40fd8553aa3390d168684456c14
  - name: IMAGE_ADDONS_TKN_CLI_SERVE
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel9@sha256:d055d2b35a663aef3e1aafdbed0b12957867c0670c946ebae66e9c44a768bda2
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/manual-approval-gate-webhook-rhel9@sha256:e6a7738cdb0e8aa9e1af381273b1c18ec1414b08a66fc851f6e11e5aa7a6706f
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/manual-approval-gate-controller-rhel9@sha256:20e19c02efdecf94a7b16483047e5db81c50dc2a0aa59d4895067e6c7769efcc
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipelines-as-code-controller-rhel9@sha256:80d441ec5d07c5059277a3a9173a35dfc0b8372d6e4d7823514131a94bae3fd7
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipelines-as-code-webhook-rhel9@sha256:cd28c2c90dd340324b0d8709640cd7636f28286114b0023649b6e21be13e03c2
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipelines-as-code-watcher-rhel9@sha256:96f5e1922fb9d6dc17e271576dda9bd032bd6dcc04e7496fb15a2f6b5871cd67
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/pipelines-as-code-cli-rhel9@sha256:2ba6782af0d7e5c4d623de31814f43f4f7c3c38d09b57705021957d334067f87
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-operator-rhel9@sha256:c90a9c3a20f088241980b76986ba4f43b0243fd6d94a826fa7b5888e01c13093
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-operator-rhel9@sha256:c90a9c3a20f088241980b76986ba4f43b0243fd6d94a826fa7b5888e01c13093
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-proxy-rhel9@sha256:e2b4c3b505c4b5aa36f8a5e661389b0de4e799c74c2c7f16a065e5522b438e89
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-webhook-rhel9@sha256:8ae0ca6411e4fcd5c0605344bc6930cf122ffd80e71199509d58423a8b41de1d
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cache-rhel9@sha256:3964c3248dfb1006ea9a46295baf7f8cfa71952d6b9863b52f87e8f3d7863b1e
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/cache-rhel9@sha256:3964c3248dfb1006ea9a46295baf7f8cfa71952d6b9863b52f87e8f3d7863b1e
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:14147edcea47f0dc53f15dd78a735fe18b13b0ed4c1d972f279a43a9a2b2a611
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:14147edcea47f0dc53f15dd78a735fe18b13b0ed4c1d972f279a43a9a2b2a611
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:14147edcea47f0dc53f15dd78a735fe18b13b0ed4c1d972f279a43a9a2b2a611
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:14147edcea47f0dc53f15dd78a735fe18b13b0ed4c1d972f279a43a9a2b2a611
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:14147edcea47f0dc53f15dd78a735fe18b13b0ed4c1d972f279a43a9a2b2a611
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/git-init-rhel9@sha256:14147edcea47f0dc53f15dd78a735fe18b13b0ed4c1d972f279a43a9a2b2a611
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/console-plugin-rhel9@sha256:97611715856eaf69ab63a9548c7db4775f6730a2379ae99c1a34b04218e646de
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/1-18/operator-bundle-rhel9@sha256:296c177edc308b14ccd0cd9230eaf23b561559fd703982252b44a679881e3e58
