versions:
  current: 1.22.0
  previous: 1.21.0
  previous_range: 1.21.0
  channel: pipelines-1.22
  openshift:
    latest: 4.20 # lastest GA'ed openshift
    min: 4.16 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-controller-rhel9@sha256:f7144f9e8fc13515b642ddfe35c3acb915766f4ff028da6c8e96e32aebbe3d6a
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-webhook-rhel9@sha256:fa90c2e31f925150641f37e0d71e4d386bbb13fa072a469b33c99266587dfa32
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-resolvers-rhel9@sha256:a4c6130486f9b86e6441ae5c4d7d49c65b85af0af556f4e6d54d76c7e939d835
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-events-rhel9@sha256:57bf512e42ffe107b8a238744f81b541a1a036da7f097d6a94ca032b70fe0676
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-entrypoint-rhel9@sha256:dc2a36ccd2e1c0e0642f72320483701c23f1ee86643a983b4b29500ba1ad69c9
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-workingdirinit-rhel9@sha256:1d6028f2844ffe64fc807e3e0c343c4e4b17d1a7f9843f4c78e6bf985811ef39
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-nop-rhel9@sha256:af5eeb0fa444a6869d5893bd8202bb516ad9505526c4efa25c5f3e3b0841ca14
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-entrypoint-rhel9@sha256:dc2a36ccd2e1c0e0642f72320483701c23f1ee86643a983b4b29500ba1ad69c9
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-sidecarlogresults-rhel9@sha256:ea8915c77b1cebaaeb01b8c23a830268d1bf83da636af9bb53766d3bb4d05495
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-controller-rhel9@sha256:c0c518b7e2bbca4d629b70fcefacf0f1cf0f53b69b06d6dc2b51ce339f9f10e9
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-webhook-rhel9@sha256:b0890a41f56df3949ce070633d547d2f08dba2b24b6cc3485329456a7c8ece3c
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-core-interceptors-rhel9@sha256:3a570336324f19cf6afce351d854b2bb045909bf9b962b306cf1ae7f87837ee2
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-triggers-eventlistenersink-rhel9@sha256:4c3c5c9c2f74b4ca057336f1888c8925d8af7d9e507888f07554e4331eac2c82
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-chains-controller-rhel9@sha256:29fd6a8d7bdff9a196080b6a9996208b9d3cc91fc689b4117ae287ac3f78d249
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-hub-db-migration-rhel9@sha256:0589b17a0c2feeb0c0c84b8a75f71c7642aabfbb7e613a6e4d41d685d5378a6f
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-hub-api-rhel9@sha256:75a9c288ec225a2d73c016edbd8e1569f1ce27b40f8423e359552a5612f19759
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-hub-ui-rhel9@sha256:89c99753a87998a4098a4445c6417ae309644b5fe490a409552baa769986c871
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-results-watcher-rhel9@sha256:60b87a71ac2d4f4d6aca01f2c66e96741cd9de936b483f83141baf14f06e9e0f
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-results-api-rhel9@sha256:4206312c75273d0f5ebb28affaabaec2d12bf880894ac4e4c0028caa51f7c13c
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-results-retention-policy-agent-rhel9@sha256:6139a5e8fa2b4257e4843eaa1839d145e93f3d15987dc6970a2591062334f25f
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cli-tkn-rhel9@sha256:9e95cea384268d4f9d9d15f5da2e6f29e52209f2b16b63bab856ce9827f8a5e4
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cli-tkn-rhel9@sha256:9e95cea384268d4f9d9d15f5da2e6f29e52209f2b16b63bab856ce9827f8a5e4
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cli-tkn-rhel9@sha256:9e95cea384268d4f9d9d15f5da2e6f29e52209f2b16b63bab856ce9827f8a5e4
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-serve-tkn-cli-rhel9@sha256:ac27f336d3e4e9e2538a867c1a956ca8328428948dd72d9ad6456c346ab48989
  - name: IMAGE_ADDONS_TKN_CLI_SERVE_INIT_CONFIG
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-serve-tkn-cli-rhel9@sha256:ac27f336d3e4e9e2538a867c1a956ca8328428948dd72d9ad6456c346ab48989
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-manual-approval-gate-webhook-rhel9@sha256:76aae5f615bb19fa637bd030e5c5dc4cce827e033301d0152ab9f86e6c0864fe
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-manual-approval-gate-controller-rhel9@sha256:a5955610a37c3fcd6fab43890f25829d79dafcb91a567e6067a00b4487d7aec3
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-controller-rhel9@sha256:7b2ce5c38a5941d51aae780b498eb0a5b4cc8a9bd84cf001dadf154b2ceb60b8
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-webhook-rhel9@sha256:d5154c295c48651fd2134af7c9935fabd3a2214fd4878e57f94307ac90808f27
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-watcher-rhel9@sha256:bad5bf114f0e9582746a8e55e571a1fb378c009392ab3fc92ae2b54e4251e5ac
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pipelines-as-code-cli-rhel9@sha256:2217f52b3a7947fd0b0c939e642869323c941f1888522e5882b9c448e46acc1b
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-rhel9-operator@sha256:3044e54fb46809bd6b0a0da947d7852ea55b0e6f0bbff5fa7812db1c43f52d31
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-rhel9-operator@sha256:3044e54fb46809bd6b0a0da947d7852ea55b0e6f0bbff5fa7812db1c43f52d31
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-operator-proxy-rhel9@sha256:19751e2094919e7c0fd7a96fabb38d8d0e8ac6217171a8d2ceb8965236dd3e37
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-operator-webhook-rhel9@sha256:4c0a87b29cdb64eb0357d8e871d49c949917d79e946b29a80cf5225d7c1e1f65
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cache-rhel9@sha256:1b9dbd7cae8009942d25b99e0eab414eed9f1ce18ecc113856d347764cc65527
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-cache-rhel9@sha256:1b9dbd7cae8009942d25b99e0eab414eed9f1ce18ecc113856d347764cc65527
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-console-plugin-rhel9@sha256:b90510e3bc8feb9cfd04cb24d4ccc15cb9039187e646298830f66ec73303603a
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-operator-bundle@sha256:313720e14a3f1c3bbe6df53adb812aa58525b0669eec633587f6ecdafafda194
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-opc-rhel9@sha256:ae7ce6ffc5b084276e6e754a0f89493cd25cd78c5b515c31ec81c31b9c716e2c
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pruner-controller-rhel9@sha256:a0778ab491db10c4134e21aa6c9b98a5b3e3fc4f0f64b9ebd803ff4af730f689
  - name: IMAGE_PRUNER_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pipelines-pruner-webhook-rhel9@sha256:955bf9666f016d58d19db73df73009d7d9802015ee9e3e2761c5c0cf52a99de9
