versions:
  current: 5.0.5-749
  previous: 5.0.5-748
  previous_range: 1.20.0
  channel: pipelines-5.0
  openshift:
    latest: 4.20 # lastest GA'ed openshift
    min: 4.12 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-controller-rhel9@sha256:bcd247afad787369b6398b9c80c8248a70443b2a50e5b421725a1b73e78dab45
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-webhook-rhel9@sha256:16b4cb6797a19bf40450fc60f9184767a5191a2cb6da410c02faef918e773f2e
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-resolvers-rhel9@sha256:6a0977a2c1bff6eccccb6c0f43346e94c15e5a8f4efa04c86c07b16b034cadbe
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-events-rhel9@sha256:d127085a586d5d1a8412ba0092216b3e7e87bc66ad948041a7efa5a200e39e4f
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-entrypoint-rhel9@sha256:be220407b502731a9bf03b753725670930ea91b972f70c950ef76264590f993e
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-workingdirinit-rhel9@sha256:1966830a2bdafa5e7dd142d97cbcb3d1fffc643c7de1704b312425e9ed73b4ed
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-nop-rhel9@sha256:af31935144a3de67cebd1d1fa8ef652b6ced2b96e32cc06757a800a80e3899de
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-entrypoint-rhel9@sha256:be220407b502731a9bf03b753725670930ea91b972f70c950ef76264590f993e
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipeline-sidecarlogresults-rhel9@sha256:a1687042b5a5e2777fda97079ab26f683b2b843d4427a541430fb8c4e85376cb
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/triggers-controller-rhel9@sha256:7eaf44ffc5fed8c9da69c18629b0268038534b0a2692b8c8d7054cb53623feac
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/triggers-webhook-rhel9@sha256:541b93d05d36ea37e9e688b25f9bacab6ad3ca92052b6975694bfb2332c0340b
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/triggers-core-interceptors-rhel9@sha256:57f7ec2bacc494e3cf8a268e317497d317269e014877e28d570b62b70fa9d0ea
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/triggers-eventlistenersink-rhel9@sha256:7b0c267eb208560e3a997f68d75c44eeaa03211096e951bbf78f787bf6ecfa47
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/chains-controller-rhel9@sha256:4029c6f4920a87bd8a0610ab1a310d1752bbbe52660d0fd8364370c9d8d9baa8
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/hub-db-migration-rhel9@sha256:84b0435aac4e93f42a81c64ae8d8fc8dc819b65deb80c1ddd64a405ee2c72273
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/hub-api-rhel9@sha256:c8443833598d8eb74859f07e92a6f3e4a20d574180d51d17527e1740c2c7a67c
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/hub-ui-rhel9@sha256:3e7428f2d1d8c1a8a9f695414b0583628a496cc65ba575b72460afcfbde8530a
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/results-watcher-rhel9@sha256:eb6e9a9c22b226efbfec080a1998529c64918988a6a37287901afb30a7654c18
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/results-api-rhel9@sha256:a5dad1b043af36296f4c68c240f1ca49653dc24425f04a2f4de653cb689625bf
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/results-retention-policy-agent-rhel9@sha256:eadc2ab083e95a76825f754c428b156d5de9713c0798ab5b3078180aa5fcfebe
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cli-tkn-rhel9@sha256:47cfda75018b713f356541ed6ab0f970cd53c16b87837aae1cabf1d2fd38b939
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cli-tkn-rhel9@sha256:47cfda75018b713f356541ed6ab0f970cd53c16b87837aae1cabf1d2fd38b939
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cli-tkn-rhel9@sha256:47cfda75018b713f356541ed6ab0f970cd53c16b87837aae1cabf1d2fd38b939
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/serve-tkn-cli-rhel9@sha256:ac27f336d3e4e9e2538a867c1a956ca8328428948dd72d9ad6456c346ab48989
  - name: IMAGE_ADDONS_TKN_CLI_SERVE_INIT_CONFIG
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/serve-tkn-cli-rhel9@sha256:ac27f336d3e4e9e2538a867c1a956ca8328428948dd72d9ad6456c346ab48989
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/manual-approval-gate-webhook-rhel9@sha256:b6a08a8073e67764ec10316887b99eb9ac4743807bf6acd368f3bac7ecea5bc3
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/manual-approval-gate-controller-rhel9@sha256:105733e51e447886658866024e1b225d84d6bef39a9226a89ba37b34c1e99b0e
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipelines-as-code-controller-rhel9@sha256:346ec0cb6f85540fbe3d189a5d3118ca6dc49a89f4daa0e5eb2af0897ea33636
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipelines-as-code-webhook-rhel9@sha256:8b27065d1ac7fa2b5c72df3aa858db7b2843da835866d94f539e66577f00e74f
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipelines-as-code-watcher-rhel9@sha256:6e386f438877e468b37d0d67797e06da88ff94d1ec44f7f666ac9a1f09c129a7
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pipelines-as-code-cli-rhel9@sha256:2217f52b3a7947fd0b0c939e642869323c941f1888522e5882b9c448e46acc1b
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-operator-rhel9@sha256:fdf9b4abb7f67ff1802449f52468bf127ade04976ad8dd9afefb31c7a84b62c8
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-operator-rhel9@sha256:fdf9b4abb7f67ff1802449f52468bf127ade04976ad8dd9afefb31c7a84b62c8
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-proxy-rhel9@sha256:300c59473b5333cd06ad397817bd0243a466bd3c8e546a9c1ce401f2c910911b
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-webhook-rhel9@sha256:7e537f8a1ab8b9dc64f5a6870134fdbeaa3b30bc21c1fab0c2f2623aa5c54c2a
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cache-rhel9@sha256:1b9dbd7cae8009942d25b99e0eab414eed9f1ce18ecc113856d347764cc65527
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/cache-rhel9@sha256:1b9dbd7cae8009942d25b99e0eab414eed9f1ce18ecc113856d347764cc65527
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  - name: IMAGE_ADDONS_PREPARE_AND_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/git-init-rhel9@sha256:7eb44962e318f67d26fca82bcd6ad6c0c31b76eca6370782c8459dbfe96ad9a7
  # console-plugin
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/console-plugin-rhel9@sha256:b90510e3bc8feb9cfd04cb24d4ccc15cb9039187e646298830f66ec73303603a
  # operator-bundle
  - name: IMAGE_OPERATOR_BUNDLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/operator-bundle-rhel9@sha256:87c669e6fbe47448b634b1546eef415c0d4ccffc1a2bc402c84040a695bca71d
  - name: IMAGE_ADDONS_OPC
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/opc-rhel9@sha256:ae7ce6ffc5b084276e6e754a0f89493cd25cd78c5b515c31ec81c31b9c716e2c
  # Pruner
  - name: IMAGE_PRUNER_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pruner-controller-rhel9@sha256:9518c4bc1cb0498caa496f72df3ffefd6d0320e38b66640268d44a78be019ed9
  - name: IMAGE_PRUNER_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/next/pruner-webhook-rhel9@sha256:e640d0e01736af6519d4341ce4b0440991e35044fd45d0a048d72af097d239e7
