//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 The OpenShift Pipelines Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShift) DeepCopyInto(out *OpenShift) {
	*out = *in
	if in.PipelinesAsCode != nil {
		in, out := &in.PipelinesAsCode, &out.PipelinesAsCode
		*out = new(PipelinesAsCodeConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShift.
func (in *OpenShift) DeepCopy() *OpenShift {
	if in == nil {
		return nil
	}
	out := new(OpenShift)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PACSettings) DeepCopyInto(out *PACSettings) {
	*out = *in
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PACSettings.
func (in *PACSettings) DeepCopy() *PACSettings {
	if in == nil {
		return nil
	}
	out := new(PACSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelinesAsCode) DeepCopyInto(out *PipelinesAsCode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelinesAsCode.
func (in *PipelinesAsCode) DeepCopy() *PipelinesAsCode {
	if in == nil {
		return nil
	}
	out := new(PipelinesAsCode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelinesAsCode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelinesAsCodeConfig) DeepCopyInto(out *PipelinesAsCodeConfig) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	in.PACSettings.DeepCopyInto(&out.PACSettings)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelinesAsCodeConfig.
func (in *PipelinesAsCodeConfig) DeepCopy() *PipelinesAsCodeConfig {
	if in == nil {
		return nil
	}
	out := new(PipelinesAsCodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelinesAsCodeList) DeepCopyInto(out *PipelinesAsCodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PipelinesAsCode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelinesAsCodeList.
func (in *PipelinesAsCodeList) DeepCopy() *PipelinesAsCodeList {
	if in == nil {
		return nil
	}
	out := new(PipelinesAsCodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelinesAsCodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelinesAsCodeSpec) DeepCopyInto(out *PipelinesAsCodeSpec) {
	*out = *in
	out.CommonSpec = in.CommonSpec
	in.Config.DeepCopyInto(&out.Config)
	in.PACSettings.DeepCopyInto(&out.PACSettings)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelinesAsCodeSpec.
func (in *PipelinesAsCodeSpec) DeepCopy() *PipelinesAsCodeSpec {
	if in == nil {
		return nil
	}
	out := new(PipelinesAsCodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelinesAsCodeStatus) DeepCopyInto(out *PipelinesAsCodeStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelinesAsCodeStatus.
func (in *PipelinesAsCodeStatus) DeepCopy() *PipelinesAsCodeStatus {
	if in == nil {
		return nil
	}
	out := new(PipelinesAsCodeStatus)
	in.DeepCopyInto(out)
	return out
}
