/*
Copyright 2023 The OpenShift Pipelines Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/openshift-pipelines/operator/pkg/apis/operator/v1alpha1"
	scheme "github.com/openshift-pipelines/operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PipelinesAsCodesGetter has a method to return a PipelinesAsCodeInterface.
// A group's client should implement this interface.
type PipelinesAsCodesGetter interface {
	PipelinesAsCodes() PipelinesAsCodeInterface
}

// PipelinesAsCodeInterface has methods to work with PipelinesAsCode resources.
type PipelinesAsCodeInterface interface {
	Create(ctx context.Context, pipelinesAsCode *v1alpha1.PipelinesAsCode, opts v1.CreateOptions) (*v1alpha1.PipelinesAsCode, error)
	Update(ctx context.Context, pipelinesAsCode *v1alpha1.PipelinesAsCode, opts v1.UpdateOptions) (*v1alpha1.PipelinesAsCode, error)
	UpdateStatus(ctx context.Context, pipelinesAsCode *v1alpha1.PipelinesAsCode, opts v1.UpdateOptions) (*v1alpha1.PipelinesAsCode, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.PipelinesAsCode, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.PipelinesAsCodeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PipelinesAsCode, err error)
	PipelinesAsCodeExpansion
}

// pipelinesAsCodes implements PipelinesAsCodeInterface
type pipelinesAsCodes struct {
	client rest.Interface
}

// newPipelinesAsCodes returns a PipelinesAsCodes
func newPipelinesAsCodes(c *OperatorV1alpha1Client) *pipelinesAsCodes {
	return &pipelinesAsCodes{
		client: c.RESTClient(),
	}
}

// Get takes name of the pipelinesAsCode, and returns the corresponding pipelinesAsCode object, and an error if there is any.
func (c *pipelinesAsCodes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PipelinesAsCode, err error) {
	result = &v1alpha1.PipelinesAsCode{}
	err = c.client.Get().
		Resource("pipelinesascodes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PipelinesAsCodes that match those selectors.
func (c *pipelinesAsCodes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PipelinesAsCodeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PipelinesAsCodeList{}
	err = c.client.Get().
		Resource("pipelinesascodes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested pipelinesAsCodes.
func (c *pipelinesAsCodes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("pipelinesascodes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a pipelinesAsCode and creates it.  Returns the server's representation of the pipelinesAsCode, and an error, if there is any.
func (c *pipelinesAsCodes) Create(ctx context.Context, pipelinesAsCode *v1alpha1.PipelinesAsCode, opts v1.CreateOptions) (result *v1alpha1.PipelinesAsCode, err error) {
	result = &v1alpha1.PipelinesAsCode{}
	err = c.client.Post().
		Resource("pipelinesascodes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pipelinesAsCode).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a pipelinesAsCode and updates it. Returns the server's representation of the pipelinesAsCode, and an error, if there is any.
func (c *pipelinesAsCodes) Update(ctx context.Context, pipelinesAsCode *v1alpha1.PipelinesAsCode, opts v1.UpdateOptions) (result *v1alpha1.PipelinesAsCode, err error) {
	result = &v1alpha1.PipelinesAsCode{}
	err = c.client.Put().
		Resource("pipelinesascodes").
		Name(pipelinesAsCode.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pipelinesAsCode).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *pipelinesAsCodes) UpdateStatus(ctx context.Context, pipelinesAsCode *v1alpha1.PipelinesAsCode, opts v1.UpdateOptions) (result *v1alpha1.PipelinesAsCode, err error) {
	result = &v1alpha1.PipelinesAsCode{}
	err = c.client.Put().
		Resource("pipelinesascodes").
		Name(pipelinesAsCode.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pipelinesAsCode).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the pipelinesAsCode and deletes it. Returns an error if one occurs.
func (c *pipelinesAsCodes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("pipelinesascodes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *pipelinesAsCodes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("pipelinesascodes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched pipelinesAsCode.
func (c *pipelinesAsCodes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PipelinesAsCode, err error) {
	result = &v1alpha1.PipelinesAsCode{}
	err = c.client.Patch(pt).
		Resource("pipelinesascodes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
