---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
  name: operator-main-bundle
spec:
  componentName: bundle
  application: operator-main
  build-nudges-ref:
    - operator-main-index
  source:
    git:
      url: https://github.com/openshift-pipelines/operator.git
      dockerfileUrl: openshift/olm-catalog/openshift-pipelines/Dockerfile
      revision: main
