/*
Copyright 2023 The OpenShift Pipelines Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/openshift-pipelines/operator/pkg/apis/operator/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePipelinesAsCodes implements PipelinesAsCodeInterface
type FakePipelinesAsCodes struct {
	Fake *FakeOperatorV1alpha1
}

var pipelinesascodesResource = schema.GroupVersionResource{Group: "operator.openshift-pipelines.org", Version: "v1alpha1", Resource: "pipelinesascodes"}

var pipelinesascodesKind = schema.GroupVersionKind{Group: "operator.openshift-pipelines.org", Version: "v1alpha1", Kind: "PipelinesAsCode"}

// Get takes name of the pipelinesAsCode, and returns the corresponding pipelinesAsCode object, and an error if there is any.
func (c *FakePipelinesAsCodes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PipelinesAsCode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(pipelinesascodesResource, name), &v1alpha1.PipelinesAsCode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PipelinesAsCode), err
}

// List takes label and field selectors, and returns the list of PipelinesAsCodes that match those selectors.
func (c *FakePipelinesAsCodes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PipelinesAsCodeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(pipelinesascodesResource, pipelinesascodesKind, opts), &v1alpha1.PipelinesAsCodeList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PipelinesAsCodeList{ListMeta: obj.(*v1alpha1.PipelinesAsCodeList).ListMeta}
	for _, item := range obj.(*v1alpha1.PipelinesAsCodeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested pipelinesAsCodes.
func (c *FakePipelinesAsCodes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(pipelinesascodesResource, opts))
}

// Create takes the representation of a pipelinesAsCode and creates it.  Returns the server's representation of the pipelinesAsCode, and an error, if there is any.
func (c *FakePipelinesAsCodes) Create(ctx context.Context, pipelinesAsCode *v1alpha1.PipelinesAsCode, opts v1.CreateOptions) (result *v1alpha1.PipelinesAsCode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(pipelinesascodesResource, pipelinesAsCode), &v1alpha1.PipelinesAsCode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PipelinesAsCode), err
}

// Update takes the representation of a pipelinesAsCode and updates it. Returns the server's representation of the pipelinesAsCode, and an error, if there is any.
func (c *FakePipelinesAsCodes) Update(ctx context.Context, pipelinesAsCode *v1alpha1.PipelinesAsCode, opts v1.UpdateOptions) (result *v1alpha1.PipelinesAsCode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(pipelinesascodesResource, pipelinesAsCode), &v1alpha1.PipelinesAsCode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PipelinesAsCode), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePipelinesAsCodes) UpdateStatus(ctx context.Context, pipelinesAsCode *v1alpha1.PipelinesAsCode, opts v1.UpdateOptions) (*v1alpha1.PipelinesAsCode, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(pipelinesascodesResource, "status", pipelinesAsCode), &v1alpha1.PipelinesAsCode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PipelinesAsCode), err
}

// Delete takes name of the pipelinesAsCode and deletes it. Returns an error if one occurs.
func (c *FakePipelinesAsCodes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(pipelinesascodesResource, name, opts), &v1alpha1.PipelinesAsCode{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePipelinesAsCodes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(pipelinesascodesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PipelinesAsCodeList{})
	return err
}

// Patch applies the patch and returns the patched pipelinesAsCode.
func (c *FakePipelinesAsCodes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PipelinesAsCode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(pipelinesascodesResource, name, pt, data, subresources...), &v1alpha1.PipelinesAsCode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PipelinesAsCode), err
}
