apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift-pipelines/operator?rev={{revision}}
    pipelinesascode.tekton.dev/pipeline: "https://raw.githubusercontent.com/openshift-pipelines/operator/refs/heads/main/.tekton/fbc-build.yaml"
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "release-v1.15.x" &&
      (".tekton/operator-1-15-index-4-18-pull-request.yaml".pathChanged() ||
      ".konflux/olm-catalog/index/v4.18/catalog/***".pathChanged() ||
      ".konflux/olm-catalog/index/v4.18/Dockerfile.catalog".pathChanged() ||
      ".tekton/fbc-build.yaml".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: operator-1-15-index-4-18-application
    appstudio.openshift.io/component: operator-1-15-index-4-18
    pipelines.appstudio.openshift.io/type: build
  name: operator-1-15-index-4-18-on-pull-request
  namespace: tekton-ecosystem-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-1-15-index-4-18-application/index-4.18:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: .konflux/olm-catalog/index/v4.18/Dockerfile.catalog
  - name: build-platforms
    value:
      - linux/x86_64
  pipelineRef:
    name: fbc-build
  taskRunTemplate:
    serviceAccountName: build-pipeline-operator-1-15-index-4-18
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
