---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build-multi-platform-oci-ta","bundle":"latest"}'
  name: operator-1-18-bundle
spec:
  componentName: bundle
  application: operator-1-18
  build-nudges-ref:
    - operator-1-18-index-4-15
    - operator-1-18-index-4-16
    - operator-1-18-index-4-17
  source:
    git:
      url: https://github.com/openshift-pipelines/operator.git
      dockerfileUrl: .konflux/olm-catalog/bundle/Dockerfile
      revision: release-v1.18.x
